apps/core/app/(default)/(faceted)/brand/[slug]/static/page.tsx
apps/core/app/(default)/(faceted)/category/[slug]/static/page.tsx
apps/core/app/(default)/product/[slug]/static/page.tsx
apps/core/app/(default)/static/page.tsx
apps/core/middlewares/with-custom-urls.ts

- Static strategy for homepage
- Revalidate every 10 minutes static routes

feat(core): static generation for homepage

---

.github/workflows/basic.yml

Rename lint job to be more descriptive

---

packages/client/package.json
packages/components/package.json
packages/configs/package.json
packages/create-catalyst/package.json
packages/eslint-config-catalyst/package.json

Adjust package.json to prep for NPM.

Remove private from package.json to prep for NPM

---

apps/core/middlewares/with-custom-urls.ts

Adds type guards for the RouteCache and StorefrontStatusCache values returned from the KV, and properly handle the case when the cache is empty. (In main at the moment an error is thrown when the cache is empty, although otherwise everything does function properly and the cache is hydrated/page rendered appropriately).
Tested locally with both the vercel KV store and dev adapter, with hydrated and empty caches.

fix(core): Add type guards to middleware, properly handle empty cache

---

apps/core/README.md

Update the apps/core/README.md file.

chore(core) update apps/core/README.md

---

README.md
apps/core/README.md

Adds new README.md banner and visual separators 💅 Thanks Georgia Hough!
_Also ran `prettier` for formatting._

chore(readme): add catalyst readme banner and separators

---

README.md

chore(core): center banners

---

packages/client/src/client.ts

Adds query complexity to client logger.

feat(client): log query complexity

---

apps/core/tsconfig.json

Leftover from cli prep work, no longer needed.

chore(common): remove unused path

---

.github/workflows/lighthouse.yml
.github/workflows/lighthouseCommentMaker.js

Targeting the correct deployment to generate lighthouse scores so that we have the accurate data.
Correct scores are now posted and that can be verified on this PR.

fix(core): Target catalyst latest deployment for lighthouse scores

---

packages/functional/tests/ui/core/components/Carousel.spec.ts
packages/functional/tests/ui/core/components/RadioGroup.spec.ts
packages/functional/tests/ui/core/components/Select.spec.ts
packages/functional/tests/ui/core/components/Swatch.spec.ts
packages/functional/tests/visual-regression/reactant/StoryBookElements.ts

Preparation on getting them working again.
> [!NOTE]
> A few tests are broken, noted below:
> 1. The Swatch and Radio UI test is broken due to the static vs. dynamic paths @jorgemoya is working on a fix
> 2. One cart test is broken as we haven't fixed that functionality yet.
Locally ran

test: fix functional tests

---

README.md

Add instructions on how to run playwright UI tests.
N/A

feat: Add documentation for running UI tests

---

apps/core/app/(default)/product/[slug]/_components/description.tsx
apps/core/app/(default)/product/[slug]/_components/details.tsx
apps/core/app/(default)/product/[slug]/_components/gallery.tsx
apps/core/app/(default)/product/[slug]/_components/related-products.tsx
apps/core/app/(default)/product/[slug]/_components/warranty.tsx
apps/core/app/(default)/product/[slug]/page.tsx

- Move components from product page to their own individual components.
Locally

refactor(core): move components in PDP to own files

---

packages/create-catalyst/src/commands/create.ts
packages/create-catalyst/src/utils/https.ts
packages/create-catalyst/src/utils/login.ts

Default to the OAuth Device Authorization Grant flow for authentication inside the `create-catalyst` CLI. 
(Additional PR description left as comments in files in this PR)
CI

feat(cli): use oauth device grant by default for cli auth

---

apps/core/next.config.js

Add a default csp policy to Catalyst.
Tested locally and on a preview deploy, using all store functionality and verifying nothing is blocked.

feat(core): Add CSP

---

apps/core/components/link/index.tsx

chore(core): simplify Link props types

---

apps/core/components/product-card-carousel/index.tsx
apps/core/components/product-card-carousel/pagination.tsx
apps/docs/stories/carousel.stories.tsx
packages/components/src/components/carousel/carousel.tsx
packages/functional/tests/ui/core/components/Carousel.spec.ts

Refactor component to improve:
- State management in parent element
- Use context for everything else
- Add keys functionality from Shadcn
- Fix issue with arrow indicators on non loop carousels
- Prevent shifting issue (still testing).
Should look & behave virtually the same.
Locally

refactor(component): carousel

---

.env.example

Updates docs to reconcile with #580 
N/A

fix(env): update docs to use correct cart token scope

---

apps/core/app/(default)/account/page.tsx
apps/core/app/(default)/login/_actions/submit-login-form.ts
apps/core/components/header/index.tsx
packages/components/src/components/navigation-menu/navigation-menu.tsx

This pr adds Account Page with subsections
Locally

feat(core): CATALYST-50 account - create account landing page

---

apps/core/components/header/_actions/header-nav.tsx
apps/core/components/header/index.tsx
packages/components/src/components/navigation-menu/navigation-menu.tsx

To improve demo experience, I changed the breakpoints for mobile nav to prevent nav overflow in certain window sizes.
Locally.

fix(core): change breakpoints for demo experience

---

apps/core/next.config.js

Reverts bigcommerce/catalyst#565
This has broken quick add, reverting until we can fix.

Revert "feat(core): Add CSP"

---

packages/client/src/client.ts

This PR updates types for shipping estimations methods.
locally

fix(client): update types for shipping costs related methods

---

packages/client/package.json

chore: publish @bigcommerce/catalyst-client@0.1.1

---

.env.example
apps/core/client/queries/get-blog-posts.ts
apps/core/client/queries/get-blost-post.ts
apps/core/client/queries/get-brand.ts
apps/core/client/queries/get-brands.ts
apps/core/client/queries/get-category-tree.ts
apps/core/client/queries/get-category.ts
apps/core/client/queries/get-featured-products.ts
apps/core/client/queries/get-newest-products.ts
apps/core/client/queries/get-product-reviews.ts
apps/core/client/queries/get-product-search-results.ts
apps/core/client/queries/get-product.ts
apps/core/client/queries/get-products.ts
apps/core/client/queries/get-quick-search-results.ts
apps/core/client/queries/get-recaptcha-settings.ts
apps/core/client/queries/get-related-products.ts
apps/core/client/queries/get-route.ts
apps/core/client/queries/get-store-settings.ts
apps/core/client/queries/get-store-status.ts
apps/core/client/queries/get-web-page.ts
apps/core/client/queries/get-web-pages.ts
apps/core/client/revalidate-target.ts
packages/client/src/client.ts
packages/create-catalyst/src/utils/write-env.ts

Allow an env variable to set a default revalidate target.
Locally.

feat(core): add default revalidate target

---

apps/core/app/(default)/cart/_actions/update-product-quantity.ts
apps/core/app/(default)/cart/_components/checkout-summary.tsx
apps/core/app/(default)/cart/_components/shipping-estimator.tsx
apps/core/app/(default)/cart/page.tsx
apps/core/client/mutations/select-checkout-shipping-option.ts
apps/core/client/mutations/update-checkout-shipping-info.ts
apps/core/components/forms/_actions/submit-shipping-costs.ts
apps/core/components/forms/_actions/submit-shipping-info.ts
apps/core/components/forms/shipping-cost.tsx
apps/core/components/forms/shipping-info.tsx

This PR extends functionality for working with shipping estimations. Now after adding shipping cost to Cart we can change/update it.
locally
https://github.com/bigcommerce/catalyst/assets/67792608/f41e56a4-0f36-412c-bd39-5b40e96b1b2a

feat(core): update shipping estimations on cart

---

.changeset/config.json
package.json
pnpm-lock.yaml

Adds initial configuration for [`changesets`](https://github.com/changesets/changesets). This PR only includes configuration, and will not result in any versioning or publishing of packages until the following steps are completed:
1. Install the [changesets bot](https://github.com/apps/changeset-bot) in the Catalyst repository
2. Add the [GitHub action](https://github.com/changesets/action?tab=readme-ov-file#with-publishing) to automate releases
3. Add action vars for `${{ secrets.GITHUB_TOKEN }}` (which allows the Changesets GitHub action to open Pull Requests for new releases and `${{ secrets.NPM_TOKEN }}` (which allows the Changesets GitHub action to publish on behalf of the BigCommerce NPM org.
N/A

feat(build): add changesets and initial changeset config

---

.env.example
README.md
docs/cli.md
docs/deployment.md
docs/environment-variables.md
docs/index.md
docs/middleware.md
docs/monorepo.md

* Initial docs for catalyst.dev/docs because docs are good
---------------
Co-authored-by: Nathan Booker <nathan.booker@bigcommerce.com>
Co-authored-by: Sarah Riehl <sarah.riehl@bigcommerce.com>
Co-authored-by: Andrea Dao  <andrea.dao@bigcommerce.com>
Co-authored-by: Erik Christensen <erik.christensen@bigcommerce.com>

docs(new): first docs for catalyst.dev/docs

---

apps/core/app/[locale]/(default)/(faceted)/_components/pagination.tsx
apps/core/components/product-card/cart.tsx
apps/core/package.json
pnpm-lock.yaml

Latest `next-intl` release fixes issue with Links.
Locally.

chore(core): bump next-intl and use Link after fix

---

apps/core/client/queries/get-product-search-results.ts

Missed this suggestion from #639.
Locally.

refactor(core): variables handling in getProductSearchResults

---

apps/core/components/footer/footer-menus/base-footer-menu.tsx
apps/core/components/footer/social-icons.tsx
apps/core/components/header/index.tsx

Fixes a few accessibility issues affecting our lighthouse score. Specifically, ensures that the footer links, mobile navigation dropdown, and social icons are appropriately inside `<li>` tags in their respect `<ul>` lists.
Tested locally against both mobile and desktop Lighthouse tests.

fix(core): Fix accessibility issues

---

apps/core/.env.example

Updates the `.env.example` in the `core` directory to match the one in the root of the monorepo. This will ensure the `.env.example` created by the CLI has all the correct variables and respective documentation.
No code changes.

chore(core): Update core .env.example

---

.changeset/yellow-ears-provide.md
packages/create-catalyst/README.md

Updates `README` for `@bigcommerce/create-catalyst` with more detailed usage. 
N/A

chore(cli): update readme with usage

---

docs/cli.md
docs/deployment.md
docs/index.md

Update broken links in docs

---

.changeset/rotten-lizards-wonder.md
apps/core/app/[locale]/(default)/login/_actions/submit-login-form.ts
apps/core/app/api/auth/[...nextauth]/route.ts
apps/core/middlewares/with-auth.ts

Tried running `next dev --turbo` and it errored out with these imports.

fix(core): auth imports

---

README.md
apps/core/README.md
docs/cli.md
docs/monorepo.md

Update references to the CLI `create` command to reference https://www.npmjs.com/package/@bigcommerce/create-catalyst

chore(docs): Update cli command

---

.changeset/small-ears-suffer.md
packages/components/tailwind.config.js

Extend instead of replace.
Locally.

fix(component): extends colors in tailwind config

---

.changeset/ten-penguins-tie.md
apps/core/client/mutations/register-customer.ts

This pr adds registerCustomer mutation to the client.
Locally.

feat(core): add register customer mutation

---

.changeset/pretty-flies-add.md

The latest changes from our client were before our changesets setup. This PR adds a changeset to trigger a new release.

chore(client): adds changeset

---

apps/core/app/[locale]/(default)/(faceted)/_components/facets.tsx
apps/core/client/mutations/add-cart-line-item.ts
apps/core/client/mutations/assign-cart-to-customer.ts
apps/core/client/mutations/create-cart.ts
apps/core/client/mutations/register-customer.ts
apps/core/client/mutations/unassign-cart-from-customer.ts
apps/core/client/mutations/update-cart-line-item.ts

This PR removes some of the types we were using from codegen. PR 1 of  ~4.

refactor(core): remove cogen usages v1

---

apps/core/client/mutations/add-checkout-shipping-info.ts
apps/core/client/mutations/update-checkout-shipping-info.ts

Continuation of https://github.com/bigcommerce/catalyst/pull/690
Removes more codegen usages.

refactor(core): remove cogen usages V2

---

apps/core/components/bc-image/index.tsx
docs/catalyst-middleware.md
docs/cdn-and-images.md

Add docs for new image functions added in https://github.com/bigcommerce/catalyst/pull/701

Docs for <BcImage> and bcCdnImageLoader

---

docs/index.md

- Update docs to include integrations section

 Update docs to include integrations

---

.changeset/olive-cups-relax.md
apps/docs/stories/tabs.stories.tsx
packages/components/package.json
packages/components/src/components/tabs/index.ts
packages/components/src/components/tabs/tabs.tsx
pnpm-lock.yaml

This PR adds tabs component.
Locally

feat(components): add tabs component

---

apps/core/package.json
packages/eslint-config-catalyst/package.json
pnpm-lock.yaml

chore: bump next packages

---

.github/workflows/playwright-ui.yml
packages/functional/tests/ui/desktop/e2e/login.spec.ts

Adds a simple test that uses test account to login and logout.

feat(core): Add test to verify login

---

packages/functional/tests/ui/desktop/e2e/cart.spec.ts
packages/functional/tests/ui/desktop/e2e/coupon.spec.ts

This change adds a new test to verify applying a coupon at checkout and consolidates all coupon related tests into its own test file.
Tested against a deployed branch.

feat(core): Test coupon application at checkout

---

docs/localization.md

Add Localization doc

---

.changeset/bright-plants-lick.md
apps/core/client/mutations/update-customer.ts

This pr adds mutation to update registred customer data 
Locally

feat(core): add update customer mutation

---

packages/functional/tests/ui/desktop/core/components/Counter.spec.ts
packages/functional/tests/ui/desktop/e2e/cart.spec.ts

Fixes tests that were broken.
https://github.com/bigcommerce/catalyst/actions/runs/8743650430/job/23994680605

tests: fix broken tests with counter and cart

---

docs/localization.md

The localization doc doesn't render because of linting errors, so this PR attempts to fix the linting issues. 
I also made a couple of grammar fixes 
cc @slsriehl for some help please 🆘

Fix linting errors

---

docs/localization.md

docs(tweak): localization

---

apps/core/app/[locale]/(default)/cart/_components/cart-item.tsx
apps/core/app/[locale]/(default)/cart/_components/checkout-button.tsx
apps/core/app/[locale]/(default)/cart/_components/empty-cart.tsx
apps/core/app/[locale]/(default)/cart/_components/item-quantity.tsx
apps/core/app/[locale]/(default)/cart/page.tsx

This is the first pass for fragment colocation on cart page. We'll split into multiple PRs for easier reviews.

refactor(core): fragment colocation for cart page

---

apps/core/app/[locale]/(default)/product/[slug]/_components/breadcrumbs.tsx
apps/core/app/[locale]/(default)/product/[slug]/page.tsx
apps/core/client/queries/get-product.ts

Define fragment on breadcrumbs component. This is part of the ongoing efforts to colocate all fragments for the PDP page.

refactor(core): breadcrumbs fragment colocation

---

apps/core/app/[locale]/(default)/product/[slug]/_components/details.tsx
apps/core/app/[locale]/(default)/product/[slug]/_components/product-schema.tsx
apps/core/app/[locale]/(default)/product/[slug]/_components/review-summary.tsx
apps/core/app/[locale]/(default)/product/[slug]/page.tsx
apps/core/app/api/product/[id]/route.ts
apps/core/components/product-form/fields/checkbox-field/fragment.ts
apps/core/components/product-form/fields/checkbox-field/index.tsx
apps/core/components/product-form/fields/date-field/fragment.ts
apps/core/components/product-form/fields/date-field/index.tsx
apps/core/components/product-form/fields/multi-line-text-field/fragment.ts
apps/core/components/product-form/fields/multi-line-text-field/index.tsx
apps/core/components/product-form/fields/multiple-choice-field/fragment.ts
apps/core/components/product-form/fields/multiple-choice-field/index.tsx
apps/core/components/product-form/fields/number-field/fragment.ts
apps/core/components/product-form/fields/number-field/index.tsx
apps/core/components/product-form/fields/text-field/fragment.ts
apps/core/components/product-form/fields/text-field/index.tsx
apps/core/components/product-form/fragment.ts
apps/core/components/product-form/index.tsx
apps/core/components/product-sheet/fragment.ts
apps/core/components/product-sheet/product-sheet-content.tsx

Progress on PDP fragment colocation, this PR now includes colocation on the product `<Details>` component.

refactor(core): product details fragment colocation

---

apps/core/app/[locale]/(default)/product/[slug]/_components/description.tsx
apps/core/app/[locale]/(default)/product/[slug]/page.tsx

This PR adds a fragment for the product description component.

refactor(core): product description fragment colocation

---

apps/core/app/[locale]/(default)/product/[slug]/_components/warranty.tsx
apps/core/app/[locale]/(default)/product/[slug]/page.tsx

~Builds on https://github.com/bigcommerce/catalyst/pull/841~
This PR adds a fragment for the product warranty component.

refactor(core): product warranty fragment colocation

---

.changeset/itchy-buttons-join.md
.changeset/itchy-humans-beam.md
.changeset/poor-apricots-whisper.md
.changeset/thin-pumpkins-search.md

Our CI is erroring again because of this same issue as in #837.
See CI.

chore: remove @bigcommerce/docs references from changesets

---

.changeset/brown-feet-smash.md
apps/core/next.config.js
apps/core/tailwind.config.js

Missed removing these due to rebase.

chore: remove additional references to components

---

apps/core/app/[locale]/(default)/cart/_actions/remove-item.ts
apps/core/app/[locale]/(default)/cart/_components/coupon-code/apply-coupon-code.ts
apps/core/app/[locale]/(default)/cart/_components/coupon-code/remove-coupon-code.ts
apps/core/app/[locale]/(default)/cart/_components/shipping-info/submit-shipping-info.ts
apps/core/app/[locale]/(default)/cart/_components/shipping-options/submit-shipping-costs.ts
apps/core/app/[locale]/(default)/cart/page.tsx
apps/core/app/[locale]/(default)/compare/_actions/add-to-cart.ts
apps/core/client/queries/get-cart.ts
apps/core/client/tags.ts
apps/core/components/product-card/_actions/add-to-cart.ts
apps/core/components/product-form/_actions/add-to-cart.ts

Add a "tags" constant instead of using raw strings for cache tags per issue #849

feat(core): Add cache tags as constant

---

apps/core/app/[locale]/(default)/product/[slug]/page-data.ts
apps/core/app/[locale]/(default)/product/[slug]/page.tsx

Share query between PDP page and metadata for react's cache deduping.

refactor(core): cache PDP page and metadata data request

---

core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx
core/components/product-card/compare.tsx

Small accessibility fixes to our PLP and PDP.
Tested locally and with a preview vercel deployment.

fix(core): fix accessibility issues on plp and pdp

---

core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx

Use Promise.all in faceted pages to optimize load
Locally

fix(core): use Promise.all in faceted pages to optimize load

---

.changeset/kind-maps-attend.md
core/app/[locale]/(default)/cart/_components/cart-item.tsx

Show original price when it is different from sale price.
Locally.

feat(core): show original price on Cart

---

core/tests/ui/desktop/e2e/search.spec.ts

Additional tests to verify search functionality using different possible ways to search.

feat(functional): Add additional tests for search

---

core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts
core/app/[locale]/(default)/account/[tab]/_components/change-password-form.tsx
core/app/[locale]/(default)/product/[slug]/_components/related-products.tsx
core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx
core/client/util/index.ts
core/components/header/cart-icon.tsx
core/lib/cdn-image-loader.ts
core/package.json
pnpm-lock.yaml

Removes unused packages and exports. Found them running `knip.dev`
CI

chore(core): remove unused packages and exports

---

core/tests/ui/desktop/e2e/checkout.spec.ts

Add checkout experience tests as a guest customer and logged in customer.
Tests are run as part of this build.

feat(functional): Add checkout experience tests

---

.changeset/tender-kangaroos-melt.md
core/app/[locale]/(default)/account/[tab]/_actions/add-address.ts
core/app/[locale]/(default)/account/[tab]/_actions/delete-address.ts
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-book.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/customer-new-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/index.tsx
core/app/[locale]/(default)/account/[tab]/page.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/password.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/shared/field-wrapper.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/text.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/utils.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx
core/client/mutations/add-customer-address.ts
core/messages/en.json
core/tests/ui/desktop/e2e/account.spec.ts

This PR brings functionality for adding new address for customer.
locally

feat(core): add new address for customer

---

core/tests/ui/desktop/e2e/checkout.spec.ts

This change enables the test verifying behavior of logged in customer checkout end-to-end experience.
Verified test locally and also this test runs as part of this PR check.

chore(functional): Enable test for logged in customer experience

---

.changeset/beige-turtles-cheer.md
core/client/mutations/delete-wishlists.ts

This pr adds delete wishlist mutation for customer account
Locally

Delete wishlist mutation

---

core/lib/kv/adapters/bc.ts
core/lib/kv/index.ts

Adds a BC kv adapter, we'll be using it for our test store for some time.

feat(core): bc kv adapter

---

core/tests/ui/desktop/e2e/account.spec.ts
core/tests/ui/desktop/e2e/checkout.spec.ts

Stablize test suite by fixing flappy tests.
Locally and checks run against this PR.

fix(chore): Fix flappy tests

---

core/tests/ui/desktop/core/components/accordion.spec.ts
core/tests/ui/desktop/e2e/checkout.spec.ts

Updates a couple of tests that are sometimes being flaky.
As part of the CI process and also verified tests locally.

fix(chore): Update tests to avoid flakiness

---

.changeset/fuzzy-ties-switch.md
core/app/api/product/[id]/route.ts

It was missing so I added it.
Locally I get the correct information.

fix(core): use customerId in product api

---

core/app/[locale]/(default)/login/register-customer/page.tsx
core/lib/bypass-recaptcha.ts
core/tests/ui/desktop/e2e/register.spec.ts

- Add register customer test 
- Add bypass recaptcha functionality for running it in CI

feat(functional): Add register customer test

---

.changeset/two-tomatoes-breathe.md
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/index.tsx
core/app/[locale]/(default)/account/[tab]/page.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/multiline-text.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/parse-fields.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/utils.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx
core/client/fragments/form-fields-values.ts

This PR brings `multilineText` field for Account & Address forms.
locally
https://github.com/bigcommerce/catalyst/assets/67792608/74c53ab9-e8a4-4f95-990e-665963b4e319

Account multilinetext form field

---

core/components/hero/index.tsx
core/components/ui/slideshow/slideshow.tsx

Refactor Slideshow to accept  `slides` prop.
Locally.

refactor(core): slideshow

---

core/components/ui/button/button.tsx
core/components/ui/calendar/calendar.tsx

Refactor button by removing cva.
Locally.

refactor: button

---

core/app/[locale]/(default)/(faceted)/_components/facets.tsx
core/components/compare-drawer/index.tsx
core/components/ui/accordion/accordion.tsx

Accordion is now an atomic component. Usages of the new Accordions component are working.
https://github.com/user-attachments/assets/d9562eb3-94bb-46a2-a02d-1321f3112e85

refactor: accordion + usages

---

core/app/[locale]/(default)/page.tsx
core/app/[locale]/(default)/product/[slug]/_components/related-products.tsx
core/app/[locale]/not-found.tsx
core/components/product-card-carousel/index.tsx
core/components/product-card/index.tsx
core/components/ui/product-card/compare.tsx
core/components/ui/product-card/product-card.tsx

Refactor Product Card component to accept props. Remove add to cart functionality from component.
Locally it still looks as expected, but no add to cart button.

refactor(core): product card

---

core/components/quick-search/index.tsx
core/components/quick-search/search-input.tsx
core/components/ui/date-picker/date-picker.tsx
core/components/ui/input/input.tsx

- Remove cva
- Change icon logic
- Create new component for Quick Search (deviates from Input enough to warrant its own component).
Locally.

refactor: input

---

core/components/ui/text-area/text-area.tsx

refactor: textarea

---

core/components/ui/checkbox/checkbox.tsx

- Remove CVA
- Add success variant
Locally

refactor: checkbox

---

.changeset/few-tools-clean.md
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx
core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/fields/text.tsx
core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/index.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/register-customer.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/checkboxes.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/date.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/multiline-text.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/parse-fields.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/radio-buttons.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/utils.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx
core/components/ui/form/form.tsx

This PR adds `checkboxField` for Account & Addresses forms.
locally
https://github.com/bigcommerce/catalyst/assets/67792608/632f1b35-855d-45f1-976b-650b814c3a28

Account checkbox form field

---

core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/ui/radio-group/radio-group.tsx

Missing prop to show error state.
Locally.

fix: radio group error state in pdp

---

core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/ui/pick-list/pick-list.tsx

Refactor pick list.
Locally still works.

refactor: pick list

---

core/components/ui/button/button.tsx

We still need to forward ref in some scenarios.
Locally.

fix: forward ref to button

---

core/app/[locale]/(default)/(faceted)/_components/sort-by.tsx
core/app/[locale]/(default)/cart/_components/shipping-info/index.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist-or-text.tsx
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist.tsx
core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/ui/pick-list/pick-list.tsx
core/components/ui/select/select.tsx

- Refactor to accept `options` prop.
- Remove CVA
- Refactor instances
Locally

refactor: select

---

core/components/ui/badge/badge.tsx

fix: use correct font weight in badge

---

core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/ui/rectangle-list/rectangle-list.tsx

Refactor rectangle list to accept an array of items.
Locally.

refactor: rectangle list

---

core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/ui/pick-list/pick-list.tsx

refactor: pick list props

---

core/components/ui/radio-group/radio-group.tsx

refactor: radio group props

---

core/components/ui/date-picker/date-picker.tsx

We need this for forms.
Locally.

fix: forward DatePicker ref

---

core/app/[locale]/(default)/(faceted)/_components/facets.tsx
core/components/product-form/fields/checkbox-field/index.tsx
core/components/product-form/fields/date-field/index.tsx
core/components/product-form/fields/multi-line-text-field/index.tsx
core/components/product-form/fields/multiple-choice-field/index.tsx
core/components/product-form/fields/number-field/index.tsx
core/components/product-form/fields/text-field/index.tsx
core/components/ui/label/label.tsx
core/components/ui/pick-list/pick-list.tsx
core/components/ui/product-card/compare.tsx
core/components/ui/radio-group/radio-group.tsx

- Refactor Label.
- Remove defined styles
- Change implementations
Locally.

refactor: label

---

core/app/[locale]/(default)/blog/[blogId]/page.tsx
core/components/blog-post-card/index.tsx
core/components/ui/blog-post-card/blog-post-card.tsx
core/components/ui/product-card/product-card.tsx

- Refactor blog-post-card.
- Removed use of BlogPostCard in blog/[blogId]/page since, although similar, it is a not the same component and elements vary.
Locally.

refactor: blog post card

---

core/app/[locale]/(default)/compare/page.tsx
core/components/ui/rating/rating.tsx

refactor: rating

---

core/app/[locale]/(default)/(faceted)/_components/mobile-side-nav.tsx
core/components/product-sheet/index.tsx
core/components/quick-search/index.tsx
core/components/quick-search/search-input.tsx
core/components/ui/sheet/sheet.tsx

- Refactored Sheet
- Quick Search is different enough from "expected" Sheet layout so instead of using Sheet component I created a new component to fit the needs.
Locally.

refactor: sheet

---

core/app/[locale]/(default)/(faceted)/_components/facets.tsx
core/components/compare-drawer/index.tsx
core/components/ui/accordion/index.ts
core/components/ui/accordions/accordions.tsx
core/components/ui/accordions/index.ts

- Remove title
- Change body => content
- Rename folder
- Use radix primitive for compare-drawer since it does not follow the accordions pattern
Locally

fix: accordions props

---

core/components/ui/gallery/gallery.tsx

fix: gallery props

---

.changeset/odd-zebras-unite.md
core/components/ui/header/mobile-nav.tsx
core/components/ui/sheet/sheet.tsx

Nav was missing title and we're not using describedby for now.
No warnings or errors locally.

fix(core): missing accessibility for Sheet and Mobile nav

---

.changeset/friendly-seas-wash.md
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/components/search-form/index.tsx
core/messages/en.json

Fixed some overlapping styles but included more context to the page.
Locally.

feat(core): add more context when no result in search page

---

.changeset/empty-eels-sing.md
core/components/footer/locale.tsx
core/components/header/index.tsx
core/components/header/locale-switcher.tsx
core/components/ui/popover/popover.tsx
core/i18n.ts
core/messages/en.json

Add a locale picker when there is more than 1 locale available.
Locally.

feat(core): add locale picker in Header

---

.changeset/weak-humans-heal.md
core/app/providers.tsx
core/components/ui/compare-drawer/compare-drawer.tsx
core/components/ui/compare-drawer/context.tsx
core/components/ui/compare-drawer/index.ts
core/components/ui/product-card/compare.tsx

Move CompareDrawer to UI components.
Locally works the same.

feat: move CompareDrawer to ui components

---

.changeset/loud-jokes-chew.md
core/app/[locale]/(default)/(faceted)/_components/facets.tsx
core/components/ui/accordions/accordions.tsx

Prop is more descriptive of how it's used.
Locally

refactor(core): change value prop to title in Accordions

---

.changeset/fast-ducks-accept.md
core/components/header/index.tsx
core/components/ui/dropdown/dropdown.tsx
core/components/ui/dropdown/index.ts
core/package.json
core/tests/ui/desktop/e2e/login.spec.ts
pnpm-lock.yaml

Add `Dropdown` component.
Use in Header.
Locally.

feat(core): add Dropdown component

---

.changeset/six-cooks-brush.md
core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/app/[locale]/(default)/account/[tab]/_components/addresses-content/index.tsx
core/components/ui/pagination/index.ts
core/components/ui/pagination/pagination.tsx

Move `Pagination` component to be a shareable UI component, update imports.
Locally.

feat(core): add Pagination component

---

core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/register-customer.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx
core/components/ui/dropdown/dropdown.tsx
core/messages/en.json
core/tests/ui/desktop/e2e/account.spec.ts
core/tests/ui/desktop/e2e/login.spec.ts
core/tests/ui/desktop/e2e/register.spec.ts

Attempt to add some stability to the account/auth pages to ensure the test runs completely.
See CI.

test(core): add some stability to some account tests

---

package.json

Updates pnpm corepack version to the latest.
See CI.

chore: update pnpm corepack version to latest

---

.github/workflows/prData.js
.github/workflows/pull-request-data.js
.github/workflows/regression-tests.yml

Fall back to using github `action-script` to fetch the pull request details which was more reliable than what we currently have.
Tested a few times as part of this change in the CI.

fix(chore): Fetch pull request details in script

---

.changeset/twenty-rocks-tell.md
packages/create-catalyst/src/utils/write-env.ts

Remove previously completed todo
N/A

chore: remove previously completed todo

---

docs/index.md

Introduces initial documentation for consuming and building native Catalyst integrations
Manual testing using Makeswift staging host

feat: initial integration development documentation

---

.changeset/hot-papayas-divide.md

Added changeset for changelog entries on the new `integrations/makeswift` folder as well as the additions to `docs/index.md`
N/A

chore: changeset for makeswift integration

---

integrations/makeswift/integration.patch

Easier diff to review: 
https://github.com/bigcommerce/catalyst/compare/@bigcommerce/catalyst-core@0.14.0...integrations/makeswift
Checkout `integrations/makeswift` branch, install deps, add `MAKESWIFT_SITE_API_KEY` env var, run `pnpm dev` and open Makeswift builder

feat: update makeswift integration for compatibility with @bigcommerce/catalyst-core@0.14.0

---

.changeset/rich-starfishes-itch.md
core/client/mutations/add-wishlist-items.ts

This pr adds _add wishlist items_ mutation for customer account
Locally

feat(core): add wishlist items mutation

---

.changeset/lovely-days-pretend.md
core/client/mutations/delete-wishlist-items.ts

This pr adds _delete wishlist items_ mutation for customer account
Locally

feat(core): delete wishlist items mutation

---

.changeset/new-maps-film.md
core/components/ui/blog-post-card/blog-post-card.tsx

fix(core): wrapping author text in BlogPostCard

---

.changeset/chilly-forks-smell.md
core/client/mutations/delete-wishlists.ts

This pr contains changes for _delete wishlists mutation_ interface to be consistent with other wishlist mutations
Locally

feat(core): update delete wishlists mutation

---

docs/index.md

[DEVDOCS-6061 ](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6061)
- Add functionality about orders to overview page
N / A

docs: add orders functionality 

---

integrations/strapi-rest/integration.patch
integrations/strapi-rest/manifest.json

Moves the pre-existing [Catalyst <> Strapi example](https://github.com/bigcommerce-labs/catalyst-strapi-storefront) into our new integration CLI model.
Locally

Add optional Strapi rest-based integration for CLI

---

docs/index.md
package.json

Clarify MIT license in package.json and docs

Clarify license in package.json and docs

---

core/next.config.js
docs/environment-variables.md

Our reduction in webpack chunks _does_ negatively affect Lighthouse scores, so I'm increasing the default and adding documentation to inform users of why they might want to tweak it and how.

Adjust WEBPACK_MAX_CHUNKS default and add more documentation

---

core/app/[locale]/(default)/(faceted)/types.ts
core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx
core/client/index.ts
core/components/footer/footer.tsx
core/components/ui/compare-drawer/context.tsx
core/components/ui/form/select/select.tsx
core/lib/kv/adapters/bc.ts
core/lib/kv/adapters/upstash.ts
core/lib/kv/adapters/vercel.ts
core/lib/kv/index.ts
core/lib/kv/types.ts
packages/client/package.json
packages/client/src/error.ts
packages/create-catalyst/package.json
packages/create-catalyst/src/utils/apply-integration.ts
packages/create-catalyst/src/utils/get-latest-core-tag.ts
packages/create-catalyst/src/utils/login.ts
packages/eslint-config-catalyst/package.json
pnpm-lock.yaml

Bump `@bigcommerce/eslint-config` to get https://github.com/bigcommerce/eslint-config/pull/265 
CI

chore(deps): bump eslint config

---

.changeset/flat-cars-vanish.md
core/components/ui/form/select/select.tsx

This PR fixes issue with 'floating' placeholder positioning for `Picklist` form field.
locally
https://github.com/user-attachments/assets/3f51f7a4-6f47-4613-ad58-85b812a0ef2f
https://github.com/user-attachments/assets/39c563b6-2fc0-4faf-9f65-6d551a17bf1c

fix(core): fix placeholder positioning for picklist custom form field

---

.changeset/healthy-bulldogs-collect.md

chore: bump client

---

.changeset/lucky-dragons-heal.md
core/messages/da.json
core/messages/fr.json

Was causing an error when using these strings. Not sure if it was incorrectly added originally, or if the bot messed it up.
Locally, it works now.

fix(core): incorrect template string for da and fr messages

---

core/messages/da.json
core/messages/de.json
core/messages/en.json
core/messages/es-419.json
core/messages/es-AR.json
core/messages/es-CL.json
core/messages/es-CO.json
core/messages/es-LA.json
core/messages/es-MX.json
core/messages/es-PE.json
core/messages/es.json
core/messages/fr.json
core/messages/it.json
core/messages/ja.json
core/messages/nl.json
core/messages/no.json
core/messages/pl.json
core/messages/pt-BR.json
core/messages/pt.json
core/messages/sv.json
core/tests/ui/e2e/account-settings.spec.ts
core/tests/ui/e2e/addresses.spec.ts

- add test for updating Account info
- fix typos in lang files
See regression test run in CI

test(core): add update account test and fix typos

---

.changeset/stupid-drinks-report.md
core/client/index.ts

Add additional IP address header necessary for proper rate limiting.

Add additional IP address header

---

core/messages/en.json
core/messages/ja.json
core/tests/ui/e2e/login.spec.ts
core/tests/ui/e2e/register.spec.ts

- add test for login with invalid credentials
- add test for account registration with already used email
- fix typos in lang files
See Regression test run in CI

test(core): add account tests and fix typos

---

core/vibes/soul/components/cart/index.tsx
core/vibes/soul/components/counter/index.tsx
core/vibes/soul/components/dropdown/index.tsx
core/vibes/soul/components/input/index.tsx
core/vibes/soul/components/label/index.tsx
core/vibes/soul/components/modal/index.tsx

Add soul components necessary for Cart page.

chore(core): add soul cart page components

---

core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts
core/app/[locale]/(default)/cart/_actions/remove-item.ts
core/app/[locale]/(default)/cart/_actions/update-quantity.ts
core/app/[locale]/(default)/cart/_components/cart.tsx
core/app/[locale]/(default)/cart/page.tsx
core/messages/en.json
core/vibes/soul/components/cart/index.tsx
core/vibes/soul/components/counter/index.tsx

- Use soul Cart component in Cart page
- Skip shipping consignment for now (and extra summary fields related to this, like `tax`, `grandTotal`, etc). Only show `subtotal` and rely on redirected checkout to finish checkout.
- Update soul Cart component to be functional and fit our needs. Not final version of component. Skeleton, etc, will change.
Locally.

refactor(core): cart

---

core/app/[locale]/(default)/(faceted)/brand/[slug]/_components/product-list.tsx
core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/_components/product-list.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/search/_components/product-list.tsx
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/data-transformers/facets-transformer.ts
core/vibes/soul/components/chip/index.tsx
core/vibes/soul/components/compare-drawer/product-chip.tsx
core/vibes/soul/components/compare-products/index.tsx
core/vibes/soul/components/dropdown/index.tsx
core/vibes/soul/components/filter-panel/index.tsx
core/vibes/soul/components/pagination/index.tsx
core/vibes/soul/components/products-header/index.tsx

+ Use soul components in PLP.
+ Category page has no subcategory links.
+ In search, when term has no results, form is still not styled to soul.
Locally.

refactor(core): plp

---

core/app/[locale]/(default)/product/[slug]/_actions/add-to-cart.ts
core/app/[locale]/(default)/product/[slug]/_components/related-products.tsx
core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx
core/app/[locale]/(default)/product/[slug]/page.tsx
core/components/featured-products-carousel/index.tsx
core/messages/en.json
core/vibes/soul/components/cart/index.tsx
core/vibes/soul/components/counter/index.tsx
core/vibes/soul/components/product-detail/index.tsx
core/vibes/soul/components/product-detail/product-gallery.tsx

+ Adds PDP page with soul components
+ Some of the components are used temporarily with static info, will change
+ No product options, adding to cart only works with simple products
+ No alerts
Locally.

refactor(core): pdp for products without options

---

core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts
core/tests/fixtures/utils/account/create.ts
core/tests/ui/e2e/register.spec.ts

Fixes the register customer test to use the created account info.
See CI.

fix(core): update register customer test

---

docs/index.md

Update docs based on things that have shipped.

Update docs to reflect current state of releases

---

.changeset/tender-games-warn.md
packages/create-catalyst/src/commands/create.ts

> [!IMPORTANT]
> This PR stacks on #1435
Ensure `git` is installed on the machine running the CLI
Locally

refactor(cli)!: ensure git is installed on the machine running the CLI

---

docs/caching.md

Adds documentation around Catalyst caching strategies and methods we use across the repo.
N/A

feat: add documentation on caching

---

core/components/product-card/add-to-cart/form/index.tsx

chore: remove semicolon

---

docs/caching.md

Improve Caching docs with mention of ISR strategy.
N/A

Add mention of ISR strategy to caching docs

---

.changeset/little-plants-think.md
core/app/[locale]/(default)/cart/_components/item-quantity/index.tsx
core/tests/ui/e2e/cart.spec.ts

Copy of #1466 + changeset
Tested on the deployed branch preview URL.

fix(core): set the product quantity back to it's original value when there's an error updating it

---

.changeset/soft-years-guess.md
packages/create-catalyst/src/utils/https.ts

Update scopes requested by CLI
- Remove cart (no longer needed)
- Add both storefront API token scopes to ease transition to customer access tokens
Tested locally

Update CLI scopes

---

.changeset/dirty-starfishes-guess.md
packages/create-catalyst/src/utils/telemetry/telemetry.ts

CLI was hanging waiting for the promise to resolve.
https://github.com/user-attachments/assets/65fbf29b-6140-4956-bfa3-bc188846a14b
https://github.com/user-attachments/assets/48128ec7-8ee8-4bac-a672-efd3f6aaa635

fix(cli): CLI freezes before continuing

---

.changeset/fuzzy-colts-drop.md
core/package.json
pnpm-lock.yaml

Fixes https://github.com/amannn/next-intl/issues/1438
Locally

chore(core): bump next-intl to fix issue of query params in urls

---

packages/create-catalyst/src/utils/user-agent.ts

Remove 'unknown environment' case since it's not valuable
Locally

Improve CLI UA

---

core/components/ui/slideshow/slideshow.tsx

Set image priority on carousel; only prioritize first image
Resolves lighthouse issue on preview build

Set image priority

---

SECURITY.md

chore: APPSEC-705 update SECURITY.md

---

.changeset/cold-timers-burn.md
core/app/[locale]/(default)/account/(tabs)/_components/tab-heading.tsx
core/app/[locale]/(default)/account/(tabs)/_components/tab-navigation.tsx
core/app/[locale]/(default)/account/(tabs)/layout.tsx

This PR fixes styles for active account tab
locally
**before:**
https://github.com/user-attachments/assets/47e6715b-9b85-412a-a05b-ca4822739b6c
**after:**
https://github.com/user-attachments/assets/5b3f1f71-dc08-4a40-8108-ed8a12f64daf

fix(core): fix styles for active account tab

---

core/.env.example
core/app/[locale]/(default)/[...rest]/page.tsx
core/app/[locale]/layout.tsx
core/app/api/makeswift/[...makeswift]/route.ts
core/app/api/makeswift/draft-mode/route.ts
core/app/api/product-card-carousel/[type]/route.ts
core/components/ui/accordions/accordion.makeswift.tsx
core/components/ui/carousel/carousel.makeswift.tsx
core/components/ui/slideshow/slideshow.makeswift.tsx
core/components/ui/tabs/tabs.makeswift.tsx
core/components/ui/tabs/tabs.tsx
core/lib/makeswift/client.ts
core/lib/makeswift/components.ts
core/lib/makeswift/provider.tsx
core/lib/makeswift/runtime.ts
core/middleware.ts
core/middlewares/with-makeswift.ts
core/next.config.js
core/package.json
pnpm-lock.yaml

- The first commit is a cherry-picked commit from the `integrations/makeswift` branch.
- The second commit upgrades the `@makeswift/runtime` to a feature branch that has embedded component support.

Add Makeswift integration to vibes/soul-with-makeswift

---

core/components/featured-product-list/index.tsx
core/vibes/soul/sections/featured-products-list/index.tsx

Udpated FeaturedProductsList from Vibes to match design and added missing CTA button link.
Go to home page and scroll down to Our Plants section.

chore: update FeaturedProductsList from Vibes and pass CTA

---

core/vibes/soul/sections/featured-products-carousel/index.tsx

Update FeaturedProductsCarousel component from vibes to get latest styles
Go to home page and scroll down to `Newest products` section.
Uploading CleanShot 2024-11-06 at 11.51.50.mp4…

Update FeaturedProductsCarousel component

---

core/app/[locale]/(default)/cart/loading.tsx
core/app/[locale]/(default)/cart/page.tsx
core/vibes/soul/sections/cart/index.tsx

- Use skeleton in Cart
- Use empty state in Cart
Locally.

feat: add skeleton to cart page, use empty component

---

core/app/[locale]/(default)/(faceted)/_actions/redirect-to-compare.ts
core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page-data.ts
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts
core/app/[locale]/(default)/(faceted)/search/page-data.ts
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/package.json
core/vibes/soul/primitives/drawer/index.tsx
core/vibes/soul/primitives/products-list/compare-drawer.tsx
core/vibes/soul/primitives/products-list/index.tsx
core/vibes/soul/sections/products-list-section/index.tsx
pnpm-lock.yaml

- Fetches product details when a product is selected for compare. Passes unresolved Promise to component.
Locally.

fix: selecting products for compare in PLP

---

.github/CODEOWNERS

chore: add Makeswift team to CODEOWNERS

---

core/app/[locale]/(default)/[...rest]/page.tsx
core/app/[locale]/layout.tsx
core/components/footer/footer.tsx
core/i18n/routing.ts
core/lib/makeswift/client.ts
core/lib/makeswift/components.ts
core/lib/makeswift/provider.tsx
core/makeswift/components/footer/client.tsx
core/makeswift/components/footer/index.tsx
core/makeswift/components/footer/register.tsx
core/vibes/soul/sections/footer/index.tsx

https://github.com/user-attachments/assets/c7fa76a7-0d66-41cb-b808-1e8538a27066

feat: editable footer

---

core/lib/makeswift/components.ts
core/lib/makeswift/components/product-card/product-card.makeswift.tsx
core/vibes/soul/primitives/accordions/accordions.makeswift.tsx
core/vibes/soul/primitives/button-link/button-link.makeswift.tsx
core/vibes/soul/primitives/card-carousel/card-carousel.makeswift.tsx
core/vibes/soul/primitives/card-carousel/index.tsx
core/vibes/soul/primitives/card/card.makeswift.tsx
core/vibes/soul/primitives/card/index.tsx
core/vibes/soul/primitives/carousel/carousel.makeswift.tsx
core/vibes/soul/primitives/inline-email-form/inline-email-form.makeswift.tsx
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/products-carousel/products-carousel.makeswift.tsx
core/vibes/soul/primitives/products-list/products-list.makeswift.tsx
core/vibes/soul/sections/featured-image/featured-image.makeswift.tsx
core/vibes/soul/sections/slideshow/index.tsx
core/vibes/soul/sections/slideshow/slideshow.makeswift.tsx
pnpm-lock.yaml

Binding for `button-link` component.
https://github.com/user-attachments/assets/d81956cd-0ee8-4068-aef8-5c8cac3c405f
Binding for `accordions` component.
https://github.com/user-attachments/assets/d9f51968-9ff5-4161-b7f5-17910d6c0203
Binding for `card` component.
https://github.com/user-attachments/assets/280133aa-c3e9-44a3-800d-226b76dc2952
Binding for `carousel` component.
https://github.com/user-attachments/assets/cd99893b-fe9e-4074-9876-5fb9560a94b7
Binding for `card-carousel` component.
https://github.com/user-attachments/assets/e215bfa0-7ecb-4a55-b7e5-69d713bbc529
Binding for `product-carousel` component.
https://github.com/user-attachments/assets/fd060c08-1435-4aca-9e03-56c80f69b1f4
Binding for `slideshow` component.
https://github.com/user-attachments/assets/e91c9d3b-92cc-4f6c-a62d- …

feat: soul component bindings

---

core/app/[locale]/(default)/(auth)/login/_components/login-form.tsx
core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/[...rest]/page.tsx
core/app/[locale]/(default)/account/(tabs)/settings/_components/update-settings-form.tsx
core/app/[locale]/(default)/product/[slug]/_components/product-form/fields/shared/error-message.tsx
core/app/[locale]/(default)/product/[slug]/_components/product-form/index.tsx
core/app/[locale]/(default)/product/[slug]/page.tsx
core/app/[locale]/maintenance/page.tsx
core/components/featured-product-list/index.tsx
core/components/header/index.tsx
core/components/header/quick-search.tsx
core/components/ui/accordions/accordions.tsx
core/components/ui/button/button.tsx
core/components/ui/compare-drawer/compare-drawer.tsx
core/components/ui/form/checkbox/checkbox.tsx
core/components/ui/form/counter/counter.tsx
core/components/ui/form/input/input.tsx
core/components/ui/form/pick-list/pick-list.tsx
core/components/ui/form/radio-group/radio-group.tsx
core/components/ui/form/rectangle-list/rectangle-list.tsx
core/components/ui/form/select/select.tsx
core/components/ui/form/swatch/swatch.tsx
core/components/ui/form/text-area/text-area.tsx

Move away from hardcoded accordion to using the API data; insert HTML where relevant.
Next step - embedded component.

Wire up product description, custom fields, warranty

---

core/vibes/soul/sections/products-list-section/filters-panel.tsx
core/vibes/soul/sections/products-list-section/index.tsx
core/vibes/soul/sections/products-list-section/mobile-filters.tsx

feat: hide plp filters if empty

---

core/vibes/soul/sections/products-list-section/filters-panel.tsx
core/vibes/soul/sections/products-list-section/index.tsx

Add reset filter label to PLP

---

core/components/header/index.tsx
core/lib/makeswift/components.ts
core/makeswift/components/header/client.tsx
core/makeswift/components/header/index.tsx
core/makeswift/components/header/register.tsx
core/messages/en.json
core/vibes/soul/primitives/navigation/index.tsx

https://github.com/user-attachments/assets/faf441c2-5522-4b59-a625-3867a4833619

feat: editable header

---

core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/sections/header-section/index.tsx

- Navigation now has shadow when unpinned
- Navigation search now closes on scroll

Navigation scroll enhancements

---

core/app/[locale]/(default)/product/[slug]/_actions/add-to-cart.ts
core/app/[locale]/(default)/product/[slug]/page-data.ts
core/app/[locale]/(default)/product/[slug]/page.tsx

feat: add PDP form

---

core/tailwind.config.js

Various VIBES primitives weren't showing proper animations due to missing classes in the Tailwind config.
https://github.com/user-attachments/assets/1b176d89-3076-4f81-89cb-827189354e09
https://github.com/user-attachments/assets/1f163f06-0e97-4518-83fc-96e0a5a66f6a

chore: import latest VIBES Tailwind config

---

core/app/api/products/[entityId]/route.ts
core/app/api/products/group/[group]/route.ts
core/app/api/products/ids/route.ts
core/client/queries/get-products.ts
core/lib/makeswift/components.ts
core/makeswift/components/accordions/accordions.makeswift.tsx
core/makeswift/components/button-link/button-link.makeswift.tsx
core/makeswift/components/card-carousel/card-carousel.makeswift.tsx
core/makeswift/components/card/card.makeswift.tsx
core/makeswift/components/carousel/carousel.makeswift.tsx
core/makeswift/components/featured-image/featured-image.makeswift.tsx
core/makeswift/components/featured-products-carousel/featured-products-carousel.makeswift.tsx
core/makeswift/components/inline-email-form/inline-email-form.makeswift.tsx
core/makeswift/components/product-card/product-card.makeswift.tsx
core/makeswift/components/products-carousel/products-carousel.makeswift.tsx
core/makeswift/components/products-list/products-list.makeswift.tsx
core/makeswift/components/slideshow/slideshow.makeswift.tsx
core/makeswift/components/sticky-sidebar-layout/sticky-sidebar-layout.makeswift.tsx
core/vibes/soul/primitives/products-carousel/products-carousel.makeswift.tsx
core/vibes/soul/primitives/products-list/products-list.makeswift.tsx

ProductCarousel
https://github.com/user-attachments/assets/622bc577-3258-4522-817b-0e67ec6f232b
ProductList
https://github.com/user-attachments/assets/35658a17-902f-42ae-8149-8a0c86e0059f

ProductList and ProductCarousel can now query data.

---

core/app/[locale]/(default)/product/[slug]/page.tsx
core/lib/makeswift/components.ts
core/makeswift/components/footer/client.tsx
core/makeswift/components/footer/index.tsx
core/makeswift/components/header/index.tsx
core/makeswift/components/product-description/client.tsx
core/makeswift/components/product-description/index.tsx
core/makeswift/components/product-description/register.tsx
core/makeswift/lib/merge-sections.ts
core/package.json
pnpm-lock.yaml

https://github.com/user-attachments/assets/25a98f70-2e69-4d8b-8617-1fb3f618871f

feat: editable PDP

---

core/package.json
pnpm-lock.yaml

https://github.com/user-attachments/assets/e8fafa12-b990-4482-a8f6-0501aee10b27
https://github.com/user-attachments/assets/08851b92-34ca-4c82-9f74-6a066e94d05d

fix: update `@makeswift/runtime`, fixes stale snapshot issue

---

core/app/[locale]/(default)/product/[slug]/loading.tsx

Adds interim skeleton for PDP.
https://github.com/user-attachments/assets/08f9f987-77a5-4519-8a37-188149e55752
Locally.

feat: add loading file for PDP

---

core/makeswift/components/sticky-sidebar-layout/sticky-sidebar-layout.makeswift.tsx
core/vibes/soul/primitives/accordions/index.tsx
core/vibes/soul/sections/product-description/index.tsx
core/vibes/soul/sections/product-detail/index.tsx
core/vibes/soul/sections/sticky-sidebar-layout/index.tsx

- Added breadcrumbs to PDP
- Added `containerSize` to sticky layout
- Fixed product description overflow issues

PDP Updates

---

core/app/[locale]/(default)/product/[slug]/_components/reviews-data.ts
core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx
core/app/[locale]/(default)/product/[slug]/page.tsx
core/vibes/soul/primitives/card-carousel/index.tsx
core/vibes/soul/primitives/cursor-pagination/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/primitives/products-carousel/index.tsx
core/vibes/soul/sections/reviews/index.tsx

- Add empty state and skeletons for all 3
- Automatically fallback to empty state when arrays are empty
- Wire up pagination and total count for Reviews
- Add `scroll` to `CursorPagination` to disable scrolling for `Reviews`

Update Reviews, CardCarousel, ProductsCarousel

---

core/vibes/soul/primitives/carousel/index.tsx

Hide carousel scrollbar and arrows when full

---

core/makeswift/components/accordions/accordions.makeswift.tsx

https://github.com/user-attachments/assets/299c7508-d25b-4a3a-be2b-481036323cd6

fix: accordions open and close as intended

---

core/app/[locale]/(default)/product/[slug]/page.tsx

+ Append default image if found to Gallery, show result first.
+ Use first image from image in description.
https://github.com/user-attachments/assets/883b6435-69e6-408e-86cf-174c4d1ebb44
Locally.

fix: show correct image on variants

---

core/app/[locale]/(default)/page.tsx

Make the homepage to render Makeswift page instead to make it visually editable.
Go to `/` on the localhost. And go to the homepage on the Makeswift builder.

feat: make homepage visually editable

---

core/app/[locale]/(default)/product/[slug]/page-data.ts
core/app/[locale]/(default)/product/[slug]/page.tsx
core/lib/makeswift/components.ts
core/makeswift/components/product-detail/client.tsx
core/makeswift/components/product-detail/index.tsx
core/makeswift/components/product-detail/register.tsx
core/vibes/soul/sections/product-detail/index.tsx

https://github.com/user-attachments/assets/2330174c-58eb-47c6-af98-d87ea25f5aa9
Notes:
- I haven't removed the description from the product description accordion, since I'm not sure what to show on the left side of the product description by default.
- I set the characterLimit of the plainTextDescription to 1200. This is adjustable.

feat: make product detail visually editable

---

core/app/[locale]/(default)/(faceted)/search/page.tsx
core/components/empty-search/index.tsx
core/lib/makeswift/components.ts
core/makeswift/components/not-found/client.tsx
core/makeswift/components/not-found/index.tsx
core/makeswift/components/not-found/register.tsx
core/messages/en.json

https://github.com/user-attachments/assets/15ade929-652d-404d-be41-a2ea82edc293

feat: editable search placeholder/empty search states

---

core/package.json
pnpm-lock.yaml

See https://makeswifthq.slack.com/archives/C07DAL1D8JK/p1731379404815689

fix: resolve attempted import errors coming from Makeswift runtime

---

core/package.json
pnpm-lock.yaml

Bump next-intl to pull in @deini's fix: 
https://github.com/amannn/next-intl/pull/1537
CI + manual on preview deployment

Bump next-intl to fix trailing slash issues

---

.changeset/old-tables-bow.md
core/app/[locale]/(default)/account/(tabs)/orders/_components/order-details.tsx
core/app/[locale]/(default)/account/(tabs)/orders/_components/orders-list.tsx
core/app/[locale]/(default)/account/(tabs)/orders/_components/product-snippet.tsx
core/app/[locale]/(default)/account/(tabs)/orders/page-data.ts

Thanks for GQL API updates this PR adds ability to link order items to their PDP.
locally
https://github.com/user-attachments/assets/41e3e04b-2d00-4372-b6ec-1d27430ecf99

feat(core): add path to PDP for Orders

---

core/app/[locale]/(default)/(auth)/login/_components/login-form.tsx
core/app/[locale]/(default)/account/(tabs)/settings/_components/update-settings-form.tsx
core/app/[locale]/(default)/product/[slug]/_components/product-form/fields/shared/error-message.tsx
core/app/[locale]/(default)/product/[slug]/_components/product-form/index.tsx
core/app/[locale]/layout.tsx
core/app/[locale]/maintenance/page.tsx
core/app/globals.css
core/components/link/index.tsx
core/components/ui/accordions/accordions.tsx
core/components/ui/button/button.tsx
core/components/ui/compare-drawer/compare-drawer.tsx
core/components/ui/form/checkbox/checkbox.tsx
core/components/ui/form/counter/counter.tsx
core/components/ui/form/input/input.tsx
core/components/ui/form/pick-list/pick-list.tsx
core/components/ui/form/radio-group/radio-group.tsx
core/components/ui/form/rectangle-list/rectangle-list.tsx
core/components/ui/form/select/select.tsx
core/components/ui/form/swatch/swatch.tsx
core/components/ui/form/text-area/text-area.tsx
core/tailwind.config.js

- Add tailwind setup per VIBES/Soul docs
- Use electric theme
- Update layout to use new fonts and remove container classes
- Remove styles from Link component
- Fix eslint conflicts from new tailwind config
Locally, pages use new tailwind config.

chore(core): update tailwind config and layout to use Soul config

---

core/app/[locale]/layout.tsx

chore(core): add roboto mono font

---

core/tsconfig.json

In preparation for vibes components, add this rule to match imports in those components.
Locally.

chore(core): add @/vibes/* path in tsconfig

---

.changeset/wicked-papayas-smoke.md
core/i18n/request.ts
core/package.json
pnpm-lock.yaml

feat(core): provide a fallback locale for translations

---

core/app/[locale]/(default)/page.tsx
core/components/featured-products-carousel/fragment.ts
core/components/featured-products-carousel/index.tsx
core/messages/en.json
core/vibes/soul/primitives/animated-link/index.tsx
core/vibes/soul/primitives/carousel/index.tsx
core/vibes/soul/primitives/products-carousel/index.tsx
core/vibes/soul/sections/featured-products-carousel/index.tsx

- Add FeaturedProductsCarousel component that uses the VIBES FeaturedProductsCarousel component.
- Define a new fragment for FeaturedProductsCarousel.
- Import VIBES component needed to render VIBES FeaturedProductsCarousel.
- Use new component in Homepage to render Newest Products.
- Add messages in dictionary.
Locally carousel renders.

feat(core): add FeaturedProductsCarousel and use in Homepage

---

core/app/[locale]/(default)/page.tsx
core/messages/en.json

+ Builds off #1675, review last commit.
+ Adds Best selling products
+ Adds messages to dictionary
Locally best selling products carousel renders.

feat(core): add best selling products to Hompage

---

.changeset/orange-cheetahs-explode.md
core/components/ui/product-card/compare.tsx
core/messages/en.json

Lighthouse was reporting 93 on Accessibility on PLP.
Just added an aria-label to compare to have 100%
Open a PLP, run Lighthouse, and check the accessibility score.

FIX missing aria labels on compare

---

core/components/ui/carousel/carousel.tsx
core/components/ui/footer/footer.tsx
core/components/ui/form/counter/counter.tsx
core/components/ui/gallery/gallery.tsx
core/components/ui/header/input.tsx
core/components/ui/header/mobile-nav.tsx
core/components/ui/header/search.tsx
core/components/ui/pagination/pagination.tsx
core/components/ui/product-card/compare.tsx

Fix lint issues introduced in https://github.com/bigcommerce/catalyst/pull/1690
CI

Fix lint issues

---

.changeset/slow-houses-smell.md
packages/create-catalyst/src/commands/create.ts

fix(cli): fix command check for Windows in create

---

core/app/[locale]/(default)/[...rest]/page.tsx
core/app/[locale]/layout.tsx
core/components/ui/carousel/carousel.makeswift.client.tsx
core/components/ui/carousel/carousel.makeswift.tsx
core/components/ui/slideshow/slideshow.tsx

Makeswift [integration setup](https://docs.makeswift.com/developer/app-router/installation#geting-started) + Next 15 compatibility fixes.

fix: move `<MakeswiftProvider>` to the root layout + Next 15 compat

---

core/app/[locale]/(default)/layout.tsx
core/app/[locale]/not-found.tsx
core/components/header/index.tsx
core/components/ui/footer/footer.tsx
core/data-transformers/logo-transformer.ts
core/messages/en.json
core/package.json
core/vibes/soul/primitives/banner/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/primitives/navigation/schema.ts
core/vibes/soul/sections/header-section/index.tsx
pnpm-lock.yaml

+ Use `Header` section component from VIBES.
+ Install react-headroom
+ Pass in streamable props to component.
Locally.

feat: add header

---

.changeset/afraid-eels-complain.md
core/app/[locale]/(default)/(auth)/change-password/_actions/change-password.ts
core/app/[locale]/(default)/(auth)/change-password/_components/change-password-form.tsx
core/app/[locale]/(default)/(auth)/login/_components/login-form.tsx
core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts
core/app/[locale]/(default)/(auth)/login/forgot-password/_components/reset-password-form/index.tsx
core/app/[locale]/(default)/(auth)/register/_components/register-customer-form.tsx
core/app/[locale]/(default)/account/(tabs)/_components/account-status-provider.tsx
core/app/[locale]/(default)/account/(tabs)/_components/submit-messages-list.tsx
core/app/[locale]/(default)/account/(tabs)/addresses/_actions/delete-address.ts
core/app/[locale]/(default)/account/(tabs)/addresses/_components/address-book.tsx
core/app/[locale]/(default)/account/(tabs)/addresses/add/_actions/add-address.ts
core/app/[locale]/(default)/account/(tabs)/addresses/add/_components/add-address-form.tsx
core/app/[locale]/(default)/account/(tabs)/addresses/edit/[slug]/_actions/update-address.ts
core/app/[locale]/(default)/account/(tabs)/addresses/edit/[slug]/_components/edit-address-form.tsx
core/app/[locale]/(default)/account/(tabs)/settings/_actions/update-customer.ts
core/app/[locale]/(default)/account/(tabs)/settings/_components/update-settings-form.tsx
core/app/[locale]/(default)/account/(tabs)/settings/change-password/_actions/change-password.ts
core/app/[locale]/(default)/account/(tabs)/settings/change-password/_components/change-password-form.tsx

This PR utilizes [PR](https://github.com/bigcommerce/catalyst/pull/1647) for improving create-account submit error message and extends it on other account forms. 
locally

Update account forms submit errors message

---

core/app/[locale]/(default)/page.tsx
core/messages/en.json

Removes best selling products from home page.
Locally best selling does not show.

feat: remove bestselling products from Home

---

core/app/[locale]/(default)/page.tsx
core/messages/en.json
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/products-carousel/index.tsx
core/vibes/soul/sections/featured-products-carousel/index.tsx

- Adds empty state to `FeaturedProductsCarousel`
https://github.com/user-attachments/assets/ef2084ab-f0ae-44ee-816a-e7685f215011

feat: add empty state to FeaturedProductsCarousel

---

core/app/[locale]/(default)/account/order/[slug]/_components/order-details.tsx
core/app/[locale]/(default)/account/orders/_components/orders-list.tsx

Fixes ESLint warnings.
Ran `pnpm lint` locally, CI should pass now.

chore: run pnpm lint -- --fix

---

core/app/[locale]/(default)/account/addresses/add/_actions/add-address.ts
core/app/[locale]/(default)/account/addresses/add/_components/add-address-form.tsx
core/app/[locale]/(default)/account/addresses/edit/[slug]/_actions/update-address.ts
core/app/[locale]/(default)/account/addresses/edit/[slug]/_components/edit-address-form.tsx
core/tests/ui/e2e/addresses.spec.ts

Moves address related action messages over to using the toast.
> [!TIP]
> Hide whitespace might help the review.

feat(core): update address actions to use toasts

---

.changeset/grumpy-roses-attack.md
core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts
core/app/[locale]/(default)/(auth)/register/_components/register-customer-form.tsx
core/messages/en.json

Converts the register customer page over to using toasts.
https://github.com/user-attachments/assets/f95dd80b-6db3-4aff-8245-438e466c9468

feat(core): convert register over to toasts

---

core/app/[locale]/(default)/logout/route.ts

Adds a logout route handler to be able to logout via a url.
https://github.com/user-attachments/assets/8fcdff86-5e53-4c3e-bdb2-f73fd31e39c8

feat: add logout route handler

---

core/vibes/soul/primitives/animated-link/index.tsx
core/vibes/soul/primitives/breadcrumbs/index.tsx

- Updates breadcrumb with new skeleton
- Adds `AnimatedLink` to breadcrumbs
Locally

feat: update Breadcrumbs to use AnimatedLink and new skeleton design

---

core/app/[locale]/(default)/(auth)/change-password/page.tsx
core/app/[locale]/(default)/(auth)/login/forgot-password/page.tsx
core/app/[locale]/(default)/(auth)/register/page.tsx
core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/app/[locale]/(default)/account/addresses/add/page.tsx
core/app/[locale]/(default)/account/addresses/edit/[slug]/page.tsx
core/app/[locale]/(default)/account/addresses/page.tsx
core/app/[locale]/(default)/account/order/[slug]/page.tsx
core/app/[locale]/(default)/account/orders/page.tsx
core/app/[locale]/(default)/account/settings/change-password/page.tsx
core/app/[locale]/(default)/account/settings/page.tsx
core/app/[locale]/(default)/blog/[blogId]/page.tsx
core/app/[locale]/(default)/blog/page.tsx
core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx
core/app/[locale]/(default)/cart/page.tsx
core/app/[locale]/(default)/compare/page.tsx
core/app/[locale]/(default)/page.tsx
core/app/[locale]/(default)/product/[slug]/page.tsx
core/app/[locale]/(default)/webpages/contact/[id]/page.tsx
core/app/[locale]/(default)/webpages/normal/[id]/page.tsx
core/app/[locale]/maintenance/page.tsx
core/app/[locale]/not-found.tsx

Removes edge runtime on all pages.
👀  Preview

chore: remove edge runtime from pages

---

core/vibes/soul/form/checkbox/index.tsx
core/vibes/soul/primitives/price-label/index.tsx
core/vibes/soul/primitives/product-card/compare.tsx
core/vibes/soul/primitives/product-card/index.tsx

Updated `ProductCard`, `PriceLabel` and `Checkbox` to use CSS variables for future theming support.

feat: add CSS variables to ProductCard

---

core/vibes/soul/primitives/navigation/index.tsx

Brings the latest changes of the navigation primitive from VIBES.
Minimal import changes that are verified by CI.

chore: sync navigation primitive with VIBES

---

core/vibes/soul/primitives/banner/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/primitives/products-list/index.tsx
core/vibes/soul/sections/header-section/index.tsx
core/vibes/soul/sections/sticky-sidebar-layout/index.tsx

Add CSS variables and other configurable props for:
- `Navigation`
- `ProductList`
- `StickySidebarLayout`
https://github.com/user-attachments/assets/eee451c8-b4ac-49ad-9c8a-568c132f0e4b

Add CSS variables / props for `Navigation`, `ProductList`, `StickySidebarLayout`

---

core/app/[locale]/(default)/blog/page-data.ts
core/app/[locale]/(default)/blog/page.tsx
core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx

- Update `/blog/tag/[tagId]` page to use `FeaturedBlogPostList` component.
- Minor refactoring to use shared logic and avoid code duplication
**Next iteration:**
- Update `FeaturedBlogPostList` component to use pagination
https://github.com/user-attachments/assets/9d2957b8-68aa-43c2-8aed-5457dcc61190

feat: use FeaturedBlogPostList in /blog/tag/ route

---

core/app/[locale]/(default)/page.tsx

Replace the homepage with `MakeswiftPage` to make it visually editable.
Running `next start` locally
https://github.com/user-attachments/assets/095fc76b-bfc8-4247-85af-297a224f9959

feat: replace homepage with MakeswiftPage

---

core/lib/makeswift/components.ts
core/lib/makeswift/components/accordions/accordions.makeswift.tsx
core/lib/makeswift/components/button-link/button-link.makeswift.tsx
core/lib/makeswift/components/card-carousel/card-carousel.makeswift.tsx
core/lib/makeswift/components/card/card.makeswift.tsx
core/lib/makeswift/components/carousel/carousel.makeswift.tsx
core/lib/makeswift/components/slideshow/slideshow.makeswift.tsx
core/vibes/soul/primitives/card-carousel/index.tsx
core/vibes/soul/primitives/card/index.tsx

Add presentational Makeswift components:
https://github.com/user-attachments/assets/66c4765a-566b-42a2-bf0f-eeb3966b1924
https://github.com/user-attachments/assets/f6bd529d-b1ac-4427-93b3-bda64273b1c0
https://github.com/user-attachments/assets/335073f3-31e4-4093-a95f-9f084f579bd1
https://github.com/user-attachments/assets/95e2321e-d3bf-4fcd-a323-3dbe1b30351a
https://github.com/user-attachments/assets/df00dc70-a93b-4091-940e-de55b1efbf53
https://github.com/user-attachments/assets/4d48df71-2055-44bf-a9d8-82ce50dd7593

Add initial Makeswift components

---

core/lib/makeswift/components.ts
core/lib/makeswift/components/section/section.makeswift.ts
core/lib/makeswift/components/sticky-sidebar/sticky-sidebar.makeswift.tsx
core/vibes/soul/sections/section-layout/index.tsx
core/vibes/soul/sections/sticky-sidebar-layout/index.tsx

Add two layout components
https://github.com/user-attachments/assets/5c8efca6-a2d5-40a0-8705-c3f8aedf2f6f

feat: add Makeswift components section and sticky-sidebar

---

core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/create-filters-search-params-cache.ts
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/messages/en.json

Uses the Soul product list section component for the `/search` page.
https://github.com/user-attachments/assets/cf36d5df-7128-41be-a49b-ac7013669852

feat: Soul ProductsListSection for search results

---

core/components/header/index.tsx
core/lib/makeswift/components.ts
core/lib/makeswift/components/site-header/site-header.client.tsx
core/lib/makeswift/components/site-header/site-header.makeswift.tsx
core/lib/makeswift/components/site-header/site-header.tsx

Add editable site header
https://github.com/user-attachments/assets/e289c1fc-87a5-46bd-b9cf-9eaa20ff1b2e

feat: add Makeswift site header

---

core/components/footer/footer.tsx
core/lib/makeswift/components.ts
core/lib/makeswift/components/site-footer/site-footer.client.tsx
core/lib/makeswift/components/site-footer/site-footer.makeswift.tsx
core/lib/makeswift/components/site-footer/site-footer.tsx
core/lib/makeswift/utils/merge-sections.ts

Add editable Makeswift footer
https://github.com/user-attachments/assets/d9582e04-e1ba-4863-a877-0198cf11c8c0

feat: add Makeswift site footer

---

core/app/api/products/[entityId]/route.ts
core/app/api/products/group/[group]/route.ts
core/app/api/products/ids/route.ts
core/client/queries/get-products.ts
core/lib/makeswift/components.ts
core/lib/makeswift/components/product-card/product-card.makeswift.tsx
core/lib/makeswift/components/products-carousel/products-carousel.makeswift.tsx
core/lib/makeswift/components/products-list/products-list.makeswift.tsx
core/lib/makeswift/utils/search-products.ts
core/lib/makeswift/utils/use-bc-product-to-vibes-product/use-bc-product-to-vibes-product.ts
core/lib/makeswift/utils/use-products.ts

Add editable ProductList and ProductCarousel
ProductList
https://github.com/user-attachments/assets/417950aa-0eea-4691-8aab-ecfefc5e9e09
ProductCarousel
https://github.com/user-attachments/assets/ec11acd8-c8ee-43a1-9183-0b14010ac4b4

feat: add Makeswift ProductList and ProductCarousel

---

core/app/api/products/[entityId]/route.ts
core/app/api/products/group/[group]/route.ts
core/app/api/products/ids/route.ts
core/app/api/products/route.ts
core/client/queries/get-products.ts
core/client/queries/get-search-results.ts
core/lib/makeswift/components.ts
core/lib/makeswift/components/product-card/product-card.makeswift.tsx
core/lib/makeswift/components/products-carousel/products-carousel.makeswift.tsx
core/lib/makeswift/components/products-list/products-list.makeswift.tsx
core/lib/makeswift/utils/search-products.ts
core/lib/makeswift/utils/use-bc-product-to-vibes-product/fragment.ts
core/lib/makeswift/utils/use-bc-product-to-vibes-product/use-bc-product-to-vibes-product.ts
core/lib/makeswift/utils/use-products.ts
core/package.json
pnpm-lock.yaml

Add editable Product Card
https://github.com/user-attachments/assets/bd0d77e7-78b1-46af-ad15-e1d783af38f5

feat: add Makeswift ProductCard, ProductList and ProductCarousel

---

core/app/[locale]/not-found.tsx
core/vibes/soul/sections/not-found/index.tsx

Add the `NotFound` component from VIBES to the 404 page.
- I'll add the FeaturedProductsCarousel in my next PR

feat: Add NotFound section to 404 page

---

core/lib/makeswift/runtime.ts

Adds custom breakpoints to Makeswift integration.
Tested locally.

feat: add custom breakpoints

---

core/app/[locale]/not-found.tsx

Add the `FeaturedProductsCarousel` to the 404 page
- https://github.com/bigcommerce/catalyst/pull/1812

feat: add FeaturedProductsCarousel to 404 page

---

core/vibes/soul/form/input/index.tsx
core/vibes/soul/form/number-input/index.tsx

Fixes an issue with forms not working uncontrolled.
Locally, inputs work now.

fix: remove empty string in value

---

core/package.json
pnpm-lock.yaml

Revert to version that works until we can explore why upgrading is breaking the build.
Locally.

chore: revert nextjs

---

.gitignore
core/app/api/temp-cache-headers/route.ts
core/lib/kv/adapters/vercel-data-cache.ts
core/lib/kv/index.ts
core/lib/kv/types.ts
core/middlewares/with-routes.ts
core/package.json
pnpm-lock.yaml

VDC prototype

---

core/app/[locale]/(default)/account/addresses/page-data.ts
core/app/[locale]/(default)/account/addresses/page.tsx
core/data-transformers/form-field-transformer/index.ts
core/vibes/soul/form/select/index.tsx

Adds the list of countries to the address list page/form.
> [!NOTE]
> Rebased from `soul/account-addresses` #1870 
https://github.com/user-attachments/assets/4f952320-3dd3-4afd-832c-8fb10eda2512

feat(core): add country list to account addresses

---

core/app/[locale]/maintenance/page.tsx
core/vibes/soul/sections/maintenance/index.tsx
core/vibes/soul/sections/section-layout/index.tsx

Add **Down for Maintenance** page to Catalyst

Add down for maintenance page

---

core/app/[locale]/(default)/product/[slug]/page.tsx
core/messages/en.json
core/vibes/soul/form/button-radio-group/index.tsx
core/vibes/soul/form/card-radio-group/index.tsx
core/vibes/soul/form/checkbox-group/index.tsx
core/vibes/soul/form/radio-group/index.tsx
core/vibes/soul/form/swatch-radio-group/index.tsx
core/vibes/soul/form/toggle-group/index.tsx
core/vibes/soul/sections/product-detail/index.tsx
core/vibes/soul/sections/product-detail/product-detail-form.tsx

Fixes:
+ Issue with uncontrolled/controlled inputs
+ Issue with headings order
+ Issue with missing labels
Lighthouse no longer gives warnings for these issues.

fix: accessibility issues in PDP

---

core/vibes/soul/form/card-radio-group/index.tsx
core/vibes/soul/lib/streamable.tsx
core/vibes/soul/primitives/blog-post-card/index.tsx
core/vibes/soul/primitives/logo/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/products-carousel/index.tsx
core/vibes/soul/primitives/products-list/index.tsx
core/vibes/soul/sections/cart/index.tsx
core/vibes/soul/sections/order-details-section/index.tsx
core/vibes/soul/sections/order-list-section/order-list-line-item.tsx
core/vibes/soul/sections/product-detail/product-gallery.tsx
core/vibes/soul/sections/slideshow/index.tsx
core/vibes/soul/sections/subscribe/index.tsx

Brings in latest changes from VIBES, which mostly include image optimizations.
https://github.com/user-attachments/assets/2a3605b3-0a15-4680-aaa5-414ff1768884
https://github.com/user-attachments/assets/1dec9945-94dd-47c7-beef-400686f80c6c

chore: bring in latest changes from VIBES

---

core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/sections/footer/index.tsx

Fix spacing in the footer between logo and address.

fix: footer spacing

---

core/lib/makeswift/components/card-carousel/card-carousel.makeswift.tsx
core/lib/makeswift/components/carousel/carousel.makeswift.tsx
core/lib/makeswift/components/products-carousel/products-carousel.makeswift.tsx
core/lib/makeswift/components/section/section.makeswift.ts
core/lib/makeswift/components/site-theme/components/header/nav.ts
core/vibes/soul/primitives/card-carousel/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/sections/footer/index.tsx
core/vibes/soul/sections/sticky-sidebar-layout/index.tsx

- Added `hideOverflow` controls to carousels and section.
- Removed nav menu divider color control from site theme.
https://github.com/user-attachments/assets/bd387a27-d59f-4177-aed9-4b3a4a5746ec

Carousel overflow controls

---

core/package.json
pnpm-lock.yaml

Next 15.2.0-canary.8

---

.github/workflows/regression-tests.yml

In merging Soul we removed old UI tests because they would all be broken, but we also deleted the lighthouse tests. Putting them back in their own file.
CI

Bring back lighthouse check

---

core/package.json
pnpm-lock.yaml

https://github.com/vercel/next.js/releases
CI & preview

Bump next to v15.2.0-canary.14

---

.changeset/five-seals-chew.md
core/app/[locale]/(default)/(auth)/change-password/page.tsx
core/app/[locale]/(default)/(auth)/login/forgot-password/page.tsx
core/app/[locale]/(default)/(auth)/login/page.tsx
core/app/[locale]/(default)/(auth)/register/page.tsx
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/app/[locale]/(default)/account/addresses/page.tsx
core/app/[locale]/(default)/account/settings/page.tsx
core/app/[locale]/(default)/cart/page.tsx
core/app/[locale]/(default)/compare/page.tsx
core/app/[locale]/(default)/product/[slug]/page-data.ts
core/app/[locale]/maintenance/page.tsx

We either type all of them, or none of them.

chore(core): add result type to generateMetadata

---

core/package.json
pnpm-lock.yaml

chore(deps): Bump Next.js to version 15.2.0-canary.27

---

.changeset/quiet-impalas-hear.md
core/app/[locale]/(default)/(auth)/change-password/page.tsx
core/app/[locale]/(default)/webpages/[id]/contact/page.tsx
core/app/[locale]/(default)/webpages/[id]/normal/page.tsx

Same as #1927, but for webpages pages.
Requests is being properly memoized.

fix(core): dedupe requests in webpages

---

core/package.json
pnpm-lock.yaml

Bump next canary to .41
CI/CD and preview

Bump canary to .41

---

core/package.json
pnpm-lock.yaml

Bump canary to .52

---

.changeset/slow-dolls-allow.md
core/app/[locale]/(default)/cart/_actions/apply-coupon-code.ts
core/app/[locale]/(default)/cart/_actions/remove-coupon-code.ts
core/app/[locale]/(default)/cart/_actions/update-coupon-code.ts
core/app/[locale]/(default)/cart/page-data.ts
core/app/[locale]/(default)/cart/page.tsx
core/messages/en.json
core/vibes/soul/form/input/index.tsx
core/vibes/soul/form/label/index.tsx
core/vibes/soul/primitives/chip/index.tsx
core/vibes/soul/sections/cart/client.tsx
core/vibes/soul/sections/cart/coupon-code-form/coupon-chip.tsx
core/vibes/soul/sections/cart/coupon-code-form/index.tsx
core/vibes/soul/sections/cart/index.tsx
core/vibes/soul/sections/cart/schema.ts

Adds coupon code form to Cart.
Pending approval of https://github.com/makeswift/vibes/pull/505
https://github.com/user-attachments/assets/5667127c-9dd0-4b79-b6f5-7355d1c8d88f
Locally.

feat(core): add coupon code to Cart

---

.changeset/good-actors-return.md
core/app/[locale]/(default)/(auth)/login/page.tsx
core/app/[locale]/(default)/logout/route.ts
core/app/[locale]/layout.tsx
core/app/notifications.tsx
core/auth/index.ts
core/components/force-refresh/index.tsx
core/lib/client-cookies.ts
core/lib/force-refresh.ts
core/lib/server-toast.ts
core/messages/en.json

- Add support for Persistent Carts (restoring or merging carts during login)
- Ensure `/logout` link refreshes the layout with a force-refresh cookie component
https://github.com/user-attachments/assets/fc85a346-0d8e-431f-8dad-61186d9daf8d

Add persistent cart support

---

core/app/[locale]/(default)/cart/page.tsx
core/messages/en.json
core/vibes/soul/sections/cart/coupon-code-form/index.tsx

Forgot to include these changes in #1979 
Locally.

fix: change label from Grand Total to Total in Cart

---

core/data-transformers/order-details-transformer.ts
core/vibes/soul/primitives/badge/index.tsx
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/skeleton/index.tsx
core/vibes/soul/sections/order-details-section/index.tsx

Sync `Badge`, `Skeleton`, `ProductCard`, and `OrderDetailsSection` components with VIBES.

Sync badge, skeleton, product-card, and order-details with VIBES

---

core/app/[locale]/(default)/product/[slug]/page.tsx
core/package.json
core/tailwind.config.js
core/vibes/soul/sections/product-detail/index.tsx
pnpm-lock.yaml

- Installs `@tailwindcss/typography` as dev dependency
- Adds default styles for `prose` Tailwind class
https://github.com/user-attachments/assets/c343bf58-a425-43b5-97f3-c06847950c7f

feat: add default Tailwind typography styles

---

.changeset/translations-patch-1685d885.md
core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts
core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts
core/app/[locale]/(default)/product/[slug]/page.tsx
core/messages/es-419.json
core/messages/es-AR.json
core/messages/es-CL.json
core/messages/es-CO.json
core/messages/es-LA.json
core/messages/es-MX.json
core/messages/es-PE.json
core/messages/pt-BR.json
core/messages/pt.json
core/package.json
core/tailwind.config.js
core/vibes/soul/sections/product-detail/index.tsx
pnpm-lock.yaml

Merging `canary` into `integrations/makeswift` to cut a new release.
https://github.com/user-attachments/assets/22debe6a-0e5c-4823-ab6f-be275128bf6d

Update `integrations/makeswift` with latest code from `canary`

---

.changeset/breezy-buses-push.md
.changeset/mean-geese-retire.md
.changeset/short-lies-draw.md
packages/create-catalyst/CHANGELOG.md
packages/create-catalyst/package.json

Creates a new release for `@bigcommerce/create-catalyst` CLI.
N/A

chore(release): publish create-catalyst CLI

---

README.md
core/app/api/customer/group/route.ts
core/app/api/customer/groups/route.ts
core/client/queries/get-customer.ts
core/lib/makeswift/components.ts
core/lib/makeswift/components/customer-group-slot/customer-group-slot.makeswift.tsx
core/lib/makeswift/components/customer-group-slot/schema.ts

This component can map groups to slots in Makeswift
https://github.com/user-attachments/assets/e32ab87b-7939-4f55-a5c6-4e4d652ccd81

feat: customer-group-slots component

---

core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
core/app/[locale]/(default)/(faceted)/search/page.tsx
core/data-transformers/product-card-transformer.ts
core/vibes/soul/primitives/compare-card/index.tsx
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/wishlist-item-card/index.tsx
core/vibes/soul/primitives/wishlist-item-card/remove-wishlist-item.tsx
core/vibes/soul/primitives/wishlist-item-card/wishlist-item-add-to-cart.tsx
core/vibes/soul/sections/featured-product-list/index.tsx
core/vibes/soul/sections/product-carousel/index.tsx
core/vibes/soul/sections/product-list/index.tsx
core/vibes/soul/sections/products-list-section/index.tsx

Sync `ProductCard` and `WishlistItemCard` with VIBES as a prerequisite to subsequent wishlist PRs
Tested locally, build passes

feat: Sync ProductCard and WishlistItemCard with VIBES

---

core/components/modal/index.tsx
core/components/modal/modal-form-provider.tsx
core/components/wishlist/fragment.ts
core/data-transformers/product-card-transformer.ts
core/data-transformers/wishlists-transformer.ts
core/lib/user-agent.ts
core/messages/en.json

- Add wishlist translations
- Add data transformers for wishlists
- Add `Modal` component wrapper to support wishlist functionality
Tested locally

feat: Add wishlist translations, transformers, and core components

---

core/app/[locale]/(default)/account/wishlists/[id]/_actions/add-to-cart.tsx
core/app/[locale]/(default)/account/wishlists/[id]/_components/visibility-switch.tsx
core/app/[locale]/(default)/account/wishlists/_actions/change-wishlist-visibility.ts
core/app/[locale]/(default)/account/wishlists/_actions/delete-wishlist.ts
core/app/[locale]/(default)/account/wishlists/_actions/mutation.ts
core/app/[locale]/(default)/account/wishlists/_actions/new-wishlist.ts
core/app/[locale]/(default)/account/wishlists/_actions/remove-wishlist-item.ts
core/app/[locale]/(default)/account/wishlists/_actions/rename-wishlist.ts
core/app/[locale]/(default)/account/wishlists/_actions/schema.ts
core/app/[locale]/(default)/account/wishlists/_components/modals/change-visibility.tsx
core/app/[locale]/(default)/account/wishlists/_components/modals/delete.tsx
core/app/[locale]/(default)/account/wishlists/_components/modals/new.tsx
core/app/[locale]/(default)/account/wishlists/_components/modals/rename.tsx
core/app/[locale]/(default)/account/wishlists/_components/modals/share.tsx

- Add wishlist modal content components 
- Add wishlist modal form schemas
- Add server actions for wishlists
- Add visibility switch to be used on Wishlist Details page
Tested locally

feat: Add wishlist modals, actions, and visibility switch

---

core/package.json
pnpm-lock.yaml

https://nextjs.org/blog/cve-2025-29927
CI/CD and preview

Bump next to address CVE

---

core/app/[locale]/(default)/account/wishlists/[id]/_components/share-button.tsx
core/app/[locale]/(default)/account/wishlists/[id]/_components/wishlist-actions.tsx
core/app/[locale]/(default)/account/wishlists/_components/new-wishlist-button.tsx
core/app/[locale]/(default)/account/wishlists/_components/wishlist-actions-menu.tsx
core/app/[locale]/(default)/account/wishlists/modals.tsx

- Add wishlist modal definitions file
- Add wishlist "share" button
- Add wishlist actions dropdown menu component
Tested locally

feat: Add wishlist modal defs, share button, and action dropdown menu

---

.changeset/pnpm-update-03242025.md
package.json
pnpm-workspace.yaml

Updates pnpm to the latest version.
See CI.

chore: update pnpm to 10.6.5

---

.changeset/pnpm-update-03242025.md

Changeset was not valid (which I thought it was) which errored out in CI: https://github.com/bigcommerce/catalyst/actions/runs/14042453605/job/39315609624
N/A

chore: remove invalid changeset

---

core/data-transformers/product-card-transformer.ts
core/lib/makeswift/components/card/card.makeswift.tsx
core/lib/makeswift/components/site-theme/components/card.ts
core/lib/makeswift/components/site-theme/components/product-card.ts
core/lib/makeswift/utils/use-bc-product-to-vibes-product/use-bc-product-to-vibes-product.ts
core/vibes/soul/primitives/card/index.tsx
core/vibes/soul/primitives/compare-drawer/index.tsx
core/vibes/soul/primitives/compare-drawer/loader.tsx
core/vibes/soul/primitives/product-card/index.tsx
core/vibes/soul/primitives/products-carousel/index.tsx
core/vibes/soul/primitives/products-list/index.tsx

- adds ability to change `borderRadius` on `Card` and `ProductCard`
- adds ability to change `fontFamily` on `Card` and `ProductCard`
- fixes issues where `ProductCard` was using the wrong CSS var for setting its `font-family`
- adds controls for new props in `Card` and `ProductCard`
- updates `Card`, `ProductCard`, `Compare` and `CompareDrawer` to the latest Soul VIBE components
https://github.com/user-attachments/assets/305a7765-6127-4d40-bc0e-261c7c356fd9

feat: add ability to update card and productcard

---

core/app/[locale]/(default)/(auth)/login/page.tsx
core/app/[locale]/(default)/cart/page.tsx
core/lib/makeswift/slot.tsx

Added slots to Login and Cart.
https://github.com/user-attachments/assets/d3e9fcbb-fb55-4d83-bc35-62a8dc15dc97
https://github.com/user-attachments/assets/7c53a2a9-2411-4a9b-8f41-4952804af53f

Add slots to Login and Cart

---

.changeset/six-schools-roll.md
core/.gitignore
core/app/[locale]/(default)/(auth)/change-password/_actions/change-password.ts
core/app/[locale]/(default)/(auth)/login/_actions/login.ts
core/app/[locale]/(default)/account/wishlists/[id]/page.tsx
core/app/[locale]/(default)/account/wishlists/modals.tsx
core/app/[locale]/(default)/account/wishlists/page.tsx
core/app/[locale]/(default)/cart/page.tsx
core/app/[locale]/(default)/wishlist/[token]/page.tsx
core/app/[locale]/layout.tsx
core/data-transformers/order-details-transformer.ts
core/data-transformers/wishlists-transformer.ts
core/global.ts
core/messages/en.json
core/next.config.ts
core/package.json
core/tsconfig.json
pnpm-lock.yaml

We want to upgrade to `next-intl` v4 in preparation for `dynamicIO` and to adopt the latest functionality. By adopting TypeScript type augmentation we also make it harder to have translation bugs. This PR already identified existing errors with bad translation keys.
https://github.com/user-attachments/assets/352aee4a-1450-4f88-a0bf-3cb0ec9f99b4

Upgrade `next-intl` to v4 and add TypeScript type augmentation

---

core/app/[locale]/(default)/product/[slug]/page.tsx
core/vibes/soul/sections/product-detail/index.tsx
core/vibes/soul/sections/product-detail/product-detail-form.tsx
core/vibes/soul/sections/product-detail/product-gallery.tsx

- syncs `ProductDetail`, `ProductGallery`, and `ProductDetailForm` from Catalyst
https://github.com/user-attachments/assets/0459d398-f8da-4d18-8c51-c92d7a2087dc

feat: sync pdp components with catalyst

---

core/components/wishlist/fragment.ts
core/data-transformers/wishlists-transformer.ts

- syncs this branch with the latest changes from [ja/fix-wishlist-schema](https://github.com/bigcommerce/catalyst/pull/2192)
- fixes build issues from latest attempts to sync VIBE components

feat: syncs wishlists-transformer with catalyst

---

core/globals.css

Fixes the `globals.css` file with proper formating/css properties.

fix(core): formatting issues with globals.css

---

core/vibes/soul/form/number-input/index.tsx

- adds light border and dark border styles to the `NumberInput` component

fix: border on number-input

---

.changeset/clean-humans-wonder.md
core/vibes/soul/sections/product-detail/index.tsx
core/vibes/soul/sections/product-detail/product-detail-form.tsx

Fixes an issue of not being able to add product to cart when you redirect to product via navigation.
After the fix, you can add product to cart.
Remove changes to UI related to #2191 .

fix(core): revert streamings fields in product form

---

core/vibes/soul/sections/cart/client.tsx
core/vibes/soul/sections/cart/coupon-code-form/coupon-chip.tsx
core/vibes/soul/sections/cart/coupon-code-form/index.tsx
core/vibes/soul/sections/cart/index.tsx
core/vibes/soul/sections/cart/shipping-form/index.tsx

- updates Cart component to the latest VIBES cart component
- fixes wrong border color in order details
- adjusts padding and margin in order details
https://github.com/user-attachments/assets/aa46c1fa-76d6-442a-831f-76785e3ec7dc

feat: update cart component with current VIBES

---

core/globals.css

Missed this add from #2215 and needed to add it back. No changeset as it should be covered in another PR.
N/A
N/A

fix(core): add back in changes from #2215

---

core/middlewares/with-routes.ts
core/vibes/soul/form/switch/index.tsx

Merge `canary` into `integrations/makeswift`.
https://github.com/user-attachments/assets/123d3d20-e18e-4a2b-8f5b-ab9e2dd9b9c0
Pull in latest branch

Merge `canary` into `integrations/makeswift`.

---

core/components/footer/index.tsx
core/components/footer/payment-icons/amazon.tsx
core/components/footer/payment-icons/american-express.tsx
core/components/footer/payment-icons/apple-pay.tsx
core/components/footer/payment-icons/mastercard.tsx
core/components/footer/payment-icons/paypal.tsx
core/components/footer/payment-icons/visa.tsx
core/vibes/soul/sections/footer/index.tsx

- updates `Footer` to the latest VIBES Soul version
- makes improvements to pass the Lighthouse accessibility audit
https://github.com/user-attachments/assets/0a370ab9-0762-4b0b-ac34-70e803bfbafa

feat: make icons accessible

---

core/vibes/soul/primitives/compare-drawer/index.tsx

- fixes border color on `CompareDrawer` card

feat: add border color to compare drawer

---

.changeset/eighty-bushes-cut.md
core/data-transformers/product-options-transformer.ts
core/vibes/soul/sections/product-detail/product-detail-form.tsx
core/vibes/soul/sections/product-detail/schema.ts

Add `textarea` field to product details form.
Locally, tested with default values or no default values.
Add missing textarea field switch case to product details form.

feat(core): add textarea field to product details form

---

README.md

> [!WARNING]
> This PR builds on #2304. Review by last commit on this branch
- Updates the "Getting Started" section of the README to more closely align with the respective page on https://www.catalyst.dev/docs/local-development
- Adds requirements and steps to get started
Tested locally
N/A

chore: CATALYST-1117 update readme quickstart section

---

core/README.md

Updates the README inside of `core/` to match the changes introduced by #2304, #2305, #2306
N/A
N/A

chore: CATALYST-1117 update readme in core

---

.changeset/five-squids-tie.md
.changeset/hungry-plums-hug.md
.changeset/little-hornets-stand.md
.changeset/mean-geese-retire.md

Need to merge this in before #2312 
Cherry picked the first two commits in that PR.
N/A
N/A

chore: move client and CLI changests into separate changesets

---

.changeset/dry-frogs-pump.md
.changeset/five-squids-tie.md
.changeset/gentle-seals-sing.md
.changeset/hungry-plums-hug.md
.changeset/itchy-ways-do.md
.changeset/pretty-coats-accept.md
.changeset/sweet-lions-kneel.md
.changeset/swift-tips-wave.md
packages/client/CHANGELOG.md
packages/client/package.json
packages/create-catalyst/CHANGELOG.md
packages/create-catalyst/package.json

This will trigger a release of the catalyst-client & create-catalyst CLI packages.
N/A
N/A

chore(release): publish create-catalyst CLI & client

---

.gitignore
core/.env.test.example
core/.eslintrc.cjs
core/.gitignore
core/package.json
core/playwright.config.ts
core/tests/README.md
core/tests/environment.ts
core/tests/tags.ts
pnpm-lock.yaml

This is a prerequisite to my upcoming test changes
- Update playwright configuration
- Add eslint rules for test imports
- Update `.gitignore` for new test reporting directory
- Add `README` for basic testing outline and instructions
- Upgrade zod, add t3-oss/env-core for type-safe environment parsing
Tested locally
Copy `/core/tests` directory from this PR

Add test config, README, and setup files

---

.env.example
core/.env.example

It was reported that the `CustomerGroupSlot` component relies on the `BIGCOMMERCE_ACCESS_TOKEN` environment variable which is not documented anywhere in that branch.
This PR documents the environment variable in `.env.example` and syncs `.env.example` with `core/.env.example`
N/A, simply add the environment variable to your `.env.local` file.
N/A, simply add the environment variable to your `.env.local` file.

chore: update and sync .env.example for makeswift branch

---

core/vibes/soul/primitives/button-link/index.tsx
core/vibes/soul/primitives/button/index.tsx
core/vibes/soul/primitives/navigation/index.tsx
core/vibes/soul/sections/blog-post-content/index.tsx
core/vibes/soul/sections/product-detail/index.tsx
core/vibes/soul/sections/products-list-section/index.tsx
core/vibes/soul/sections/slideshow/index.tsx
core/vibes/soul/sections/subscribe/index.tsx

- fixes broken `max-w-screen-2xl` class
- fixes broken `aspect-ratio` not working with circle buttons
https://github.com/user-attachments/assets/697a5a4a-7656-45dc-83dc-8a1ec2972011

fix: broken max-width and aspect-ratio styles

---

core/tests/ui/e2e/compare.spec.ts

Adds e2e tests for compare page.
Locally and CI
d CI
N/A

chore(core): add compare page e2e tests

---

core/tests/fixtures/blog/index.ts
core/tests/fixtures/index.ts
core/tests/fixtures/utils/api/blog/http.ts
core/tests/fixtures/utils/api/blog/index.ts
core/tests/fixtures/utils/api/index.ts
core/tests/ui/e2e/blog.spec.ts

Add e2e tests for Blog index and Blog posts
Copy changes from `/core/tests`

Add e2e tests for Blog and Blog Posts

---

core/app/[locale]/(default)/(auth)/login/page.tsx
core/vibes/soul/primitives/button-link/index.tsx
core/vibes/soul/sections/sign-in-section/index.tsx

- updates styles for the sign-in page
https://github.com/user-attachments/assets/f33eab01-c597-4f26-b5b1-f5afaf28e430

feat: update sign-in styles to match latest vibes

---

.changeset/clever-parts-pull.md
.changeset/config.json
.github/workflows/changesets-release.yml
packages/client/CHANGELOG.md
packages/client/package.json
packages/create-catalyst/CHANGELOG.md
packages/create-catalyst/package.json
packages/eslint-config-catalyst/CHANGELOG.md
packages/eslint-config-catalyst/package.json

Sync `integrations/makeswift` with `canary` and Release 1.0.0

---

.gitignore
.vscode/launch.example.json

feat: add launch.json example for vscode debugger

---

core/.env.test.example

* Encourages principle of least privilege for users who want to run the functional test suite without any skips or failures regardless of `TESTS_READ_ONLY` value
```
cd core && pnpm exec playwright test ui/e2e
```
Not necessary, this is a docs-only change

docs: update .env.test.example with api account scope reqs

---

packages/cli/package.json
packages/cli/src/commands/build.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/lib/mk-temp-dir.ts
packages/cli/src/program.ts
packages/cli/tests/commands/build.spec.ts
packages/cli/tests/commands/deploy.spec.ts
packages/cli/tests/lib/mk-temp-dir.spec.ts
pnpm-lock.yaml

- Scaffolds `deploy` command
- `deploy` builds the zip file and stores in `.bigcommerce/dist/bundle.zip`
Added unit tests
N/A

feat(cli): scaffold deploy command and generate bundle zip

---

packages/cli/src/commands/link.ts
packages/cli/src/lib/project-config.ts
packages/cli/src/program.ts
packages/cli/tests/commands/link.spec.ts
packages/cli/tests/index.spec.ts
packages/cli/tests/lib/project-config.spec.ts
packages/cli/tests/mocks/handlers.ts
pnpm-lock.yaml

Adds `link` command.
- Accepts `--project-uuid` to set a `projectUuid` value in `.bigcommerce/project.json`.
- If no `--project-uuid` is provided, fetches projects and prompts selection.
- Successfully linking also adds `"framework": "catalyst"` to `project.json`.
Unit tests and locally.
N/A

feat(cli): add link command

---

.gitignore
packages/cli/src/commands/build.ts
packages/cli/tests/commands/build.spec.ts
pnpm-lock.yaml

Generates a `bigcommerce/dist` output in the format that the [`deploy` command](https://github.com/bigcommerce/catalyst/blob/canary/packages/cli/src/commands/deploy.ts) expects as input. 
Pull down this branch, run `pnpm i`, then `pnpm -F "./packages/cli" build`, then `node packages/cli/dist/index.js build`. Once complete, you should see a new `.bigcommerce` folder in your current working directory with the following contents:
N/A

feat: build catalyst with opennextjs-cloudflare

---

packages/cli/package.json
packages/cli/src/commands/build.ts
pnpm-lock.yaml

Cloudflare's OpenNext team recently released `@opennextjs/cloudflare` 1.8.0 which includes a feature request we discussed [here](https://github.com/opennextjs/opennextjs-cloudflare/pull/853#issuecomment-3205095480). This PR makes use of that new flag... thanks Cloudflare!
✅ CI Passes
Manual Test (local): 
N/A

feat(cli): use custom opennext config path in new opennextjs cli release
