bigcommerce/catalyst

apps/core/.eslintrc.cjs, apps/core/next.config.js
`next lint` doesn't run by default on all directories.
=> chore(core): run eslint on all dirs

apps/core/app/(default)/product/[slug]/page.tsx
Fixes issue with prices not being the right font size in PDP.
As suggested by @bc-0dp in #505, but with additional fixes for semantic html.
Closes #505
Locally.
=> fix(core): price font size in pdp

package.json
Our current version always logs package changes even when we don't have any. Fixed in newer verison.
after
=> chore(common): bump pnpm

README.md, apps/core/README.md
The rainbow separators in the READMEs were not centered, which looked off when viewing the README directly.
=> chore(core): Center align the separators in the READMEs

apps/core/app/api/revalidate/route/route.ts, apps/core/app/api/revalidate/store-status/route.ts, apps/core/middlewares/with-custom-urls.ts
Now that https://github.com/bigcommerce/catalyst/pull/476 has been merged to main, we can remove the `v2_` prefix, as all  branches will now be using the new format of the cache values. (Can probably hold off a day or so to merge this just to play nice with existing branches)
Verified the KV store is still getting/setting properly, both on initial hydration and when revalidating.
=> chore(core): Remove v2_ prefix from kv keys

packages/functional/tests/visual-regression/reactant/components/BlogPostCard.spec.ts, packages/functional/tests/visual-regression/reactant/components/NavigationMenu.spec.ts, packages/functional/tests/visual-regression/reactant/components/ProductCard.spec.ts, packages/functional/tests/visual-regression/reactant/components/RadioGroup.spec.ts, packages/functional/tests/visual-regression/reactant/components/RectangleList.spec.ts, packages/functional/tests/visual-regression/reactant/components/TextArea.spec.ts
Uses the correct urls after the doc files got renamed.
> [!NOTE]
> The `Zero rating` test failed due to a 1px difference.
=> test: fix renamed component tests

.github/ISSUE_TEMPLATE/config.yml
Temporarily routing users to the README to get started, awaiting formal docs.
=> fix(gh): fix issue template link for docs

apps/core/components/header/index.tsx, packages/components/src/components/navigation-menu/navigation-menu.tsx
Having a large number of categories overflows the menu and breaks the experience.
- Limit the categories to show to 6, and suggest modification if requiring more than 6.
- There is no limit on the GQL endpoint so this is done by slicing the returned array (suggestions welcomed).
- Add `overflow-hidden` in case it still wants to overflow with 6 categories.
Additional: center nav menu
Locally
=> fix(core): limit category tree for parent navigation categories

.gitignore, apps/core/.gitignore
In the monorepo, `apps/core` can inherit necessary `.gitignore` lines from the root `.gitignore`. 
Once cloned via `create-catalyst`, it can no longer do that. This PR moves relevant `.gitignore` lines from root to `apps/core/.gitignore`.
=> fix(core): colocate gitignore lines specific to apps/core

apps/core/client/queries/get-recaptcha-settings.ts, apps/core/components/forms/contact-us.tsx
This pr adds `isEnabledOnStorefront` field for `get-recaptcha-settings` query to respect reCaptcha settings from control panel
Locally
=> feat(core): add check is recaptcha enabled for contact us form

apps/core/app/(default)/product/[slug]/_components/gallery.tsx, packages/components/src/components/gallery/gallery.tsx
- Simplify the Gallery component by wrapping thumbnails instead of showing a scroll bar. No longer need to `scrollIntoView`.
- Decrease size of thumbnails for mobile viewport.
Locally.
=> fix(core): wrap thumbnails in Gallery and remove scrollIntoView

packages/functional/tests/ui/core/components/RadioGroup.spec.ts, packages/functional/tests/ui/core/components/Swatch.spec.ts
Looks like we had some product changes that require test updates. This change should take care of that.
Tested against latest build.
=> fix: Update tests to match product changes

.github/workflows/cli-integration.yml, .github/workflows/cli-unit.yml, packages/create-catalyst/.eslintrc.cjs, packages/create-catalyst/.swcrc, packages/create-catalyst/README.md, packages/create-catalyst/jest.config.cjs, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/init.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/src/utils/clone-catalyst.ts, packages/create-catalyst/src/utils/https.ts, packages/create-catalyst/src/utils/install-dependencies.ts, packages/create-catalyst/src/utils/login.ts, packages/create-catalyst/src/utils/parse.ts, packages/create-catalyst/src/utils/pm.spec.ts, packages/create-catalyst/src/utils/pm.ts, packages/create-catalyst/src/utils/project-config.ts, packages/create-catalyst/src/utils/spinner.spec.ts, packages/create-catalyst/src/utils/spinner.ts, packages/create-catalyst/src/utils/write-env.ts, packages/create-catalyst/tsconfig.json, pnpm-lock.yaml
- Adds initial commands for the `create-catalyst` CLI: `create` and `init`. 
- `create` is the default command, and invoked by running `[npm|pnpm|yarn] create @bigcommerce/catalyst@latest`. The command accepts a number of configurable options that can be passed as flags the CLI command (this is mostly useful for running the CLI in a CI environment). A number of the configurable options have some default values if they are left empty. If no options are passed as flags, the user is prompted to enter values for each option via terminal input. The end result is a Catalyst project, created in a local directory, with an (optionally) configured environment variable file, with dependencies installed, and if the environment variable file is configured, the `create` command also runs GraphQL …
=> feat(cli): CATALYST-246 create-catalyst login, create env, scaffold project

.env.example
Clarify defaulting to Channel 1 and recommend against it.
Headless storefronts like Catalyst work best when they have their own [channel ID, Site URL, Checkout Site URL](https://developer.bigcommerce.com/docs/storefront/headless/channels), and [Routes](https://developer.bigcommerce.com/docs/rest-management/sites/site-routes#create-a-site-route).
=> Clarify Channel 1 in .env.example

packages/functional/tests/ui/core/components/Carousel.spec.ts
Caoursel spec requires an update due to a recent change.
=> fix: Update Carousel spec

packages/create-catalyst/package.json, packages/create-catalyst/src/index.ts, pnpm-lock.yaml
Exits the Node.js process for the `create-catalyst` CLI if the user's Node version is not at least 18.
https://github.com/bigcommerce/catalyst/assets/28374851/d908e36b-01c3-47a2-9d2e-c112f51b5911
=> feat(cli): minimum node.js version check

.github/workflows/cli-integration.yml, packages/create-catalyst/README.md, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/init.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/tsup.config.ts, pnpm-lock.yaml
Previously, `zod` was being used to ensure that the options passed via CLI flags were typed correctly. Commander also maintains https://www.npmjs.com/package/@commander-js/extra-typings which allows us to remove a lot of unnecessary `zod` logic. 
CI
=> feat(cli): introduce types to commander

packages/components/src/components/carousel/carousel.tsx
Removing the looping behavior on the product carousels, as it is causing layout shifts. This seems non-critical enough functionality that I think we should consider removing looping until we can address this.
=> fix(core): Remove product carousel looping to fix layout shift

apps/core/components/hero/index.tsx, apps/core/components/product-card/index.tsx
Adds missing `sizes` property to `Image` components rendered on homepage. No more warnings on dev.
=> fix: add sizes on homepage images

packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/src/utils/pm.ts
* Previously, the available options for the `--package-manager` flag were set outside of the type boundaries defined by `pm.ts`. Someone could accidentally add a new package manager to the CLI option choices and forget to add it to the `pm.ts` module.
* Better variable naming
CI
=> refactor(cli): more reliable package manager detection types

.gitignore, apps/core/.gitignore
Prepping for having a secrets file by adding it to `.gitignore` early.
Can be used for more durable storage of things like access tokens in a way that they do not need to leave the local development environment, and in a way that they can be used to re-generate `.local.env` files themselves (therefore they need to be separate). This will be used by the CLI in the future, but I want to get the `.gitignore` entry in early to make sure as many customers as possible have this ignored from version control to minimize the risk of committing secrets to code.
=> Add .catalyst to .gitignore

apps/core/middleware.ts
[](url)## What/Why?
Our middleware had an extraneous matcher for the home page `/` which is already captured by the primary regex matcher. I *believe* this is what was causing two passthroughs of the middleware on our vercel deploys (interestingly, this did not seem to be happening locally).
Verified that the home page still passes through middleware both locally and on a vercel deploy.
This did indeed fix the double-middleware issue. Previous to this change, a request to the home page looked like:
Now it looks like:
(like every other pages does/did)
=> fix(core): Remove extraneous middleware matcher for home page

packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/check-storefront-limit.spec.ts, packages/create-catalyst/src/utils/check-storefront-limit.ts, packages/create-catalyst/src/utils/https.ts
⚠️ Depends on #572 
As mentioned in https://github.com/bigcommerce/catalyst/pull/572#discussion_r1492990903, this PR adds more reliable checks for active storefront limit, allowing the user the option to create a new channel if the store is allowed to (or use an existing channel), but forcing them to use an existing channel if the store cannot have any more channels created.
CI
=> refactor(cli): more reliable check for storefront limits

packages/create-catalyst/src/utils/https.ts
It was reported that the following error occurred when attempting to access checkout on a new Catalyst storefront:
```
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
```
Logs revealed the underlying error:
```
Error: Unable to get checkout URL: Forbidden
at (node_modules/@bigcommerce/catalyst-client/dist/index.js:192:12)
at (client/management/get-checkout-url.ts:15:19)
at (app/(default)/cart/page.tsx:30:22)
```
This PR adjusts the `store_cart` scope so that it has `write` permissions in addition to `read` permissions.
1. Run `pnpm create catalyst-storefront@latest`
2. `cd …
=> fix(cli): adjust cart token scope to create checkout urls

packages/client/src/client.ts
This PR adds 3 methods to graphql client based on BigCommerce [Management API](https://developer.bigcommerce.com/docs/rest-management/shipping-v2/shipping-zones):
- get all available Countries per Store;
- get a list of States belonging to a Country;
-  get a list of all Shipping Zones
locally
[CATALYST-242]: https://bigcommercecloud.atlassian.net/browse/CATALYST-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(core): CATALYST-242 add shipping countries, states & zones

packages/create-catalyst/src/commands/create.ts
Surfaced by #436 
Adds an extra `--` when passing the `--fix` flag to the `lint` script. Since the extra `--` is compatible with both `yarn` and `pnpm`, we shouldn't need to modify this command depending on package manager, we should be able to just pass the extra `--` no matter which package manager is being used.
=> fix(cli): handle npm script flag passthrough

apps/core/components/store-logo/index.tsx
This pr covers the case when logo is an image and its height bigger than its width
**Header Before**
**Footer Before**
**Header After**
**Footer After**
=> fix(core): limit image logo size

apps/core/components/forms/contact-us.tsx
Removes `eslint-disable` comment by using the named export instead of naming the default export a named member (that's a mouthful 😅). 
This will fix one of the eslint issues preventing: https://github.com/bigcommerce/catalyst/actions/runs/8007584319/job/21872352776?pr=436
from passing.
Run `npm create catalyst-storefront@latest`, allow `lint` task to run, verify `lint` task fixed all issues by running `cd <name_of_your_catalyst_directory> && <package_manager> run lint`
=> fix(build): refactor out eslint-disable comment

packages/create-catalyst/src/utils/check-storefront-limit.spec.ts, packages/create-catalyst/src/utils/check-storefront-limit.ts
Previously, these logs were printed to console in `red`, which makes it look like an error at first glance; after using the CLI in a few edge cases (such as the authenticated store having existing channels available for connection), I realize this log should be in yellow, to convey that this is more of an "important note" than an error.
`npm create catalyst-storefront@latest`
=> refactor(cli): change log color to communicate warning instead of error

apps/core/app/api/revalidate/route/route.ts, apps/core/app/api/revalidate/store-status/route.ts, apps/core/client/queries/get-route.ts, apps/core/lib/kv/keys.ts, apps/core/middlewares/with-routes.ts
Adds a lookup for existing 301 redirects on a Route and redirects as appropriate.
I have also versioned the keys to v3 out of an abundance of caution, based on our previous change in https://github.com/bigcommerce/catalyst/pull/518/files
Confirmed that both manual and entity-targeted redirects work on a real store, and that existing Route functionality is unaffected.
Also confirmed new v3_ keys are correctly writing to KV.
=> Support 301 redirects

apps/core/components/product-form/_actions/add-to-cart.ts
In some scenario, passing an empty string was still appending a value to the option (like in numbers). With this change completely skip entry strings from the form.
Locally.
=> fix(core): skip empty options when adding to cart

apps/core/app/(default)/page.tsx, apps/core/client/queries/get-newest-products.ts, packages/functional/tests/ui/core/components/Carousel.spec.ts
Today we use “best selling products” as one of our default home page panels, which works well with our sample data, because our sample data simulates these products having been sold.
However, for most new users of Catalyst, they’ll eventually delete their sample products and start to use a catalog with new products, and those products by default do not have any sales, which makes this panel blank.
Therefore, switching to "newest products" which will result in a better first-time user experience.
Preview deployment:
=> Change "best selling products" to "newest products" on home page

apps/core/app/api/raw-page/[id]/route.ts, apps/core/client/queries/get-raw-web-page-content.ts, apps/core/client/queries/get-route.ts, apps/core/client/queries/get-web-page.ts, apps/core/middlewares/with-routes.ts
Add proper support for Raw Web Pages, in which the user should be able to set 100% of the HTML content of the page, bypassing the framework or template.
Previously this was broken and trying to insert one HTML document inside of another; this fixes that.
I have opted to use the GQL global ID as the identifier on the API route, and I'd like to start moving towards GQL global IDs in general so this is intentional. I will look at moving the other objects over to this format in a later PR.
Compare output on preview deployment vs prod
**Main (before this PR):**
This is a bootstrap HTML document weirdly embedded into the main one, polluting the styles of the page and doing weird stuff
**After this PR:**
HTML document is 100% what we get back from the API
Raw Web Pages support other content …
=> Support Raw page type properly

apps/core/client/management/get-countries.ts, apps/core/client/management/get-country-states.ts, apps/core/client/management/get-shipping-zones.ts, apps/core/client/mutations/add-checkout-shipping-info.ts, apps/core/client/mutations/select-checkout-shipping-option.ts
This PR updates client on Core with
1. mutations:
- `addCheckoutShippingInfo`,
- `selectCheckoutShippingOption`
2. management:
- `getCountries`,
- `getCountryStates`,
- `getShippingZones`
locally
=> feat(core): add client methods related to shipping

apps/core/app/(default)/cart/_actions/get-shipping-countries.ts, apps/core/app/(default)/cart/_actions/remove-products.ts, apps/core/app/(default)/cart/_components/checkout-summary.tsx, apps/core/app/(default)/cart/_components/shipping-estimator.tsx, apps/core/app/(default)/cart/page.tsx, apps/core/components/forms/_actions/get-shipping-states.ts, apps/core/components/forms/_actions/submit-shipping-costs.ts, apps/core/components/forms/_actions/submit-shipping-info.ts, apps/core/components/forms/index.ts, apps/core/components/forms/shipping-cost.tsx, apps/core/components/forms/shipping-info.tsx
This PR adds components to Core that enable adding Shipping Costs to Cart.
It's based on 2 other PRs:
- [catalyst-242b](https://github.com/bigcommerce/catalyst/pull/435)
- [catalyst-242c](https://github.com/bigcommerce/catalyst/pull/436)
locally
https://github.com/bigcommerce/catalyst/assets/67792608/5163d130-4575-43e9-b9b8-78984364f696
=> feat(core): Catalyst 242 add Shipping Info to Cart

packages/create-catalyst/src/utils/clone-catalyst.ts
Installs latest version of `@bigcommerce/catalyst-client` when running `<pm> create catalyst-storefront@latest` in response to #606
N/A
=> chore(cli): bump installed version of @bigcommerce/catalyst-client

apps/core/next.config.js
Was running into [this issue](https://github.com/phosphor-icons/react/issues/45) with `react-simple-icons` due to them only exporting a barrel file. This causes some issues when the runtime tries to build a page and has to handle a ton of files (or large files) at once.
Before this PR we have been bundling the full export of `@icons-pack/react-simple-icons`. With a recent version of Next.js, it introduces an automagical way of optimizing the imports, cutting down bundle size. This PR cuts down that packages import size while fixing any future versions of the issue I ran into.
=> chore: optimize react-simple-icons

apps/core/app/(default)/cart/_actions/update-product-quantity.ts, apps/core/app/(default)/cart/_components/cart-item-counter.tsx, apps/core/app/(default)/cart/page.tsx, apps/core/client/queries/get-cart.ts
Currently, when a product has a required product modifier, I can't update the quantity without an error. This is because on the backend we require all modifiers to be sent back if we're updating a product, any missing modifiers will be deleted. Because we have a required modifiers it errors out, since it needs to be passed in.
With these changes we pass all product options that are returned from cart and we're able to update product succesfully.
Locally.
=> fix(core): send product options when updating cart item

apps/core/lib/kv/adapters/noop.ts, apps/core/lib/kv/index.ts
Adds a `NoopKvAdapter` in case you don't have KV setup in Vercel. This will be a big tank on site speed if merchants don't want to use any sort of KV.
=> feat: add noop adapter for no-KV setup

packages/create-catalyst/src/commands/init.ts
This PR updates the `init` command of the `create-catalyst` CLI to bring it up to date with the latest changes to the default `create` command.
1. `npm create catalyst-storefront@latest`
2. `npx create-catalyst-storefront@latest init`
=> fix(cli): ability for init command to connect to existing channel

apps/core/app/(default)/product/[slug]/_components/details.tsx
Fix PDP currency formatting to use active currency instead of hardcoded USD.
This relies on the currency code returned on `prices.price`, which is guaranteed to be non-null as long as `prices` is returned.
Before:
After:
=> Fix currency formatting on PDPs to use active currency

apps/core/components/footer/footer-menus/base-footer-menu.tsx, apps/core/components/footer/social-icons.tsx, packages/components/src/components/carousel/carousel.tsx
Couple quick fixes to bring the a11y lighthouse score for `catalyst-demo.site` back up to 100
=> fix(a11y): fix carousel aria roles

packages/client/package.json, packages/client/src/client.ts, packages/client/src/types.ts, packages/client/src/utils/getOperationName.ts, packages/client/src/utils/normalizeQuery.ts, pnpm-lock.yaml
~Builds on top of https://github.com/bigcommerce/catalyst/pull/615~
Currently our client only works with `TypedDocumentString` from gql codegen. This PR adds support for `TypedDocumentNode` and tada's `DocumentNode`.
=> feat(core): add support for more document nodes

README.md
Updates the Catalyst deploy button to use the BigCommerce Vercel Integration (instead of manual environment variable inputs).
https://github.com/bigcommerce/catalyst/assets/28374851/16f5ade4-5189-42db-912f-21388cff1920
=> feat(deploy): add bigcommerce vercel integration to deploy button

apps/core/app/[locale]/not-found.tsx, apps/core/components/forbidden/index.tsx, apps/docs/stories/message.stories.tsx, packages/components/src/components/message/message.tsx, packages/functional/tests/visual-regression/reactant/components/Message.spec.ts
**Extra**: Additionally removed some unnecessary use cases of the Message component.
Locally
=> feat(component): add default 'Info' variant to Message component

packages/components/src/components/radio-group/radio-group.tsx
Missed wrapping in `cn` to properly merge classes when overriden.
Locally.
=> fix(component): properly merge classes in radioGroupVariants

README.md
Updates the README docs link to point to catalyst.dev/docs rather than the /docs directory in this repo.
=> chore(core): Update README.md to point to new docs

README.md
Update the link to the monorepo docs to point to the catalyst.dev docs rather than the markdown file in the repo.
=> chore(docs): Update monorepo docs link

.gitignore, apps/core/package.json, apps/core/tsconfig.json, pnpm-lock.yaml
First PR to unblock some upcoming changes. Installs `gql.tada` and sets up the plugin.
=> chore(core): install gql.tada

apps/core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts, apps/core/client/queries/get-product-search-results.ts
Pass in `before` variable from query params to navigate to previous pages in navigation. With `before` we have to use `last` to only fetch the limit desired. We can't pass in `first` and `last` in the same query.
https://github.com/bigcommerce/catalyst/assets/196129/f2abdeea-a741-47ba-abf0-a916188cbab8
Locally.
=> fix(core): allow previous page navigation in pagination

.github/workflows/changesets-release.yml
Introduces the `changesets` [release action](https://github.com/changesets/action?tab=readme-ov-file#changesets-release-action):
>This action for [Changesets](https://github.com/atlassian/changesets) creates a pull request with all of the package versions updated and changelogs updated and when there are new changesets on [your configured `baseBranch`](https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#basebranch-git-branch-name), the PR will be updated. When you're ready, you can merge the pull request and you can either publish the packages to npm manually or setup the action to do it for you.
In our case, I've set this action up so that the action automatically publishes to NPM for us, removing the need to publish manually. 
There are some slight …
=> feat(build): add changesets github action for releases

.github/workflows/changesets-release.yml
`pnpm` needs to be setup before `setup-node` can reference it.
Fixes: https://github.com/bigcommerce/catalyst/actions/runs/8256068021/job/22583927115#step:3:20
CI
=> fix(build): setup pnpm before referencing pnpm cache

.changeset/silent-horses-beam.md, packages/create-catalyst/package.json, pnpm-lock.yaml
Bump `zod-validation-error` for the `create-catalyst` CLI to `^3.0.3`. This fixes a recently discovered bug that was caused by `zod-validation-error@3.0.2`.
Bug report:
`pnpm create catalyst-storefront@latest`
=> fix(deps): bump zod-validation-error to fix import error

.changeset/breezy-spies-sleep.md, apps/core/app/[locale]/(default)/(faceted)/search/page.tsx
The No Search Results form was missing a translation provider. This fixes that.
Verified that the "No Search Results" form now shows translated strings rather than e.g. `NotFound.searchProducts`
=> fix(core): Add translation provider to No Search Results

docs/cli.md, docs/deployment.md, docs/index.md
Our [catalyst.dev/docs](https://catalyst.dev/docs) site now has support for rendering internal links in the `.md` files correctly. Previously it was converting them to e.g. `/docs/docs/cli` rather than `/docs/cli`. This behavior has been fixed, so we can once again use internal links to other markdown files.
Tested against a preview build of the catalyst.dev/docs site pointing to this branch.
=> fix(docs): Re-add internal md links

docs/deployment.md
Missed one broken link in my prior PR that did not get changed when `cli.md` was renamed from `getting_started.md`. Also fixed a link that was going to the wrong destination.
Documentation change.
=> fix(docs): Fix additional broken link

.changeset/shiny-hornets-move.md, apps/core/client/mutations/submit-change-password.ts, apps/core/client/mutations/submit-reset-password.ts
This PR adds 2 mutations for reset password pages (Registered  customer flow):
- `submitResetPassword` is being used for sending a link on provided email,
-  `submitChangePassword` is aimed to updating existing password with new one.
locally
=> feat(core): add mutations for reset password

.changeset/fair-cheetahs-relate.md, apps/core/client/graphql.ts
Initial prep work for upcoming `gql.tada` changes.
exports a graphql() powered by gql.tada
=> feat(core): init graphql.tada

.changeset/perfect-spies-cheat.md, apps/core/app/[locale]/(default)/cart/_components/checkout-summary.tsx, apps/core/app/[locale]/(default)/cart/page.tsx, apps/core/client/queries/get-cart.ts
Discount was not showing in cart for a marketing promotion. Noticed we were using the `discountedAmount` for each specific line item instead of the global discounted amount value. 
Locally
=> fix(core): use amount and discounts fields for cart summary

.changeset/swift-cougars-wait.md, apps/core/client/mutations/add-cart-line-item.ts, apps/core/client/mutations/add-checkout-shipping-info.ts, apps/core/client/mutations/assign-cart-to-customer.ts, apps/core/client/mutations/create-cart.ts, apps/core/client/mutations/delete-cart-line-item.ts, apps/core/client/mutations/login.ts, apps/core/client/mutations/select-checkout-shipping-option.ts, apps/core/client/mutations/submit-change-password.ts, apps/core/client/mutations/submit-contact-form.ts, apps/core/client/mutations/submit-reset-password.ts, apps/core/client/mutations/unassign-cart-from-customer.ts, apps/core/client/mutations/update-cart-line-item.ts, apps/core/client/mutations/update-checkout-shipping-info.ts
Refactor all mutations to use `gql.tada`
=> refactor(core): use gql.tada on mutations

.changeset/poor-schools-exercise.md, apps/core/client/queries/get-blost-post.ts, apps/core/client/queries/get-brand.ts, apps/core/client/queries/get-brands.ts, apps/core/client/queries/get-category-tree.ts, apps/core/client/queries/get-product-reviews.ts, apps/core/client/queries/get-raw-web-page-content.ts, apps/core/client/queries/get-recaptcha-settings.ts, apps/core/client/queries/get-route.ts, apps/core/client/queries/get-store-settings.ts
This PR is the first pass to migrate our queries to `gql.tada`.
Started with the queries that have no external fragments or enums involved.
Pages using these queries load with the correct data.
=> refactor(core): use gql.tada on simple queries

.changeset/tall-crabs-leave.md, apps/core/app/[locale]/(default)/cart/_components/shipping-estimator.tsx
Button styles were being applied but this button is very subtle and needs no bg on hover (Cancel button in image).
Locally
=> fix(core): on hover bg for buttons in shipping estimator

.changeset/gentle-countries-bake.md, packages/create-catalyst/src/commands/create.ts
`exec` option for `cwd` isn't working properly, and results in the following error when running the CLI:
Using `--prefix` flag fixes this issue
Verdaccio, locally:
=> fix(cli): use prefix flag to set cwd for schema generation

.changeset/wet-students-fry.md, apps/core/app/[locale]/(default)/cart/_components/shipping-estimator.tsx
No need to display if the cost is $0.
Handling cost shown below:
Locally.
=> feat(core): hide handling cost if no cost associated

apps/core/client/queries/get-store-status.ts, apps/core/middlewares/with-routes.ts
Refactor `getStoreStatus` to use gql.tada
Note: `gql.tada` doesn't generate `enums` like codegen, added a few manual types.
=> refactor(core): use gql.tada on store status query

.changeset/polite-items-burn.md, apps/core/app/[locale]/(default)/cart/_components/checkout-summary.tsx
Seems like we lost the classes in the Internationalization PR. Adding them back.
Locally.
=> fix(core): use correct font styles for Grand Total

apps/core/client/fragments/money-fields.ts, apps/core/client/queries/get-cart.ts
[Hide whitespace for this one
](https://github.com/bigcommerce/catalyst/pull/673/files?w=1)
`getCart` now uses `gql.tada`.
`MoneyFields` fragment was only used in `getCart`.
=> refactor(core): use gql.tada on get cart query

.changeset/big-stingrays-collect.md, packages/create-catalyst/src/utils/clone-catalyst.ts
Explicitly define `name`, `description`, `version`, and `scripts` in `zod` schema because defined properties are always placed above properties parsed by the `zod.passthrough` method.
Note how `name`, `description`, `version`, and `scripts` are all placed above other defined properties - when the CLI deletes properties such as `private`, `exports`, etc., they will still be at the top:
=> fix(cli): adjust order of package.json properties

.changeset/little-flowers-invite.md, packages/create-catalyst/src/utils/clone-catalyst.ts, packages/create-catalyst/src/utils/install-dependencies.ts
Rather than writing a hardcoded version specifier to `package.json` during project creation, we will instead delete the `package.json` entries for workspace dependencies such as `@bigcommerce/catalyst-client` and simply install them manually during the "Installing dependencies" phase of project creation.
https://github.com/bigcommerce/catalyst/assets/28374851/bce4c76c-9c04-46c7-a4bb-ccbc0dd11a9a
=> fix(cli): install latest versions of catalyst dependencies

apps/core/client/fragments/prices.ts, apps/core/client/queries/get-product.ts
Move `getProduct` query to use `gql.tada`.
=> refactor(core): use gql.tada on get product

apps/core/client/fragments/web-page.ts, apps/core/client/queries/get-web-page.ts, apps/core/client/queries/get-web-pages.ts
Refactor `getWebPage` and `getWebPages` queries to use `gql.tada`.
Removed the shared fragment and some unused properties.
=> refactor(core): use gql.tada on get web pages queries

apps/core/client/fragments/page-details.ts, apps/core/client/fragments/product-details.ts, apps/core/client/queries/get-featured-products.ts, apps/core/client/queries/get-newest-products.ts, apps/core/client/queries/get-product-search-results.ts, apps/core/client/queries/get-products.ts, apps/core/client/queries/get-quick-search-results.ts, apps/core/client/queries/get-related-products.ts
[Hide whitespaces on this one](https://github.com/bigcommerce/catalyst/pull/688/files?diff=unified&w=1)
Port remaining queries to `gql.tada`, had to do all these together because of the shared `ProductDetails` fragment.
=> refactor(core): use gql.tada on remaining queries

apps/core/client/mutations/register-customer.ts
This mutation was merged recently, moved it to tada 🪄
=> refactor(core): use gql.tada on register customer mutation

.changeset/good-pets-dress.md, apps/core/app/[locale]/(default)/login/_components/login-form.tsx
When User Enters wrong credentials. Login Form shows missing translation key due to misspelling
open login page enter wrong credentials
=> Fix Login Error Translation Key

apps/core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts, apps/core/app/[locale]/(default)/cart/_actions/update-product-quantity.ts, apps/core/app/[locale]/(default)/cart/_components/cart-item-counter.tsx, apps/core/client/queries/get-product-search-results.ts, apps/core/components/product-form/_actions/add-to-cart.ts
Continuation of https://github.com/bigcommerce/catalyst/pull/690
Removes remaining usages of codegen. Will open a follow-up PR removing the codegen setup.
=> refactor(core): remove cogen usages v3

apps/core/package.json, pnpm-lock.yaml
Bumping gql.tada pacakges as the new versions have improved performance.
=> chore(core): bump gql.tada packages

.changeset/gorgeous-bugs-tickle.md, packages/create-catalyst/package.json, pnpm-lock.yaml
unjs/giget#153 has been merged and is [included in the `giget@1.2.3` release](https://github.com/unjs/giget/releases/tag/v1.2.3). This means that `@` characters are now supported as valid GitHub refs. Usage:
```sh
pnpm create @bigcommerce/catalyst@latest --gh-ref @bigcommerce/catalyst-core@0.2.1
```
1. Clone
2. Install dependencies
3. Build `packages/create-catalyst`
4. Run `node ~/path/to/catalyst/packages/create-catalyst/dist/index.js --package-manager pnpm --gh-ref @bigcommerce/catalyst-core@0.2.1`
5. Confirm code merged after #681 is not included in created project
=> feat(cli): support @ symbols in gh-ref flag

apps/core/lib/store-assets.ts, docs/cdn-and-images.md
Adds new helper functions + docs for using store assets in `/content` or Image Manager as part of a Catalyst storefront.
Tested each function in isolation to load the carousel image and a link to a PDF.
=> Add new helper functions for serving store assets

.changeset/poor-pens-matter.md, apps/core/client/fragments/form-fields.ts, apps/core/client/queries/get-address-form-fields.ts, apps/core/client/queries/get-customer-form-fields.ts
This pr adds
- `getAddressFormFields` query
- `getCustomerFormFields` query
- `FormFields` fragment used in those queries
Locally
=> feat(core): add customer & address form fields queries

apps/core/next.config.js
Now that we've added a custom image loader in https://github.com/bigcommerce/catalyst/pull/701, we no longer need to specify these remotePatterns.
https://catalyst-ksjmb4x1t-bigcommerce-platform.vercel.app/
=> Remove remotePatterns from next.config.js

apps/core/lib/store-assets.ts
After further discussion, we think it's not a great default to invalidate CDN assets after every deploy, as it will result in a lot of wasteful revalidation.
Removing this invalidation string in order to re-evaluate the approach. The ideal approach would have awareness of when assets in object storage have actually changed.
=> Remove commit hash from store asset paths in helpers

.changeset/stale-tigers-cheat.md, apps/core/app/[locale]/(default)/login/_actions/submit-change-password-form.ts, apps/core/app/[locale]/(default)/login/_components/change-password-form.tsx, apps/core/app/[locale]/(default)/login/page.tsx, apps/core/client/mutations/submit-change-password.ts, apps/core/messages/en.json, packages/components/src/components/form/form.tsx
This PR adds second step for changing password.
locally
=> feat(core): add components for change password

.changeset/itchy-deers-argue.md, apps/core/app/[locale]/(default)/login/_actions/submit-reset-password-form.ts, apps/core/app/[locale]/(default)/login/_components/reset-password-form.tsx, apps/core/app/[locale]/(default)/login/page.tsx, apps/core/client/mutations/submit-reset-password.ts, apps/core/messages/en.json
This PR adds functionality to reset password for Customer and includes 2 steps:
- reset password email,
- change password
it's based on [PR](https://github.com/bigcommerce/catalyst/pull/628) with mutations.
locally
=> feat(core): reset password

.changeset/fresh-lemons-lick.md, apps/core/app/[locale]/(default)/compare/_components/add-to-cart-form.tsx, apps/core/components/product-card/cart.tsx, apps/core/components/product-form/index.tsx
Add opportunistic `prefetch` to the cart link a shopper sees immediately after add-to-cart, since they are very likely to click on it after adding to cart.
This is a low-traffic, high-value deployment of prefetch which significantly improves the experience.
Added to cart on PDP, PLP, and compare page and compared load performance of the cart link to main.
Try it yourself on the preview deployment.
=> Prefetch the cart link immediately after add-to-cart

.changeset/fair-shrimps-compete.md, apps/core/app/[locale]/(default)/cart/_components/cart-item-counter.tsx, apps/core/app/[locale]/(default)/cart/_components/cart-item.tsx, apps/core/app/[locale]/(default)/cart/page.tsx, apps/core/client/queries/get-cart.ts
Builds of #711 to show correct pricing info.
Fetch and show digital items in Cart.
Locally
=> feat(core): fetch and show digital items in Cart

.github/workflows/.lighthouserc-desktop.json, .github/workflows/lighthouse.yml, .github/workflows/lighthouseCommentMaker.js
This change lets us take a look at the lighthouse scores for mobile and desktop configurations at once. This would help us from being blindsided to degradation on one or the other and also gives us option to track them continuosly. 
This change's impact are posted as a comment on this PR.
=> feat: Generate lh scores for desktop and mobile

.changeset/unlucky-roses-accept.md, packages/components/src/components/carousel/carousel.tsx
Only visible highlight when using keyboard navigation.
Locally
=> fix(component): use focus-visible in Carousel

.changeset/mean-meals-appear.md, apps/core/app/[locale]/(default)/cart/_components/shipping-info.tsx, packages/components/src/components/form/form.tsx
To match the expected behavior, this change will preselect first state (if country has states array) so that it visibly demonstrate state selection that is currently being preselected when form submits.
Locally.
=> fix(core): preselect first state when country is selected

.changeset/sweet-frogs-compete.md, apps/core/app/[locale]/(default)/product/[slug]/_components/breadcrumbs.tsx, apps/core/client/queries/get-product.ts
The breadcrumb links on the PDP were all pointing to `#`. I've added the `path` field to the getProduct query so that we have the path of each category available to populate the link with.
Verified that the breadcrumb links on the PDP now link to the correct page.
=> fix(core): Fix breadcrumb links on PDP

.changeset/tiny-balloons-learn.md, apps/core/app/[locale]/(default)/cart/_components/checkout-summary.tsx, apps/core/messages/en.json
Add total tax from checkout.
Locally.
=> feat(core): add tax total in checkout summary

.changeset/brown-buses-juggle.md, apps/core/app/[locale]/(default)/cart/_actions/apply-coupon-code.ts, apps/core/app/[locale]/(default)/cart/_actions/remove-coupon-code.ts, apps/core/app/[locale]/(default)/cart/_components/checkout-summary.tsx, apps/core/app/[locale]/(default)/cart/_components/coupon-code.tsx, apps/core/app/[locale]/(default)/cart/_components/coupon-codes.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-estimator.tsx, apps/core/client/mutations/apply-checkout-coupon.ts, apps/core/client/mutations/unapply-checkout-coupon.ts, apps/core/client/queries/get-checkout.ts, apps/core/messages/en.json, packages/functional/tests/ui/desktop/e2e/cart.spec.ts
Allow applying and removing coupons in cart.
https://github.com/bigcommerce/catalyst/assets/196129/62c09969-919b-433d-8b03-017e0ac13f17
TBD
=> feat(core): allow applying coupons to cart

.changeset/smart-turtles-raise.md, apps/core/app/[locale]/(default)/cart/_components/shipping-info.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-options.tsx, apps/core/client/mutations/add-checkout-shipping-consignments.ts, apps/core/client/mutations/select-checkout-shipping-option.ts, apps/core/client/mutations/update-checkout-shipping-consigment.ts
Because we were not passing in customer id, logged in users couldn't update shipping info.
Locally.
=> fix(core): pass customer id to shipping mutations

.changeset/yellow-clouds-grab.md, apps/core/app/api/cart-quantity/route.ts, apps/core/components/header/cart-icon.tsx, apps/core/components/header/cart.tsx, apps/core/middlewares/with-routes.ts
Move the cart badge icon (indicating the number of items in the cart) to a client component, allowing us to drop the requirement that the user must not have a cart yet in order to support static routes. Now, the static pages are generated with empty carts, and when the client `CartBadge` component is initially rendered, it fetches the cart quantity from a new API endpoint. Revalidation of data still works as it did previously.
Tested locally and in a vercel preview build, verifying that the transition from empty cart -> populated cart works correctly, as well as subsequent additions to the cart.
=> feat(core): Support SSG when the cart is non-empty

.github/dependabot.yml
`eslint` major will take us a bit, need to update BC's config first
=> chore(ci): dependabot ignore eslint major

.changeset/fuzzy-colts-draw.md, apps/core/app/[locale]/(default)/account/[tab]/_components/account-tabs.tsx, apps/core/app/[locale]/(default)/account/[tab]/layout.tsx, apps/core/app/[locale]/(default)/account/[tab]/page.tsx, apps/core/app/[locale]/(default)/account/page.tsx, apps/core/messages/en.json
This PR adds tabs for Customer's account page.
Locally
=> feat(core): add tabs for customer account

.changeset/thin-guests-doubt.md, apps/core/app/[locale]/(default)/cart/_components/cart-item.tsx, apps/core/app/[locale]/(default)/cart/_components/remove-from-cart-button.tsx
Add loading state to remove button in Cart to improve UX experience.
https://github.com/bigcommerce/catalyst/assets/196129/d1e64a2e-c1a7-4bdb-b79b-386c5b54e79e
Locally.
=> feat(core): add loading state to remove button in Cart

.changeset/slow-pens-change.md, apps/core/package.json, pnpm-lock.yaml
`@icons-pack/react-simple-icons` released a new patch version addressing the typing issues with latest `@types/react`.
This change should fix the errors in https://github.com/bigcommerce/catalyst/pull/738 
CI 👀
=> chore(core): bump react simple icons

pnpm-lock.yaml
Updates `tar` to `6.2.1` to fix a security vulnerability. See https://github.com/bigcommerce/catalyst/security/dependabot/19
=> chore(deps): update tar package to latest

.changeset/late-roses-fly.md, .changeset/three-hairs-nail.md, apps/core/app/[locale]/(default)/cart/_components/shipping-info.tsx, packages/components/src/components/select/select.tsx
Updates the behavior of the select component in order to scroll for longer lists.
https://github.com/bigcommerce/catalyst/assets/10539418/c902de5b-829b-4635-a680-41505c35ee44
=> fix: select component wouldn't scroll with long list

.changeset/thick-adults-love.md, apps/core/client/queries/get-customer.ts
This pr adds query to get Customer's account data
Locally
=> feat(core): add get customer query

.changeset/smooth-ties-explain.md, apps/core/messages/en.json
Adds the missing `Cart.spinnerText` translation.
=> fix(core): add missing Cart.spinnerText translation

.changeset/itchy-humans-beam.md, apps/core/app/[locale]/(default)/cart/_components/shipping-info.tsx, apps/core/messages/en.json, packages/components/src/components/select/select.tsx, packages/functional/actions/cart-actions.ts, packages/functional/tests/ui/desktop/e2e/shipping.spec.ts
Add UI tests for calculating shipping estimates on cart items.
Newly added tests should run on this PR.
=> feat(core): Add tests for shipping estimates

.changeset/silver-bulldogs-hammer.md, apps/core/app/[locale]/(default)/account/layout.tsx, apps/core/app/[locale]/(default)/account/page.tsx
Check for auth in all child pages of `/account`. Currently accessing `/account/settings` without being logged in will still render the page.
Navigating to `/account/settings` redirects to `/login` when not logged in.
=> fix(core): check for auth on account pages

packages/functional/tests/ui/desktop/e2e/account.spec.ts
Test to verify that a guest user cannot access account settings unless they login.
Tested against a deployment locally.
=> feat(core): Verify account access is restricted

.changeset/green-pets-sneeze.md, apps/core/client/mutations/delete-customer-address.ts
This PR adds a mutation for deleting Customer's address 
locally
=> feat(core): add delete address mutation

.changeset/empty-carrots-poke.md, apps/core/lib/kv/adapters/dev.ts, apps/core/package.json, pnpm-lock.yaml
Use an LRU cache for our dev kv adapter. This should work closer to how KV works in prod.
We will be dogfooding this for a bit, and potentially promote it to a non-dev adapter as it may benefit self-hosters.
=> feat(core): use LRU cache for DevKvAdapter

.changeset/clean-jokes-sneeze.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/src/utils/clone-catalyst.ts
Creates the `.vscode/settings.json` file pointing to the Typescript SDK. This will help with new repos getting better TS support for gql-tada locally.
=> feat(cli): copy vscode ts settings

.changeset/angry-nails-help.md, apps/core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, apps/core/app/[locale]/(default)/account/page.tsx, apps/core/app/api/auth/[...nextauth]/route.ts
Apply the edge runtime to missing routes.
=> fix: apply the edge runtime to missing routes

.github/workflows/basic.yml, .github/workflows/changesets-release.yml, .github/workflows/cli-unit.yml, .github/workflows/lighthouse.yml, .github/workflows/playwright-ui.yml, .github/workflows/playwright-visual-regression.yml
Pins the actions used in our workflows to the latest version. This is to increase stability in our actions by not always using the latest version.
See CI.
=> chore: pin github actions to latest versions

.changeset/four-candles-share.md, apps/core/lib/kv/adapters/vercel.ts
Adds a best-effort cache for Vercel KV reads. This cache will be hit while a worker isolate is being reused.
=> feat(core): vercel kv adapter cache

.changeset/quick-pumas-invent.md, apps/core/package.json
Enables `--turbo`, last time we tried it crashed importing images, it seems to be working fine for our use-case now.
=> chore(core): use next dev --turbo

docs/localization.md
- Fix syntax for notes in the doc
Before:
After:
=> Update syntax for notes

.changeset/itchy-buttons-join.md, apps/core/prettier.config.js, apps/docs/prettier.config.js, packages/components/prettier.config.js
Remaps the `tailwindFunctions` class name utility from `cs` (old) to `cn` (new). Looks like it was missed in https://github.com/bigcommerce/catalyst/pull/457
See the lint task
=> chore: update tailwindFunctions to use correct utility name

apps/core/app/[locale]/(default)/blog/page-data.ts, apps/core/app/[locale]/(default)/blog/page.tsx, apps/core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx, apps/core/components/blog-post-card/index.tsx
Fragment colocation for `/blog` and `blog/tag/[tag]`.
Query is still shared between the two pages.
=> refactor(core): blog fragment colocation

.changeset/lovely-camels-raise.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/src/utils/clone-catalyst.ts
Adds the ability to include the functional test suite when creating a Catalyst repo from the CLI. We are about to migrate the tests over to the core app which this PR adds some preparation for it from the CLI perspective.
> [!WARNING]
> Just note that the functional test suite won't actually be included until we port it over. This is prep work for it actually being added.
=> feat(cli): add option to include functional test suite

.changeset/curly-trees-stare.md, apps/core/app/[locale]/(default)/blog/[blogId]/page.tsx, apps/core/app/[locale]/(default)/cart/_components/cart-item.tsx, apps/core/app/[locale]/(default)/cart/_components/checkout-summary.tsx, apps/core/app/[locale]/(default)/cart/_components/coupon-code.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-estimator.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-options.tsx, apps/core/app/[locale]/(default)/cart/page.tsx, apps/core/app/[locale]/(default)/product/[slug]/_components/details.tsx, apps/core/app/[locale]/(default)/product/[slug]/_components/product-review-schema.tsx, apps/core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx, apps/core/components/blog-post-card/index.tsx, apps/core/components/pricing/index.tsx, apps/core/components/product-form/fields/date-field.tsx, apps/core/components/product-sheet/product-sheet-content.tsx
Use `formatter` from next-intl for [numbers](https://next-intl-docs.vercel.app/docs/usage/numbers) and [dates](https://next-intl-docs.vercel.app/docs/usage/dates-times) to leverage locale.
Made sure it is still formatting as expected.
=> feat(core): use next-intl to format dates and currencies

packages/functional/playwright.config.js
This cleans up unused playwright projects that weren't being referenced or used.
https://github.com/bigcommerce/catalyst/actions/runs/8821597392
=> chore(functional): remove erroneous playwright projects

packages/create-catalyst/src/utils/clone-catalyst.ts
Removes the forward slash in front of the playwright strings as the eslint file doesn't contain them.
```js
{
// ...
ignorePatterns: ['client/generated/**/*.ts', 'playwright-report/**', 'test-results/**'],
}
```
Ran a symlinked version of the CLI locally, using the latest github ref:
```bash
cd $(mktemp -d) && catalyst --gh-ref=ba0b205866891184bbe224e5a45783db6a44e032
```
=> fix(cli): remove forward slash from regex

apps/core/tests/ui/desktop/e2e/account.spec.ts
Add Account tabs tests to verify they are present and clickable
=> feat(functional): Add Account tabs test

packages/client/package.json, packages/components/package.json, pnpm-lock.yaml
Removes unused jest + testing-library packages and their `package.json` scripts.
Closes #826 
See CI
=> chore: remove unused jest + testing-library

apps/core/package.json
This causes an issue with the hero image we import in the homepage. This is fixed in Next 14.2, we can add it back when we upgrade next.
=> fix(core): remove --turbo from dev script

.changeset/nasty-crabs-do.md, apps/core/app/[locale]/(default)/cart/_actions/remove-item.ts, apps/core/app/[locale]/(default)/cart/_components/coupon-code/apply-coupon-code.ts, apps/core/app/[locale]/(default)/cart/_components/coupon-code/remove-coupon-code.ts, apps/core/app/[locale]/(default)/cart/_components/item-quantity/update-item-quantity.ts, apps/core/app/[locale]/(default)/cart/_components/shipping-info/get-shipping-states.ts, apps/core/app/[locale]/(default)/cart/_components/shipping-info/index.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-info/submit-shipping-info.ts, apps/core/app/[locale]/(default)/cart/_components/shipping-options/index.tsx, apps/core/app/[locale]/(default)/cart/_components/shipping-options/submit-shipping-costs.ts, apps/core/app/[locale]/(default)/compare/_actions/add-to-cart.ts, apps/core/app/[locale]/(default)/compare/_components/add-to-cart-form.tsx, apps/core/app/[locale]/(default)/login/_actions/submit-change-password-form.ts, apps/core/app/[locale]/(default)/login/_actions/submit-login-form.ts, apps/core/app/[locale]/(default)/login/_actions/submit-reset-password-form.ts, apps/core/app/[locale]/(default)/login/_components/login-form.tsx, apps/core/app/[locale]/(default)/webpages/contact/[id]/contact-us/_actions/submit-contact-form.ts, apps/core/app/[locale]/(default)/webpages/contact/[id]/contact-us/index.tsx, apps/core/components/product-card/_actions/add-to-cart.ts, apps/core/components/product-card/cart/index.tsx, apps/core/components/product-form/_actions/add-to-cart.ts, apps/core/components/product-form/index.tsx, apps/core/components/quick-search/_actions/get-search-results.ts, apps/core/components/quick-search/index.tsx
Standardize actions by making sure actions have the same elementsd.
Locally.
=> chore: standardize actions

apps/core/app/[locale]/(default)/product/[slug]/_components/gallery/fragment.ts, apps/core/app/[locale]/(default)/product/[slug]/_components/gallery/index.tsx, apps/core/app/[locale]/(default)/product/[slug]/page.tsx
~⚠️  Builds on top of https://github.com/bigcommerce/catalyst/pull/833~
Product gallery now defines its own gql fragment.
=> refactor(core): product gallery fragment colocation

.changeset/itchy-buttons-join.md, .changeset/thin-pumpkins-search.md
Our CI is erroring out: https://github.com/bigcommerce/catalyst/actions/runs/8901051590/job/24443995639
This removes the reference to the docs package which was removed in #835 
See CI.
=> chore: remove @bigcommerce/docs references from changesets

.changeset/rude-dodos-collect.md, apps/core/client/index.ts, apps/core/lib/kv/index.ts
Respects when `CLIENT_LOGGER="false"` or `KV_LOGGER="false"` is set in `.env.local` regardless of environment. This make it a little more configurable when doing local development.
=> feat: respect logger=false in environment variables

.changeset/perfect-roses-cheer.md, packages/create-catalyst/src/utils/clone-catalyst.ts
Since we no longer have `/packages/components`, we don't need to clone it.
TBD
=> chore(cli): remove cloning logic for components

apps/core/app/[locale]/(default)/product/[slug]/_components/related-products.tsx, apps/core/app/[locale]/(default)/product/[slug]/page.tsx
The `RelatedProducts` component is wrapped in `<Suspense>`. I converted it to a fragment instead of a query in a previous PR by mistake.
=> refactor(core): related products query

.changeset/perfect-seas-breathe.md, apps/core/app/[locale]/not-found.tsx
The not found template doesn't account for stores that do not have any featured products, which is a dev error. 
If featured products do not exist, not-found template still shows the section and the h3 headline. this commit fixes that with a length check / fallback of return null.
The git file changes may show a big block replacement, but the only changes are the if statement above the section open and else condition below the section close.
I tested by running two different Catalyst stores in dev & build, one on a store with no featured products, and one with featured products. I also had tested using a single store with featured products toggled on/off too.
=> don't show featured products section if none exist (on not-found template)

.changeset/early-bananas-wonder.md, apps/core/app/[locale]/(default)/blog/[blogId]/page-data.ts, apps/core/app/[locale]/(default)/blog/[blogId]/page.tsx, apps/core/app/[locale]/(default)/blog/page-data.ts, apps/core/app/[locale]/(default)/blog/page.tsx, apps/core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx
Fixes: #853
Doesn't return 404 if the blog is disabled from navigation. This is to preserve functionality from Stencil -> Catalyst.
=> fix(core): respect isVisibleInNavigation for blog pages

apps/core/app/[locale]/(default)/product/[slug]/_components/details.tsx, apps/core/components/product-sheet/product-sheet-content.tsx, apps/core/messages/en.json
Removes extra `:` on PDP page:
=> fix(core): remove extra colon on PDP sales price

.vscode/settings.example.json
Missed this change whenever we moved the `apps/core` folder in #870
=> chore: fix vscode settings pattern

.vscode/settings.example.json
Wasn't actually picking up the tsconfig because it wasn't properly configured.
=> chore: actually fix vscode settings

.changeset/quiet-carrots-yell.md, core/app/[locale]/layout.tsx
Sets a min width to body to prevent shrinking content to breaking widths.
Locally.
=> feat(core): add a min width to body

.changeset/ten-shoes-work.md, core/components/header/index.tsx, core/components/store-logo/index.tsx, core/components/ui/navigation-menu/navigation-menu.tsx
Fix overflow and truncate text if title is too long. Remove search icon when viewport is very small to prevent truncation.
=> fix(core): header overflow in mobile widths, remove search when small

.changeset/nervous-dancers-kick.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/https.ts
Adds a default set of Channel Menus to the newly created storefront channel.
Currently, no channel menus are created by the CLI when it creates a new Catalyst channel, which leads to a lower quality experience for BigCommerce merchants unfamiliar with the ability to create channel menus. If we create channel menus for them, they'll be able to configure settings, notifications, etc. for their new storefront channel.
> [!NOTE]
> The `social` channel menu is included in the POST request, but it will not show up in Channel Manager unless the merchant has MSF enabled on their store
Locally built and ran the CLI, opted to create a new channel, checked created channel in Channel Manager:
=> feat(cli): create channel menus for new catalyst channels

.changeset/tame-walls-itch.md, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/maintenance/page.tsx, core/app/[locale]/not-found.tsx, core/app/notifications.tsx, core/components/quick-search/index.tsx, core/components/ui/carousel/carousel.tsx, core/components/ui/footer/footer.tsx, core/components/ui/navigation-menu/navigation-menu.tsx
Sets mobile paddings to `16px` instead of `24px`.
https://github.com/bigcommerce/catalyst/assets/196129/9e810b80-acd2-49cf-8af7-ffe492e54cd6
Locally.
=> fix(core): set mobile padding to 16px

.changeset/happy-eggs-buy.md, core/app/[locale]/(default)/account/[tab]/_actions/submit-customer-change-password-form.ts, core/app/[locale]/(default)/account/[tab]/_components/addresses-content.tsx, core/app/[locale]/(default)/account/[tab]/_components/change-password-form.tsx, core/app/[locale]/(default)/account/[tab]/_components/settings-content.tsx, core/app/[locale]/(default)/account/[tab]/_components/tab-heading.tsx, core/app/[locale]/(default)/account/[tab]/page.tsx, core/client/mutations/submit-change-password.ts, core/client/mutations/submit-customer-change-password.ts, core/messages/en.json
This PR adds functionality for changed password if Customer is logged in. 
Account settings form is a placehodler. Will be updated in separate PR.
locally
=> feat(core): add customer change password for logged-in customer

.changeset/violet-swans-suffer.md, core/app/[locale]/(default)/(faceted)/_components/facets.tsx, core/app/[locale]/(default)/(faceted)/_components/refine-by.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts
According to our gql schema, category pages should use `categoryEntityId` filter instead of `categoryEntityIds`.
Introduced a new `categoryIn` filter for non-category pages and `category` now accepts a single category.
=> fix(core): use categoryEntityId filter on category PLP

.github/dependabot.yml
Bump dependabot's PR limit from `5 (default)` ->  `10`
=> chore(ci): bump dependabot pr limit

core/tests/ui/desktop/core/components/radio-group.spec.ts, core/tests/ui/desktop/core/components/swatch.spec.ts, core/tests/ui/desktop/e2e/product.spec.ts, core/tests/ui/mobile/checkout-experience.spec.ts
A few tests broke after https://github.com/bigcommerce/catalyst/pull/880
=> fix(tests): accommodate recent category changes

.github/dependabot.yml, .github/workflows/playwright-visual-regression.yml, docs/monorepo.md, turbo.json
Updates the documentation to have the latest information around visual regression testing and the removal of storybook references.
=> docs: update monorepo docs and cleanup storybook references

.changeset/four-cups-double.md, core/app/[locale]/(default)/cart/_components/cart-item.tsx, core/app/[locale]/(default)/cart/_components/item-quantity/index.tsx, core/app/[locale]/(default)/cart/_components/remove-from-cart-button.tsx, core/messages/en.json
Modified cart page layout to better account for mobile viewport.
Locally.
=> fix(core): modify cart page layout for mobile view

.changeset/nasty-news-retire.md, core/app/[locale]/(default)/login/page.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/login.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/register-customer.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/password.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist-or-text.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/shared/field-wrapper.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/text.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/app/[locale]/(default)/login/register-customer/page-data.ts, core/app/[locale]/(default)/login/register-customer/page.tsx, core/client/mutations/register-customer.ts, core/components/ui/form/form.tsx, core/messages/en.json
This pr adds Register Customer Page with Built In Fields
Locally
=> feat(core): create register customer page

.github/dependabot.yml
Ignore `next` and sibling packages (eslint next config, etc). We are planning on manually bumping those.
=> chore(ci): exclude next from dependabot updates

core/components/pricing/index.tsx
Fixes error in quick search.
Locally.
Pricing component works in various places like PDP, PLP, compare and quick search.
=> fix(core): adjust Pricing component localization in order to be used as client and server component

.changeset/grumpy-rice-bake.md, core/app/[locale]/(default)/(faceted)/_components/pagination.tsx, core/app/[locale]/(default)/account/[tab]/_actions/delete-address.ts, core/app/[locale]/(default)/account/[tab]/_components/account-status-provider.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-list.tsx, core/app/[locale]/(default)/account/[tab]/_components/modal.tsx, core/app/[locale]/(default)/account/[tab]/layout.tsx, core/app/[locale]/(default)/account/[tab]/page.tsx, core/messages/en.json
This PR  brings `delete` address functionality for Account.
locally
=> feat(core): add delete address functionality for account

.changeset/small-ducks-wink.md, core/components/ui/navigation-menu/navigation-menu.tsx, core/tests/ui/desktop/e2e/account.spec.ts
Account dropdown menu is not visible with current classes, fixed this by making overflow-y visible.
=> fix(core): overflow issue with account dropdown in header

.changeset/small-eagles-switch.md, core/components/ui/button/button.tsx
Change in #916 broke Slot because Slot needs a single React child, plus it was Slotting in the span instead of the Children as expected.
This fixes specifically the scenario of a Link slotting as a Button.
Locally.
=> fix(core): broken Slot functionality in Button

core/.eslintrc.cjs
Fixes ESLint resolution error in scaffolded projects. Note, the eslint-disable-next-line is needed for scaffolded projects.
Locally:
=> fix: eslint config resolution in core

.changeset/hot-starfishes-join.md, packages/create-catalyst/src/commands/create.ts
Since the `core` folder is running with the same ESLint config as scaffolded projects, we no longer need to run the `lint` task as part of the `create-catalyst` `create` command
Remove lint step in CLI locally and test against `--gh-ref=main`
=> refactor: remove unnecessary lint command from cli

.changeset/curvy-items-cheat.md, core/app/[locale]/(default)/cart/_components/cart-item.tsx
Fixes issue of showing an item as on sale when quantity was 2 or above.
`extendedListPrice` and `extendedSalePrice` account for quantity, but `originalPrice` doesn't. With this change I compare `originalPrice` to `listPrice`, and multiple original Price accordingly.
Before:
After:
Locally.
=> fix(core): show correct base price when sale is active in Cart

.changeset/breezy-beers-listen.md, packages/create-catalyst/bin/index.cjs, packages/create-catalyst/package.json, packages/create-catalyst/src/index.ts
> [!NOTE]
> ~This PR stacks on #935~ ✅ **Merged**
There were some reports of users not receiving a helpful error message when attempting to run the CLI with a Node version <12. While <12 versions of Node became EOL back in 2021 and earlier, there is still a chance that someone is accidentally using an early version of Node when trying to run the CLI, and we should help guide them. 
The error thrown looked like:
```
$ node packages/create-catalyst/dist/index.js
/Users/matt.volk/code/catalyst/packages/create-catalyst/dist/index.js:55
import { program } from "@commander-js/extra-typings";
^
SyntaxError: Unexpected token {
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load …
```
=> refactor: better node version check

.changeset/stupid-hairs-clean.md, core/app/[locale]/(default)/account/page.tsx
This PR fixes icons border width on the Account Page
locally
before:
after:
[BCTHEME-1846]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(core): update icons on the account page

core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts
Customer ID was not being passed to the request to get a checkout URL. As a result, there was a server error when checking out while logged in. This fixes that.
In the future, this request will return a customer-specific checkout URL, but for now it returns a guest checkout URL. This approach should automatically work in the future when the underlying URL is updated.
Locally tested both logged-in checkout and guest checkout.
=> Pass customer ID when requesting checkout URL

.changeset/cuddly-dolphins-sparkle.md, core/app/[locale]/(default)/cart/_components/shipping-info/index.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist-or-text.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist.tsx, core/components/ui/select/select.tsx
This fixes a side effect of #757, by adding a fixed heigh the Select as popper works as it should, allowing scrolling and properly rendering under the trigger.
Locally.
=> fix(core): make Select scrollable with popper positioning

.changeset/rare-bees-beg.md, core/app/[locale]/(default)/[...rest]/page.tsx, core/tests/ui/desktop/e2e/404.spec.ts
Fixes an issue with our custom 404 page not being used.
CI
Closes: https://github.com/bigcommerce/catalyst/issues/956
=> fix(core): custom 404 page not rendering

package.json, pnpm-lock.yaml
Updates pnpm to the latest version. This new version updates the lockfile version which has better support for git conflicts. Otherwise it's just a bunch of node version deprecations.
See CI
=> chore: bump pnpm to latest version

.changeset/hip-hornets-jump.md, core/app/[locale]/(default)/cart/_components/remove-from-cart-button.tsx
Hover state wasn't being overriden with the desired color.
Locally.
=> fix(core): hover text when remove product button is loading

.changeset/wet-tigers-bow.md, core/app/[locale]/(default)/cart/_components/coupon-code/index.tsx, core/messages/en.json
Noticed it had no loading state.
Locally.
=> feat(core): add loading state to remove coupon code button

core/tests/ui/desktop/e2e/checkout.spec.ts, core/tests/ui/desktop/e2e/shipping.spec.ts
Add a test to verify that shipping information is persisted when cart items are modified but shipping estimates need to be recalculated.
Verified the test locally. CI runs with the new test.
=> feat(functional): Add test for shipping estimation recalculation

.changeset/small-oranges-return.md, core/lib/kv/adapters/upstash.ts, core/lib/kv/index.ts, core/package.json, pnpm-lock.yaml
Add Upstash kv adapter using `@upstash/redis`.
Created an upstash db and was able to add entries to it.
=> feat(core): add upstash kv adapter

.changeset/lovely-adults-learn.md, .gitignore, core/.gitignore, core/client/graphql.ts, core/scripts/generate.cjs, core/tsconfig.json
This PR introduces changes that address the following concerns:
- Tracking GraphQL schemas in version control
- Consistent naming conventions for files related to GraphQL
- More helpful error messaging when generating GraphQL introspection files
A common pattern I'm seeing when integrating Catalyst with various third party services is that some third party services may have their own GraphQL API's that Catalyst needs to interface with; in these cases, I've been leveraging the [Multi-schema mode feature](https://gql-tada.0no.co/guides/multiple-schemas) of `gql.tada`. 
The moment that a second schema is added to a Catalyst project, the `schema.graphql` and `graphql-env.d.ts` file naming conventions become less useful, as the file names do not easily describe the provider from which the …
=> feat: quality of life improvements for graphql file generation

core/components/hero/index.tsx
Add a base64 LQIP for the default carousel image; improves first page load perceptual performance and also the experience when first using Catalyst with cold CDN image caches.
https://catalyst-horlf38ed-bigcommerce-platform.vercel.app/
Slow 3g example:
https://github.com/bigcommerce/catalyst/assets/8922457/5f935c4e-e827-4ebc-8bfa-45a570b4563e
=> Add blurDataURL to default carousel image

.changeset/heavy-otters-tell.md, core/client/mutations/create-wishlist.ts
This pr adds create wishlist mutation for customer account
Locally
=> Create wishlist mutation

core/lib/kv/adapters/bc.ts, core/lib/kv/adapters/memory.ts, core/lib/kv/adapters/upstash.ts, core/lib/kv/adapters/vercel.ts, core/lib/kv/index.ts, core/lib/kv/types.ts
This PR adds an in-memory cache for all kv adapters. Should help reduce number of reads to remote KVs and improve performance.
=> feat(core): cache all kv adapters with in-memory kv

.changeset/odd-berries-play.md, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-book.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/modal.tsx
This pr has changes for account modal:
- functional - props and update
- visual - tablet and desktop design updates
Locally
=> feat(core): update customer account modal component

.changeset/healthy-cycles-visit.md, core/app/[locale]/(default)/account/[tab]/_components/account-status-provider.tsx, core/app/[locale]/(default)/login/_components/change-password-form.tsx, core/app/[locale]/(default)/login/_components/login-form.tsx, core/app/[locale]/(default)/login/_components/reset-password-form/index.tsx, core/app/[locale]/(default)/login/layout.tsx, core/messages/en.json
This PR fixes the flow of redirecting users to the Login Page after changing the password
locally
**before:**
https://github.com/bigcommerce/catalyst/assets/82589781/636fcd57-79ff-42a3-95b4-f7abbe559251
https://github.com/bigcommerce/catalyst/assets/82589781/8212c532-90e2-42bf-8e09-97735e668c06
**after:**
https://github.com/bigcommerce/catalyst/assets/82589781/f46f3a41-1a8f-4b0f-a907-2a0b384ac425
https://github.com/bigcommerce/catalyst/assets/82589781/475c7df3-ec6e-484d-9189-c67b742e3678
=> fix(core): user is not redirected to Login page after requesting password reset link

core/app/[locale]/(default)/product/[slug]/_components/warranty.tsx
This pull request addresses an issue with the incorrect translation key used for the warranty section on product pages. The current code utilizes the key `Product.Details`, which results in displaying "Product.Details.warranty" on the product page instead of the correct translation.
=> Correct translation key for Warranty in Product Details

core/app/[locale]/(default)/(faceted)/_components/facets.tsx, core/app/[locale]/(default)/(faceted)/_components/refine-by.tsx, core/app/[locale]/(default)/(faceted)/_components/sort-by.tsx, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx
Added a css pulse animation when adding/removing facets. This provides users with visual feedback, indicating that an action is in progress, similar to a loading spinner.
Using the preview, click around Categories / Brands / Search pages, pulse animation while adding faces.
=> feat: add loading animations to PLP pages

.changeset/mighty-bottles-shave.md, core/components/product-form/fields/multiple-choice-field/index.tsx
On product option hover -> prefetch PDP data. This change makes the UX better at the cost of a few more requests.
This change was only required on multiple choice options, are these are the only ones changing the url.
Inspect network tab while hovering on product options.
=> feat: prefetch product option on hover

.changeset/selfish-hairs-sit.md, packages/client/src/client.ts
- Add optional channelId param to client to allow fetching from multiple channels with the same client.
- Remove non channel-aware endpoint.
- Enforce channelId being used.
TBD
=> feat(client): add channelId as an optional param

.changeset/afraid-experts-fold.md, core/app/[locale]/(default)/account/[tab]/_actions/add-address.ts, core/app/[locale]/(default)/account/[tab]/_actions/update-address.ts, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/customer-edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/numbers-only.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/parse-fields.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/utils.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/client/fragments/form-fields-values.ts, core/client/queries/get-customer-addresses.ts, core/messages/en.json, core/tests/ui/desktop/core/components/accordion.spec.ts, core/tests/ui/desktop/e2e/checkout.spec.ts
This PR adds brings first of custom fields to `Account` forms - `NumberFormField`
locally
=> feat(core): add numbers-only field & utils for account form fields

.changeset/five-emus-brush.md, .changeset/smooth-trains-watch.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/static/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/static/page.tsx, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/(default)/page.tsx, core/app/[locale]/(default)/product/[slug]/static/page.tsx, core/app/api/cart-quantity/route.ts, core/app/api/product/[id]/route.ts, core/channels.config.ts, core/client/index.ts, core/client/queries/get-cart.ts, core/client/queries/get-route.ts, core/client/queries/get-store-status.ts, core/components/header/cart-icon.tsx, core/components/product-sheet/product-sheet-content.tsx, core/middlewares/with-routes.ts, packages/client/src/client.ts
Add channel <=> locale config example.
Make client.fetch channel aware by fetching channel id assigned to locale.
Fetch from default channel if no map is found.
Locally, it requests per channel configured.
=> feat(core): make fetch channel aware per locale

core/app/[locale]/(default)/product/[slug]/page-data.ts, core/app/[locale]/(default)/product/[slug]/page.tsx
First pass on default options selection fix. This PR applies the default options overlay for the query done in the PDP page. When no product options are selected on page load (no query params) the overlay is applied.
1. Set default product options on a product
2. Navigate to the product's PDP page
3. Product options should be selected and the correct image / sku are displayed.
=> fix: pre selected options on PDP page

.changeset/gentle-boxes-tease.md, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/_actions/update-customer.ts, core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/fields/text.tsx, core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/index.tsx, core/app/[locale]/(default)/account/[tab]/page-data.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/date.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/text.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/client/mutations/update-customer.ts, core/components/ui/date-picker/date-picker.tsx
This PR adds brings `DatesFormField` for Address & Account forms.
Locally
=> feat(core): add dates field for account & addresses forms

.changeset/real-ladybugs-complain.md, core/app/robots.ts, core/app/robots.txt, core/app/sitemap.xml/route.ts, core/app/xmlsitemap.php/route.ts, core/middleware.ts
Adds a new sitemap route on /sitemap.xml which proxies to the upstream hosted sitemap on the BigCommerce server.
For users who wish to use 100% of BigCommerce's URL capabilities, this is a complete sitemap.
In the future, we may iterate on this to generate the sitemap in code, using this BC sitemap data as an input but allowing the output to be customized in code.
Awaiting a server-side change before E2E testing.
=> Add sitemap index on /sitemap.xml

core/app/[locale]/layout.tsx
It's better to return empty strings than bad defaults for this meta information, so I'm removing these generic references to Catalyst in favor of empty strings.
For the case of the page title - stores will generally have a Store Name set (it's part of the trial form), so the case that this fails to return something is very unlikely.
In the case of meta description, we will update the API to return this information and update this file once again when that's ready. It can be specified manually by end users until that time (and it already pulls from the API on most entity pages like products, etc).
Preview URL
=> Remove generic defaults for meta information

.changeset/lovely-hotels-juggle.md, core/lib/kv/index.ts, core/lib/kv/keys.ts, core/middlewares/with-routes.ts
We need for kv keys to be channel aware when using multiple locales.
Locally each locale/channel has its own kv pairs.
=> feat(core): append channel to kv key to make it channel aware

.changeset/giant-carrots-peel.md, core/app/robots.ts
Uses the deployment URL for robots.txt.
https://catalyst-latest-git-fix-robots-bigcommerce-platform.vercel.app/robots.txt
=> fix: use system environment variables for robots

core/app/[locale]/(default)/account/[tab]/_actions/submit-customer-change-password-form.ts, core/app/[locale]/(default)/account/[tab]/_components/change-password-form.tsx, core/client/mutations/submit-change-password.ts
Due to recent changes, change password form was erroring out because it's a client component importing a schema from a file with a our `client` defined within and it would throw an error because it can't read from `env` file.
This fixes the issue by moving around the schema definitions so that it doesn't clash when importing in a client component.
Locally it doesn't error.
=> fix(core): issue with imports in change password form

.changeset/green-keys-tickle.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/init.ts, packages/create-catalyst/src/utils/https.ts
Switch the `create-catalyst` CLI to generate multi-channel GraphQL tokens so that a given catalyst storefront can serve multiple channels
Manually by @matthewvolk
=> Switch CLI to generate multi-channel tokens

.changeset/empty-students-scream.md, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/index.tsx
The PR adds changes to address form layout like:
- gap between form elements reduced to `gap-y-3`
- removing top margin on heading;
locally
=> fix(core): add minor changes to address form layout

.changeset/grumpy-buttons-tan.md, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-field-handlers.ts, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/update-settings-form/index.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/register-customer.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/index.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/picklist.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/radio-buttons.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/fields/utils.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/components/ui/date-picker/date-picker.tsx
This PR adds `RadioButtons` and `Picklist` Fields (multipleChoises) for Address & Account forms.
locally
https://github.com/bigcommerce/catalyst/assets/67792608/952d86fe-928f-4b61-b6b8-ecd729ef8004
=> feat(core): add multipleChoices field(radio-buttons, picklist) for account & address forms

.changeset/selfish-insects-rule.md, core/client/mutations/update-customer.ts
Looks like a new field for errors was added to the API for the updated customer mutation. This PR fixes by adding that field fragment to the query.
See the broken build: https://github.com/bigcommerce/catalyst/actions/runs/9935948451/job/27443143789
See CI.
=> fix(core): adds missing error field on update customer mutation

docs/monorepo.md
Updates the monorepo documentation repo to point to the right components directory.
Fixes #1096 
N/A
=> chore(docs): update link in monorepo documentation

.changeset/afraid-coats-play.md, core/app/sitemap.xml/route.ts, packages/client/src/client.ts
Moves sitemap index fetching into the client so it gets the benefits of everything the client offers (such as user agent), as well as making the client more useful within other systems who may also wish to use a sitemap.
I fixed some missing user agents on admin API requests while I was at it and also fixed hardcoded hostnames.
Preview build + server logs
=> Move sitemap fetching into the client

.changeset/soft-moles-judge.md, core/app/[locale]/(default)/account/[tab]/_components/account-status-provider.tsx, core/app/[locale]/(default)/account/[tab]/_components/account-tabs.tsx
This PR makes selected account tab visible for user by default on Mobile devices even after reloading the page.
locally
**before:**
https://github.com/bigcommerce/catalyst/assets/82589781/dc82a192-ef8c-4131-ab55-9e60381590e5
**after:**
https://github.com/bigcommerce/catalyst/assets/82589781/25e83dce-6b51-43b5-b67f-691a10b68328
=> fix(core): make selected account tab visible for user by default on mobile devices

core/app/[locale]/(default)/(faceted)/_components/refine-by.tsx, core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/components/ui/tag/tag.tsx
Refactor `Tag` + usages
https://github.com/user-attachments/assets/a7e8634e-7e0d-4ab5-877b-97cc669f58d9
=> refactor: tag + usages

core/app/[locale]/(default)/product/[slug]/_components/gallery/index.tsx, core/components/ui/gallery/gallery.tsx
https://github.com/user-attachments/assets/9f7615cf-e7a1-477a-b8b8-ab2c16f9f061
=> refactor: gallery component

core/components/ui/message/message.tsx
Refactors message component, removes `cva` and `forwardRef`
=> refactor: message component

core/components/header/cart-icon.tsx, core/components/ui/badge/badge.tsx
Badge's API should accept `children` so we don't need to manually type `string`, `number`, etc.
N/A
=> refactor: badge takes children

core/components/ui/counter/counter.tsx
=> refactor: counter

.changeset/bright-shirts-sort.md, core/auth.ts, core/client/mutations/login.ts
Adds some customer information onto the session in case we want to consume that information. This also refactors a bit of the code to add information onto the JWT.  This is to provide a better way to add the `customerAccessToken` onto the JWT and session later. This is achieved by [extending the session](https://authjs.dev/guides/extending-the-session) and by using [module augmentation](https://authjs.dev/getting-started/typescript#module-augmentation) via Typescript to get the right types.
Logged in locally.
=> feat(core): add customer information onto the session

core/tests/ui/desktop/e2e/register.spec.ts
Make sure the password length and requirements are correctly met for the faker generated password used to register a test customer.
Here's what the failed attempt test was using for password to register the customer(it did not contain numerics)
Local tests and tests on this job.
=> fix(functional): Update register spec password required

core/lib/content-security-policy.js, core/next.config.js, core/package.json, pnpm-lock.yaml
Improve CSP generation logic and add logic to support framing by the Makeswift builder _if_ a Makeswift API key is present otherwise block framing.
Next step will be to use the CSP policy specified in the control panel as a starting point; this will be a future PR.
While I was at it, I extracted CSP generation and implemented https://www.npmjs.com/package/content-security-policy-builder which is a lightweight and very popular library for building CSPs.
Tested locally
=> Extract content-security-policy generation logic, add support for Makeswift builder

core/.env.example, core/app/api/makeswift/[...makeswift]/route.ts, core/lib/makeswift/client.ts
So we can point Catalyst to Makeswift's staging environment
Add
```
MAKESWIFT_API_ORIGIN=https://api.staging.makeswift.com
MAKESWIFT_APP_ORIGIN=https://app.staging.makeswift.com
```
to your staging environment
=> Add makeswift env vars

core/components/product-sheet/index.tsx, core/components/ui/sheet/sheet.tsx
Remove `transparentOverlay` and Overlay in Sheet since we don't use it.
Locally.
=> fix: remove transparent overlay prop in Sheet

core/lib/content-security-policy.js
Removes the `formAction` CSP header as it causes React Server Actions to fail if they have a redirect, e.g. our search action. In order to add this back, you'd need to add in either the production URL and/or localhost in order for it to work correctly. I want us to create a utility function for fetching the right URL as we've been doing it in a few places now. Can add this back in later when that comes into fruition.
See the automated tests.
=> fix: remove formAction CSP header

.changeset/brown-glasses-enjoy.md, core/app/[locale]/(default)/login/_actions/submit-login-form.ts, core/app/[locale]/(default)/login/_components/login-form.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/login.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/playwright.config.ts, core/tests/ui/desktop/e2e/account.spec.ts, core/tests/ui/desktop/e2e/register.spec.ts
`next-auth` does not follow the `trailingSlash` configuration so we want to use the redirect from `next/navigation` to handle it. This was causing our functional test suite to be "flaky".
See functional test runs.
=> fix(core): redirect using next/navigation instead of next-auth

core/tests/ui/desktop/e2e/cart.spec.ts
Waits for the checkout url to load before expecting on the test. This should help ensure the test can run on slower connections.
See CI.
=> test(core): wait for checkout url to load

.changeset/many-ravens-switch.md, core/components/product-card/index.tsx, core/components/ui/product-card/product-card.tsx
Renaming `brand` to a more generic `subtitle` prop.
Locally.
=> chore: rename brand prop to subtitle in Product Card

core/app/[locale]/(default)/cart/_components/cart-item.tsx
Update cart image to use the new resizeable image node instead of the deprecated imageUrl static image.
=> Use resizeable image on cart image

.changeset/lovely-falcons-hear.md, core/components/ui/pick-list/pick-list.tsx, core/components/ui/radio-group/radio-group.tsx, core/components/ui/rectangle-list/rectangle-list.tsx, core/components/ui/select/select.tsx, core/components/ui/swatch/swatch.tsx
Fixes issue with duplicate keys by setting key before spreading props. This seems to be a NextJS issue, where key is removed if used after spreading props.
Locally no longer see duplicate keys messages.
=> fix(core): issue with keys in form components

.changeset/quick-trees-cry.md, core/components/quick-search/index.tsx
Similar to #1198, add missing `Title` component and set `aria-describedby` to `undefined`.
Locally no warnings.
=> fix(core): add missing accessibility components to quick search

.changeset/nine-flowers-matter.md, core/components/hero/index.tsx, core/components/ui/slide/index.ts, core/components/ui/slide/slide.tsx
Add `Slide` component to be used in Slideshow.
Locally it works the same.
=> feat(core): add Slide component

.changeset/fast-forks-juggle.md, core/next.config.js, core/package.json, pnpm-lock.yaml
Limit the number of chunks Webpack produces to a default of 5 to strike a balance between performance and total requests.
Can be customized via env variable.
We've noticed that the first limit you hit when hosting a Catalyst storefront on Vercel is Edge Requests, and the biggest contributing factor to that is the numerous chunked JS files. Putting a limit on this makes Catalyst less expensive to operate on Vercel and allows for more page views to fit within the limits of a Vercel plan before incurring overages.
Preview deployment + lighthouse
=> Default webpack chunk limit of 5, env variable to customize

.changeset/early-fishes-tell.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/page-data.ts, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/brand/[slug]/static/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page-data.ts, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/static/page.tsx, core/app/[locale]/(default)/blog/[blogId]/page-data.ts, core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/app/[locale]/(default)/blog/page-data.ts, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/webpages/contact/[id]/page.tsx, core/app/[locale]/(default)/webpages/normal/[id]/page.tsx, core/app/[locale]/layout.tsx
- Take advantage of the new `seo` field on `site.settings` to set default metadata on the layout level. This metadata will be used, if specified in the channel settings, to set the page title, meta description, and meta keywords on any pages that do not specify more specific values.
- Normalize/standardize how we set up SEO metadata across page entity types for consistency
- Fix a bug where `generateMetadata` was not exported on our static pages for categories and brands
Manually/locally tested different scenarios with/without store settings and page-local settings.
=> SEO improvements

.changeset/plenty-news-smoke.md, core/app/[locale]/(default)/(faceted)/_components/facets.tsx, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/product/[slug]/_components/review-summary.tsx, core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx, core/components/product-sheet/product-sheet-content.tsx, core/components/ui/rating/rating.tsx
We only need a rating and size prop.
Locally it all looks the same.
=> refactor(core): change value prop to rating in Rating

.changeset/gentle-experts-do.md, core/tailwind.config.js
https://github.com/vercel/next.js/issues/37825#issuecomment-1633364694
Our build time was spending over 60 seconds on `Creating an optimized production build...` so I tried removing the `node_modules` folder from the `content` in tailwind config, and I see much faster build times now.
Preview build
Before:
After:
=> Speed up builds by excluding node_modules from tailwind config

core/components/ui/slideshow/slideshow.tsx
Since slideshow handles its own ref internally, and we do not use a ref passed from props, we can use `ComponentPropsWithoutRef` when defining the props for slideshow. This also makes it easier to register in Makeswift.
N/A
=> fix: type for slideshow should not include ref

.changeset/angry-seas-march.md, packages/create-catalyst/src/commands/integration.ts, packages/create-catalyst/src/index.ts
Adds a command to the `create-catalyst` CLI that can be executed by running `[npm|pnpm|yarn] create @bigcommerce/catalyst@latest integration` once published. Also updates the `packages/create-catalyst/README.md` with some documentation that partners interested in developing integrations can follow.
When you execute this new command following the steps below, the command will create a folder with two new files:
* `integration.patch`
* `manifest.json` 
The expectation is that the folder containing these two files will be committed to a branch, and that branch will then be used to open a PR into `bigcommerce/catalyst:main`. Once merged, the `pnpm create @bigcommerce/catalyst@latest create` CLI will then be able to accept an argument for which integration you want to scaffold your Catalyst …
=> feat: command to help generate integration patches

.changeset/hip-eels-push.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/apply-integration.ts, packages/create-catalyst/src/utils/apply-integrations.ts
The second half of #1192 - the functionality in this PR is optionally invoked at the end of the `create` command, and will apply a single integration using the `integration.patch` + `manifest.json` files created by the `integration` command.
Clone https://github.com/bigcommerce/catalyst and run the following commands to test this command with the Makeswift integration:
1. `git fetch --all`
2. `git switch integrations/apply-patch`
3. `pnpm install`
4. Modify the ref that the function uses to retrieve the `.patch` file, by changing the following line inside of the `applyIntegration` function:
```diff
-    downloadTemplate(`github:bigcommerce/catalyst/integrations/${integration}#main`, {
+    downloadTemplate(`github:bigcommerce/catalyst/integrations/${integration}#integrations/makeswift-patc …
```
=> feat: optional flag to apply integrations during create

.changeset/modern-elephants-shake.md, core/components/breadcrumbs/index.tsx, core/components/ui/breadcrumbs/breadcrumbs.tsx, core/components/ui/breadcrumbs/index.ts
Turns out, we actually need this ui component.
Locally.
=> feat(core): add Breadcrumbs component

.github/workflows/regression-tests.yml
Send notifications to slack team channel with the necessary information to alert any job failures. When a job from the regression tests workflow fails, this step will send a message with failure notification and the pull request associated with the workflow which caused the failure.
For this to work, I've added a slack workflow which provides a webhook. It accepts the payload we send as part of this step on failure and dispatches the message to the configured slack channel.
Tested by sending messages to channel.
=> feat(functional): Send gh workflow results to slack

.changeset/plenty-impalas-jog.md, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/integration.ts, pnpm-lock.yaml
Parse environment variable diff using `dotenv.parse` instead of custom regex expression
`pnpm dev && node ./packages/create-catalyst/dist/index.js integration name`
=> refactor(cli): parse env using dotenv

.changeset/tough-cycles-sell.md, packages/create-catalyst/src/commands/integration.ts, packages/create-catalyst/src/utils/apply-integration.ts
Mistakenly, the `applyIntegrations` utility function was not updated to reflect the new shape of the integration `manifest.json` file, so it failed during consumption. This PR defines a single Manifest schema with `zod` and uses it as a single source of truth for all references to manifest throughout the CLI.
Testing built CLI:
https://github.com/user-attachments/assets/567eb4be-e89b-46d4-a117-071e36cd3cc4
=> fix(cli): single source of truth for manifest schema

.github/workflows/regression-tests.yml
Add environment details to slack message to distinguish between the releases. Along with it, I updated the script to rely on `actions/github-script` to fetch the pull request information.
=> fix(functional): Add environment details to message

.github/workflows/regression-tests.yml
It looks like `find_pull_request` on lighthouse audit workflow doesn't finish and make the output available before the next step(`comment_to_pr`) is looking for the result. Moving the step to a few steps above to make the output readily available should fix the failing workflow due to this.
CI results.
=> fix(chore): Fetch pull request details at the start

.github/workflows/regression-tests.yml
Github `action-script` is unreliable when trying to fetch pull request data and thus we are going back to using the previous ways to grab the information we needed. 
Tests as part of CI.
=> fix(chore): Fetch pull request data

.github/workflows/pull-request-data.js, .github/workflows/regression-tests.yml
We want to send notifications on test runs only for open pull requests to cut down the nosie from draft pr's.
**Notifications are sent for a pull request in open state**
**Notifications are skipped for a pull request in draft state**
=> chore(functional): Send notifications only on open pr

docs/security.md
Adding answers to some of our common security questions from customers, so we have a public doc to reference re: Catalyst in the future.
Tested the .md file within the docs site to ensure it parsed.
=> Add initial security docs

.changeset/stale-deers-relate.md, core/next.config.js
Adds a `Link` header to preconnect to `cdn11.bigcommerce.com` to improve load time for images for first-time visitors.
https://www.webpagetest.org/result/240819_AiDcNC_E24/1/details/#waterfall_view_step1
=> Add link header to preconnect to CDN

.changeset/twelve-spiders-film.md, core/client/mutations/create-wishlist.ts
This pr simplifies _create wishlist mutation_. After implementation improvements we need only minor data set to return.
Also it contains changes for interface updates to be consistent with other wishlist mutations
Locally
=> feat(core): update create wishlist mutation

.changeset/giant-carpets-boil.md, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/add-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/address-book.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/edit-address.tsx, core/app/[locale]/(default)/account/[tab]/_components/addresses-content/index.tsx, core/app/[locale]/(default)/account/[tab]/layout.tsx, core/messages/en.json, core/tests/ui/desktop/e2e/account.spec.ts
This PR improves redirect behavior after adding a new address, namely, it adds a banner about the successful creation of a new address.
locally
**before:**
https://github.com/user-attachments/assets/58b6aff4-c7a2-43af-8455-8e356bdef625
**after:**
https://github.com/user-attachments/assets/69c71315-80fc-43bf-b8c5-4304ab114246
=> fix(core): improve redirect behavior after creating new address

.changeset/few-panthers-judge.md, core/app/[locale]/(default)/webpages/normal/[id]/page.tsx
Pages with non url safe ids causes to 404 response.
Page Data and PageMetadata request sends the urlencoded id strings. this cause no response. I checked the  Contact page but it already been fix
Example id: `Tm9ybWFsUGFnZToxMA==` and graphgl has the variable `{id:"Tm9ybWFsUGFnZToxMA%3D%3D"}`
Go to a page with nonurlsafe id
=> Fix: Decode Webpage Id to fix 404 on Webpages with nonsafe ids

.changeset/few-panthers-judge.md, core/app/[locale]/(default)/webpages/normal/[id]/page.tsx
OSS contribution from: https://github.com/bigcommerce/catalyst/pull/1301
=> fix: decode Webpage id to fix 404 on Webpages with nonsafe ids (#1301)

.changeset/odd-oranges-wonder.md, core/app/[locale]/(default)/account/[tab]/_components/create-wishlist-form/_actions/create-wishlist.ts, core/app/[locale]/(default)/account/[tab]/_components/create-wishlist-form/index.tsx, core/app/[locale]/(default)/account/[tab]/_components/wishlist-content/delete-wishlist-form/_actions/delete-wishlists.ts, core/app/[locale]/(default)/account/[tab]/_components/wishlist-content/delete-wishlist-form/index.tsx, core/app/[locale]/(default)/account/[tab]/_components/wishlist-content/index.tsx, core/app/[locale]/(default)/account/[tab]/_components/wishlist-content/wishlist-book.tsx, core/app/[locale]/(default)/account/[tab]/page-data.ts, core/app/[locale]/(default)/account/[tab]/page.tsx, core/app/[locale]/(default)/account/page-data.ts, core/app/[locale]/(default)/account/page.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/_actions/login.ts, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/components/ui/pagination/pagination.tsx, core/messages/en.json
This pr adds wish lists book for customer account. 
For now customer can:
- fetch existed wish lists
- create wish list
- delete wishlist
- paginate with wish lists pages
Locally
https://github.com/user-attachments/assets/4d203a82-4cc0-4651-b2cb-c907d6985f56
=> feat(core): add wishlist book

docs/index.md
Developers using `npm` instead of `pnpm` are often forgetting to add the NPM-required argument delimiter `--` when using the integrations CLI. More info: https://docs.npmjs.com/cli/v10/commands/npm-run-script#description
```bash
npm create @bigcommerce/catalyst@latest --integration=makeswift
```
does not work
```bash
npm create @bigcommerce/catalyst@latest -- --integration=makeswift
```
does work
=> docs: argument delimiter when using npm for integrations

integrations/wordpress-rest/integration.patch, integrations/wordpress-rest/manifest.json
Adds an option for WordPress into our new integration CLI model. It uses the WP REST API to fetch blog entries and tags to power the default blog routes.
Related dev branch: https://github.com/bigcommerce/catalyst/tree/integrations/wordpress-rest
Blog Index
Blog Post
=> Initial WordPress blog REST API integration

integrations/algolia/integration.patch, integrations/algolia/manifest.json
Adds an option for Algolia into our new integration CLI model. It swaps out the default quick search query to use Algolia, via their JS client.
Related dev branch: https://github.com/bigcommerce/catalyst/tree/integrations/algolia
Locally
=> Add optional Algolia integration for CLI

.changeset/proud-colts-relate.md, core/.env.example, core/client/revalidate-target.ts
Rename `NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET` to `DEFAULT_REVALIDATE_TARGET` since we don't need this exposed to the client.
Locally.
=> fix(core): rename DEFAULT_REVALIDATE_TARGET env variable

core/middleware.ts, core/middlewares/with-channel-id.ts, core/middlewares/with-intl.ts, core/middlewares/with-routes.ts
This PR splits the `with-routes` middleware into 3:
- with-intl
- with-channel-id
- with-routes
This simplifies `with-routes` and allows us to remove the `locale` var we were mutating/accessing all over the place.
=> refactor(middleware): split with-routes

.changeset/strange-cobras-impress.md, core/components/header/index.tsx, core/messages/ja.json, core/tests/ui/desktop/e2e/account.spec.ts
- Create add/delete Wishlist test
- Fix Wishlist naming in some places, since we agreed with Turner that "wishlist" is the correct one over the "wish list"
=> Add Wishlist test and update wishlist naming

.changeset/strong-terms-begin.md, core/app/[locale]/(default)/account/(tabs)/_components/account-notification.tsx, core/app/[locale]/(default)/account/(tabs)/_components/account-status-provider.tsx, core/app/[locale]/(default)/account/(tabs)/layout.tsx, core/app/[locale]/(default)/account/page.tsx, core/app/[locale]/(default)/login/_components/reset-password-form/index.tsx, core/app/[locale]/(default)/login/layout.tsx, core/app/[locale]/(default)/login/register-customer/_components/register-customer-form/index.tsx, core/app/providers.tsx, core/messages/en.json, core/tests/ui/desktop/e2e/register.spec.ts
This PR improves redirect behavior after creating account, namely, it adds a banner about the successful creation of an account.
locally
**before:**
https://github.com/user-attachments/assets/12aaf09a-fc0c-44f3-b69e-d1e93be43131
**after:**
https://github.com/user-attachments/assets/7ff7469d-44b1-431c-978e-f4279fff2221
=> fix(core): improve redirect behavior after creating account

core/app/[locale]/(default)/(faceted)/_components/sort-by.tsx
removes pagination cursors from search params when changing sort option
old cursors were sticking around in the url after changing sort which messed up pagination.
1. find a search with enough results for pagination
2. click through a few pages
3. change the sort option
4. it should reload on first page result of new sort selection & remove the cursors from params
------------------------------------
Extends from slack conversation in bigcommercedevs/#catalyst
=> fix: remove pagination cursors from search params on sort change

.changeset/healthy-cars-talk.md, core/middlewares/with-intl.ts
With the recent changes to our middleware, there is an issue when switching locales form the UI. `intlResponse.redirected` is false when status is 307 🤔
=> fix(core): resolve 500 server error on locale change

integrations/makeswift/integration.patch
Makeswift's default locale is `en-US`, while the default locale in Catalyst is just `en`. Because of this mismatch, Catalyst stores often fail to load in the Makeswift builder until the default locale in Makeswift or Catalyst is switched such that they match. 
In this PR, we just have Catalyst pass `null` when the locale is the default locale. This guarantees that no matter what the default locale is in Catalyst, it will get the page content for the default Makeswift locale.
Check out the branch this patch was generated from (https://github.com/bigcommerce/catalyst/tree/integrations/makeswift-locale-fix), run `pnpm i`, and then `pnpm dev`. Ensure you have a `MAKESWIFT_SITE_API_KEY` in your `.env.local`, and that the default Makeswift locale for the site key is `en-US`, and the default …
=> fix: use default makeswift locale in case of locale mismatch

core/next.config.js, core/package.json, pnpm-lock.yaml
Adds a new `build:analyze` command, I've been using it in my latest PRs to debug our middleware bundle.
=> chore(core): add bundle analyzer

packages/client/package.json, packages/client/src/utils/getOperationName.ts, packages/client/src/utils/normalizeQuery.ts, pnpm-lock.yaml
Change `graphql` for `@0no-co/graphql.web` in our client. This reduces the bundle size everywhere but mostly did it for our middleware:
=> chore(client): use graphl.web

.changeset/hot-buses-invent.md, core/components/ui/header/locale-switcher.tsx
Use link instead of form. Simplifies logic and behaves better.
Locally, it redirects to correct locale without use, even when always showing locale prefix.
=> fix(core): update localeSwitcher to use link instead of form

docs/internationalization.md, docs/localization.md
This PR adds the localization overview & guide back into the docs for [DEVDOCS-6062](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6062).
[PR 1298](https://github.com/bigcommerce/catalyst/pull/1298), where I originally added the localization overview & guide, was reverted in [PR 1306](https://github.com/bigcommerce/catalyst/pull/1306). The reason was that subdirectories aren't supported for the catalyst.dev repository (https://bigcommerce.slack.com/archives/C0740QWEF9R/p1724446019589669), so the docs would not appear in the navigation bar.
This PR adds the overview & guide back into the docs, but places them under the /docs directory (no subdirectories). 
See [PR 21](https://github.com/bigcommerce/catalyst.dev/pull/21) for new navigation bar changes. Must merge this PR before PR …
=> docs: add localization overview & guide

.changeset/rich-camels-bake.md, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/fragment.ts, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/index.tsx, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/update-wishlists-form/_actions/add-wishlist-items.ts, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/update-wishlists-form/_actions/delete-wishlist-items.ts, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/update-wishlists-form/index.tsx, core/app/[locale]/(default)/account/[tab]/_components/wishlist-sheet/wishlist-sheet-content.tsx, core/app/[locale]/(default)/product/[slug]/_components/details.tsx, core/app/[locale]/(default)/product/[slug]/page-data.ts, core/app/[locale]/(default)/product/[slug]/page.tsx, core/components/product-form/index.tsx, core/messages/en.json
This pr adds Wishlist Drawer for Catalyst (PDP)
This Drawer help the user to manage wishlists:
- creating new wishlist
- adding new item to wishlist
- deleting an item from wishlist
Locally
=> feat(core): add wishlist drawer

integrations/makeswift/integration.patch
Changes any `~/i18n` imports to `~/i18n/routing` appropriately. Sends `undefined` as locale value to Makeswift for default locale, so that by default any locale will work with Makeswift. Updates product carousel fragment location. Updates small changes in various component prop API keys.
Creating a local catalyst storefront and applying the Makeswift integration works locally after building the CLI.
=> feat: update for compatibility with @bigcommerce/catalyst-core@0.15.0

core/tests/ui/desktop/e2e/addresses.spec.ts
Runs the address tests in serial mode as it uses a logged in customer. When #1262 get's merged, logging a user out will invalidate the session in other parallel tests so we need to run them serially.
See CI for passing test runs.
=> test(core): run address tests in serial mode

.changeset/gentle-eyes-double.md, core/i18n/routing.ts
When using locale switcher with [locale prefix](https://next-intl-docs.vercel.app/docs/routing#shared-configuration) `never`, there is a caching issue that prevents the correct messages to show when navigating between pages. There is an [open issue](https://github.com/amannn/next-intl/issues/786) about this. 
This change sets locale prefix to `as-needed`, so locale prefix will only be shown if not using the default locale.
Correct messages are shown when locale switching without the need to hard refresh.
=> fix(core): change locale prefix to  to prevent caching issues

.changeset/small-sheep-divide.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/init.ts, packages/create-catalyst/src/utils/write-env.ts
A BigCommerce access token is no longer required to run Catalyst. If a merchant wants to use an access token, they should manually create one following: https://www.catalyst.dev/docs/environment-variables#bigcommerce_access_token
Built and ran `node packages/create-catalyst/bin/index.cjs` locally, checked `.env.local` in created project to confirm access token not present:
```shell
BIGCOMMERCE_STORE_HASH=storehash
BIGCOMMERCE_CHANNEL_ID=12345
BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN=eyJ...
AUTH_SECRET=e85b...
CLIENT_LOGGER=false
ENABLE_ADMIN_ROUTE=true
NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET=3600
```
=> fix: do not write access token to env file

.changeset/wise-games-try.md, .env.example, docs/environment-variables.md, packages/create-catalyst/src/utils/write-env.ts
> [!NOTE]
> Stacks on #1365 
Renames a few more references to `NEXT_PUBLIC_DEFAULT_REVLIDATE_TARGET` env var, missed in https://github.com/bigcommerce/catalyst/pull/1317
Search all repository files for `"NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET"`
=> fix: rename leftover references to NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET

.changeset/flat-tables-hang.md, core/app/[locale]/layout.tsx
If app is not running on Vercel's infra, `<Analytics />` and `<SpeedInsights />` are not rendered.
Opt-in to disable vercel analytics and speed insights by setting the following env vars to `true`
- `DISABLE_VERCEL_ANALYTICS`
- `DISABLE_VERCEL_SPEED_INSIGHTS`
=> feat: optionally disable Vercel's insights and analytics

.changeset/beige-clouds-whisper.md, core/.eslintrc.cjs, core/app/[locale]/(default)/(auth)/change-password/page.tsx, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/app/[locale]/(default)/(auth)/login/_components/login-form.tsx, core/app/[locale]/(default)/(auth)/register/_actions/login.ts, core/app/[locale]/(default)/(auth)/reset/_components/reset-password-form/index.tsx, core/app/[locale]/(default)/(faceted)/_components/facets.tsx, core/app/[locale]/(default)/(faceted)/_components/refine-by.tsx, core/app/[locale]/(default)/(faceted)/_components/sort-by.tsx, core/app/[locale]/(default)/account/(tabs)/_components/account-status-provider.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/add/_components/add-address-form.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/edit/[slug]/_components/edit-address-form.tsx, core/app/[locale]/(default)/account/layout.tsx, core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts, core/app/[locale]/(default)/product/[slug]/_components/product-form/fields/multiple-choice-field/index.tsx, core/app/admin/route.ts, core/app/xmlsitemap.php/route.ts, core/components/header/_actions/logout.ts, core/components/ui/pagination/pagination.tsx, core/i18n/routing.ts, core/tests/ui/desktop/e2e/login.spec.ts, core/tests/ui/desktop/e2e/register.spec.ts
Noticed we were not using next-intl's wrapper navigation APIs.
- Added eslint rule to enforce use of these APIs.
- Fixed issues.
Locally, behaves the same.
=> chore(core): enforce use of next-intl's navigation APIs

.changeset/strong-penguins-rescue.md, core/app/[locale]/(default)/(auth)/change-password/page.tsx, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/(auth)/register/page.tsx, core/app/[locale]/(default)/(auth)/reset/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/add/page.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/edit/[slug]/page.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/page.tsx, core/app/[locale]/(default)/account/(tabs)/settings/change-password/page.tsx, core/app/[locale]/(default)/account/(tabs)/settings/page.tsx, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/cart/page.tsx, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/error.tsx, core/app/[locale]/maintenance/page.tsx, core/app/[locale]/not-found.tsx, core/app/[locale]/store-selector/page.tsx, core/messages/en.json
- Localize metadata titles.
- NotFound and Error don't support metadatas, so removed from pages.
Locally.
=> feat(core): localize metadata titles

.changeset/tidy-coats-press.md, core/app/favicon.ico/route.ts, core/client/index.ts
Pass in default channel to favicon query, since `getLocale` can't be used in routes.
Locally, I no longer see the console error.
=> fix(core): manually pass in channel id for get favicon query

.changeset/clever-fans-tickle.md, core/tests/fixtures/utils/account/account.ts, core/tests/ui/e2e/account.spec.ts, core/tests/ui/e2e/login.spec.ts
Fixes tests looking for url without prepending locale. Due to recent changes, we need to prepend locale for certain redirects. More info: https://github.com/bigcommerce/catalyst/pull/1361
Locally.
=> fix(core): prepend locale for redirected urls in tests

.changeset/heavy-toes-own.md, core/app/[locale]/(default)/account/page.tsx, core/messages/en.json
Missing metadata, use translated message.
Locally.
=> feat(core): add missing metadata in account home page

.changeset/translations-patch-8f3fe68b.md, .github/workflows/translations-changeset.yml
Auto generate patch changeset for translations PRs.
Tested it locally in this PR, generates patch and commits as the bot. No longer shown since I rebased to previous commit.
=> chore(core): add translations changeset workflow

.changeset/odd-jokes-love.md, .changeset/twenty-walls-flash.md, core/auth.ts, core/client/index.ts, packages/client/src/client.ts
Passes the customer IP on non-cacheable requests so we can enforce things like rate limiting.
`x-real-ip` is the Vercel Server IP, while `x-forwarded-for` is my personal IP
=> feat: pass ip information to request on non-cacheable requests

.changeset/thick-donuts-hope.md, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/(default)/query.ts, core/app/[locale]/not-found.tsx, core/components/footer/footer.tsx, core/components/header/index.tsx
This is prep work for PPR. Moves the layout query from being fetched in the layout to header / footer. The request gets deduped by React.
Adds a header skeleton to avoid layout shifts.
=> refactor: wrap header and footer in suspense

core/app/[locale]/layout.tsx, core/app/globals.css, core/package.json, core/tailwind.config.js, pnpm-lock.yaml
Initial setup to use soul vibe fonts and styles.
=> chore: use soul tailwind config and fonts, electric colors

.changeset/strange-beers-smile.md, core/app/[locale]/(default)/blog/[blogId]/_components/sharing-links.tsx, core/app/[locale]/(default)/blog/[blogId]/page-data.ts, core/app/[locale]/(default)/cart/_components/cart-item.tsx, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/product/[slug]/_components/gallery/fragment.ts, core/app/[locale]/(default)/product/[slug]/_components/product-form/fields/multiple-choice-field/fragment.ts, core/app/[locale]/(default)/product/[slug]/_components/product-schema.tsx, core/app/[locale]/(default)/product/[slug]/page-data.ts, core/components/blog-post-card/fragment.ts, core/components/footer/fragment.ts, core/components/header/fragment.ts, core/components/product-card/fragment.ts, core/components/store-logo/fragment.ts, core/lib/cdn-image-loader.ts
Simplify image loader implementation by using the lossy param from the API, instead of setting it in code.
=> Get lossy image from API instead of setting param in code

core/tests/fixtures/utils/account/create.ts, core/tests/ui/e2e/checkout.spec.ts, core/tests/ui/e2e/register.spec.ts, core/tests/ui/e2e/reset.spec.ts
Updating the creation of accounts/orders with emails addresses from the list of ["junk" domains](https://datatracker.ietf.org/doc/html/rfc2606#section-3)
See https://github.com/bigcommerce/catalyst/actions/runs/11112645581
=> chore(tests): update email addresses to junk domains

.changeset/swift-jeans-jam.md, core/app/[locale]/(default)/account/(tabs)/settings/change-password/_components/change-password-form.tsx
This PR fixes the problem of sending the password change form, namely, the form was not sent after the first click on the submit button due to the validation of the input fields.
locally
**before:**
https://github.com/user-attachments/assets/116fbd62-b32b-4b33-a1c0-754c4ba2e6f6
**after:**
https://github.com/user-attachments/assets/983b9a26-1d9a-480a-8ee5-fefaedcf51b6
=> fix(core): fixing the problem with submitting the password change form

core/lib/bodl/bodl.ts, core/lib/bodl/providers/ga4/google_analytics4.js
Pulls setting up the script of bodl events and gtag into the `Bodl` class. This helps create a consistent location for where we are binding the DOM scripts.
=> refactor(core): move script binding to bodl initialization

core/lib/bodl/analytics.d.ts, core/lib/bodl/bodl.ts, core/lib/bodl/providers/ga4/google_analytics4.js, core/package.json, pnpm-lock.yaml
Extracts consent mode events into the Bodl provider. Technically consent mode is not fully flushed out as we don't have a consent banner to trigger these events, however we should still support it for countries that require GDPR restrictions.
=> refactor(core): elevate consent mode into bodl provider

.changeset/thirty-owls-fry.md, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/wishlist-book.tsx
This pr contains the fix for vertical image on Wishlist Book
Locally
=> fix(core): fix wishlist book item image size

.changeset/shiny-otters-end.md, core/app/[locale]/(default)/account/(tabs)/_components/modal.tsx, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/delete-wishlist-form/index.tsx, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/update-wishlist-form/_actions/update-wishlist.ts, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/update-wishlist-form/index.tsx, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/wishlist-book.tsx, core/app/[locale]/(default)/account/(tabs)/wishlists/_components/wishlist-details.tsx, core/app/[locale]/(default)/account/(tabs)/wishlists/page-data.ts, core/app/[locale]/(default)/account/(tabs)/wishlists/page.tsx, core/client/mutations/update-wishlist.ts, core/components/product-card/delete-wishlist-item-form/_actions/delete-wishlist-item.ts, core/components/product-card/delete-wishlist-item-form/index.tsx, core/components/product-card/index.tsx, core/components/ui/product-card/product-card.tsx, core/messages/en.json, core/tests/ui/e2e/account.spec.ts
This pr adds Wishlist Details Page to Account Wishlist and fix minor translation issues for Wishlist Book
Locally
=> feat(core): add wishlist details

core/app/[locale]/(default)/account/(tabs)/orders/_components/order-details.tsx, core/app/[locale]/(default)/account/(tabs)/orders/_components/orders-content.tsx, core/app/[locale]/(default)/account/(tabs)/orders/_components/orders-list.tsx
This PR updates  behaviour of `truncatedCard` for items quantity in Order. For instance, previously if we have 8 items of the same T-short, we showed as total quantity 8, while now it has been corrected  to 1 item. Additionally, usage for `getTranslations` has been updated as it's refactored across Catalyst other pages.
locally
https://github.com/user-attachments/assets/0d9b1008-5cdb-4fed-8741-394dd13b1d81
https://github.com/user-attachments/assets/35b89b5e-3a0f-4fb3-9ee2-74a592b8d918
=> fix(core): update quantity of items in order truncated card

.changeset/famous-grapes-argue.md, core/app/[locale]/(default)/account/(tabs)/orders/_components/order-details.tsx, core/app/[locale]/(default)/account/(tabs)/orders/_components/product-snippet.tsx, core/messages/en.json
This PR updates view for coupons and non coupons discounts in order making them separate items for order's summary.
locally
https://github.com/user-attachments/assets/9e1e4452-2b2e-460e-a6b0-5719914c72db
https://github.com/user-attachments/assets/a279451c-198f-4115-8ec7-8fbe9e585c74
=> fix(core): separate promotions and coupons for order summary

.changeset/shy-tips-accept.md, packages/create-catalyst/src/utils/is-exec-exception.ts
Adds a typeguard to narrow Errors thrown by `execSync` to be of `ExecException` types.
Locally
=> refactor(cli): add isExecException to check if an error is an ExecException

.changeset/stale-queens-tan.md, packages/create-catalyst/src/utils/has-github-ssh.ts
> [!IMPORTANT]
> This PR stacks on #1431 
Adds a function to check if a user has SSH authentication set up with GitHub
Locally
=> refactor(cli): add hasGitHubSSH function to check if GitHub SSH authentication is successful

.changeset/small-experts-divide.md, packages/create-catalyst/bin/index.cjs
Previously, we allowed any Node.js version 20 or greater. We have been experiencing issues with people using less-stable odd-numbered Node.js versions (like `21`) or Node.js versions that are still new and not something we have fully tested with Catalyst (like `22`)
Locally
=> refactor(cli): update required Node.js version

.changeset/pretty-dryers-perform.md, packages/create-catalyst/src/commands/create.ts
> [!IMPORTANT]
> This PR stacks on #1433
Ensure `pnpm` is installed on the machine running the CLI
Locally
=> refactor(cli)!: ensure pnpm is installed on the machine running the CLI

.changeset/fair-lobsters-own.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/install-dependencies.ts
> [!IMPORTANT]
> This PR stacks on #1439
Refactor `installDependencies` so that it installs all dependencies found in the root `package.json` file of the monorepo
Locally
=> refactor(cli)!: simplify installDependencies to install all monorepo deps

.changeset/brave-shirts-carry.md, packages/create-catalyst/src/commands/create.ts
> [!IMPORTANT]
> This PR stacks on #1441
Remove automatic generation of GraphQL type definitions on project creation. There is no root-level `generate` Turbo task, which means the environment variables aren't being picked up correctly. 
We could refactor `writeEnv` to write two env files, one in root and one in `core/` but I'm not confident that's the right solution.
Locally
=> refactor(cli)!: remove auto generation of gql types on project creation

.changeset/twelve-deers-nail.md, core/app/[locale]/(default)/compare/_components/add-to-cart/index.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-form/index.tsx, core/app/providers.tsx, core/components/header/cart-icon.tsx, core/components/header/cart-provider.tsx, core/components/product-card/add-to-cart/form/index.tsx
`Add to cart` (in PDP, PLP, Compare) now supports some optimistic updates. We keep the loading spinner on the button but show the toast and update the badge right away.
If the request fails it will revert the changes and show the error toast.
https://github.com/user-attachments/assets/8e8f494e-240c-44ff-b82b-e5a2b80136c0
=> feat: optimistic updates on add to cart

.changeset/soft-ladybugs-perform.md, core/app/[locale]/(default)/product/[slug]/page.tsx
When a product has pre-selected options, the state of the PDP was not selecting the correct variant.
https://github.com/user-attachments/assets/674d6bf9-a8fc-45bd-bd37-68710bf63fc6
=> fix(core): variant selection with pre-selected options

core/tests/ui/e2e/cart.spec.ts, core/tests/ui/e2e/checkout.spec.ts, core/tests/ui/e2e/coupon.spec.ts, core/tests/ui/e2e/shipping.spec.ts, core/tests/visual-regression/components/button.spec.ts, core/tests/visual-regression/components/input.spec.ts
Broke a few tests on https://github.com/bigcommerce/catalyst/pull/1445 this PR fixes them.
👁️ CI
=> fix(tests): handle optimistic cart updates

.env.example, core/.env.example, docs/environment-variables.md
OAuth access token is no longer required for Catalyst to function; remove the docs.
Client Secret was never fully implemented and is about to be replaced, remove that also.
N/A
=> Remove OAuth Access Token/Client Secret docs

.changeset/silly-queens-explode.md, docs/environment-variables.md, packages/client/src/client.ts
If the store has Trusted Proxy enabled, the trusted proxy secret can be stored as an env variable in which case it will be sent as a header on all requests.
Verified via logs
=> Add new env variable for Trusted Proxy

.changeset/serious-rice-cough.md, core/app/[locale]/(default)/(auth)/change-password/_actions/change-password.ts, core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts
Ran a few functional tests this morning so some of our customer mutation endpoints were being rate limited by the same IP address. This adds `no-store` to the auth mutations to ensure the forwarded ip is being passed to BC.
See CI.
=> fix(core): add no-store to rate limited mutations

packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/clone-catalyst.ts
This PR adds the ability to pass in an arbitrary repository in the form of `org-or-user/repository-name` that the `cloneCatalyst` function will use to determine which GitHub repository to clone locally. 
This PR also refactors the types for the arguments passed to the `cloneCatalyst` function; we want Typescript to complain if the arguments are not passed at all, but also want the ability to pass `undefined` as values for those arguments.
Tested + verified locally
=> feat(cli): add ability to pass arbitrary GitHub repository to clone from

core/app/[locale]/(default)/cart/_components/item-quantity/index.tsx
This is intended to set the product quantity back to its original value when there's an error while incrementing the quantity in the cart. Without this, you can increment the value from 1, 2, 3, 4 ,5, etc, even if there's only, say 2 in stock. Resetting it after the error prevents the UI from being left in an inconsistent state.
=> fix(core): set the product quantity back to it's original value when there's an error updating it

.changeset/great-turtles-breathe.md, core/middlewares/with-routes.ts
Merging 3rd party code from #1429 (PR was created to run CI)
See CI
=> refactor(core): update with-routes to handle redirect logic better

packages/create-catalyst/src/utils/checkout-ref.ts
`checkoutRef` is called from within `cloneCatalyst`, which is called before important logic such as `writeEnv` inside of `create.ts`. If we allow the process to exit before `writeEnv`, the user has to start the entire `create` flow from scratch which is frustrating. 
Locally
=> fix(cli): do not exit process if user ref cannot be checked out

.changeset/fifty-queens-provide.md, core/components/breadcrumbs/index.tsx
Breadcrumbs for top level category pages are no longer rendered
=> chore(core): dont render breadcrumbs for top level categories

.changeset/rich-flies-hang.md, core/app/[locale]/(default)/(faceted)/category/[slug]/_components/empty-state.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/messages/en.json
Empty state for category pages with no products
Eg: https://catalyst-latest-git-category-empty-state-bigcommerce-platform.vercel.app/kitchen/plates/china/
=> feat: category page empty state

.changeset/young-pandas-swim.md, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/telemetry.ts, packages/create-catalyst/src/hooks/telemetry.ts, packages/create-catalyst/src/index.ts, packages/create-catalyst/src/utils/telemetry/index.ts, packages/create-catalyst/src/utils/telemetry/telemetry.ts, packages/create-catalyst/tsup.config.ts, pnpm-lock.yaml
Adds telemetry collection to the CLI. If users want to opt-out of CLI telemetry collection, use `pnpm create @bigcommerce/catalyst telemetry disable` or use the `CATALYST_TELEMETRY_DISABLED` environment variable to opt-out.
Write key is injected on build:
=> feat(cli): add telemetry enable/disable/status commands

docs/caching.md
Add link to ISR docs; I wanted to put these in the docs originally but the link was 404ing at that time. It is now fixed
Note - this redirects to Canary docs for now, I suspect that is temporary.
Click on it
=> Add ISR link

.changeset/rich-beers-jam.md, .github/workflows/changesets-release.yml
Passes the `CLI_SEGMENT_WRITE_KEY` env var into the build command to start collecting telemetry.
See #1479
=> feat(cli): start to collect telemetry from write key

.changeset/quiet-ligers-try.md
Trying to rerelease the CLI in order to build the env var into the CLI.
=> chore(cli): noop commit to rebuild CLI

.changeset/breezy-numbers-divide.md, packages/create-catalyst/src/hooks/telemetry.ts
We were getting an issue where the `commandName` was empty, which happens when we run `./bin/index.cjs` without an argument.
=> fix(cli): add default command name on pre-hook

.changeset/silent-rats-hear.md, core/app/[locale]/(default)/(auth)/change-password/page.tsx, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/(auth)/register/_actions/login.ts, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/account/(tabs)/layout.tsx, core/app/[locale]/(default)/account/(tabs)/settings/change-password/page.tsx, core/app/[locale]/(default)/account/layout.tsx, core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/(default)/page.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/layout.tsx, core/app/[locale]/maintenance/page.tsx, core/app/[locale]/store-selector/page.tsx, core/app/admin/route.ts, core/app/sitemap.xml/route.ts, core/app/xmlsitemap.php/route.ts, core/client/index.ts, core/components/header/_actions/logout.ts, core/components/ui/compare-drawer/compare-drawer.tsx, core/i18n/routing.ts, core/package.json, core/tests/fixtures/utils/account/account.ts, core/tests/ui/e2e/account.spec.ts, core/tests/ui/e2e/login.spec.ts, core/tests/ui/e2e/register.spec.ts, pnpm-lock.yaml
+ Bump `next-intl`.
+ Use new `createNavigation` api.
+ Pass `locale` to `redirects`.
+ `setRequestLocale` is no longer unstable.
+ Fixes https://github.com/amannn/next-intl/issues/1335
Locally, redirecting on default locale will not append the default locale, just like Links.
Updated tests to match this behavior.
=> chore(core): bump next-intl

.changeset/warm-rivers-breathe.md, packages/create-catalyst/src/commands/init.ts
Adds a missing `.identify` call when using the `init` command.
=> feat(cli): add identify on init

.changeset/fast-students-approve.md, core/app/[locale]/(default)/account/(tabs)/settings/_components/update-settings-form.tsx, core/messages/en.json, core/tests/ui/e2e/account-settings.spec.ts
This PR improves account settings form, namely it removes unnecessary fields.
Also this PR updates settings confirmation message.
locally
**before**:
https://github.com/user-attachments/assets/ee8b85bd-34b9-4ef7-8303-95449c3d2ff0
**after**:
https://github.com/user-attachments/assets/ce4aa7dc-8152-41c3-8f3c-db12840ec726
**with custom field:**
https://github.com/user-attachments/assets/bf0e367b-d144-488b-89e6-c731d46fbb23
=> fix(core): improve account settings form

.changeset/tricky-trainers-greet.md, packages/create-catalyst/src/hooks/telemetry.ts
We were getting some events with arguments. This fixes the telemetry to only send events if the command is one of the available commands. Also added a function to filter out an allowlist of args to pass as properties on the event.
=> feat(cli): fix event name and provide additional properties

.changeset/shy-ads-buy.md, core/app/[locale]/(default)/(auth)/change-password/_components/change-password-form.tsx, core/app/[locale]/(default)/(auth)/login/forgot-password/_components/reset-password-form/index.tsx
The PR improves styles for reset password page like:
- fix invalid email validation
- update colour & size for validation errors
- fix ReCaptcha colour
locally
https://github.com/user-attachments/assets/e82af807-ba97-429a-8b9b-02f9035dc16e
=> fix(core): update styles for reset password validation

.github/workflows/regression-tests.yml
Do not send slack notifications if a pull request does not exist. This would cut down some of the noise and notify of changes that need attention.
Part of CI
=> fix(chore): Send slack notifications only for open pr

core/tests/ui/e2e/account.spec.ts, core/tests/ui/e2e/wishlist.spec.ts
- moved add/delete wishlist test from account.spec.ts to separate file wishlist.spec.ts
- test with adding product to wishlist
- test with creating new wishlist from drawer
- test to make sure guest user cannot use wishlist
- test to verify Favorites wishlist is default and cannot be deleted
See regression test run in CI (there is separate ticket to fix button test in visual regression)
=> test(core): Add wishlist related tests

.changeset/eighty-tomatoes-give.md, core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts, core/app/[locale]/(default)/(auth)/login/forgot-password/_components/reset-password-form/index.tsx
This PR improves validation error on Reset Password form for User. Previously Zod Error was an array of data that was quite hard to read through so we've transformed it into a message where User can read about invalid field and reason for appeared error.
locally
https://github.com/user-attachments/assets/d25bc125-a6cf-4aeb-9aee-7537c0bf521c
https://github.com/user-attachments/assets/908c6ded-b637-4125-a782-fdd1b5fa43e8
=> fix(core): improve error message on reset password page

.changeset/chilly-trains-sort.md, core/components/ui/footer/footer.tsx
This PR just removes annoyance for warning not using unique keys in components.
```
Warning: Encountered two children with the  same key
```
We have collection items  with identical keys in `<Footer/>` so updating keys in one of them removes the warning.
locally
=> fix(core): fix warning for using the same keys on items

.changeset/sweet-dragons-stare.md, core/app/[locale]/(default)/account/(tabs)/settings/_components/text-field.tsx
This PR adds validation message after an incorrectly entered email
locally
**before:**
https://github.com/user-attachments/assets/1f9c0884-2e8e-4782-bc82-99561c7883ba
**after:**
https://github.com/user-attachments/assets/4119afd9-9ce0-4762-a14b-5bcb58fffaf3
=> fix(core): fix validation message for email on account settings page

.changeset/metal-dragons-decide.md, core/app/[locale]/(default)/account/(tabs)/settings/change-password/page.tsx
This PR improves change password page behaviour.  Previously if  logged in User tried to reach change password page by url,  it was blocked by error.
locally
https://github.com/user-attachments/assets/57c07f2f-0ee4-4b87-9c85-18611515db7c
https://github.com/user-attachments/assets/8a9204b1-e230-46ed-8c65-1d136103bd99
=> fix(core): improve behaviour for change password page for logged in user

core/tests/ui/e2e/change-password.spec.ts
Added a test for changing password via Account settings as a logged in user and log in with a new password afterwards 
See regression suite test run in CI
=> test(core): Add change password test as a logged in user

.changeset/good-dragons-sing.md, packages/create-catalyst/src/commands/create.ts
If a user provides `--store-hash`, `--channel-id`, and `--storefront-token`, there is no need to prompt the user to log into a store because they already have a store they want to connect to, a channel they want to link, and a valid auth token to interact with the GQL API for that channel.
I would post a video but it would expose SF tokens - this was tested locally and ran without errors and without affecting other CLI flag combinations.
=> feat: allow project creation without prompts if given valid config values

core/app/[locale]/(default)/compare/page.tsx, core/vibes/soul/primitives/compare-card/index.tsx
Use plaintextdescription and custom fields on compare page.
Need to look at styling next; this should be table-like.
Reference:
https://cornerstone-light-demo.mybigcommerce.com/compare/111/110/109
=> Wire up plain text description and custom fields on compare

core/app/[locale]/(default)/product/[slug]/page.tsx
A `@ts-expect-error` was resulting in a 500 when rendering PDPs. This PR fixes that issue.
Since `@ts-expect-error` was removed we're now respecting TS types.
=> fix: PDP was ignoring TS

.changeset/chilled-fans-count.md, core/app/[locale]/(default)/account/(tabs)/orders/_components/product-snippet.tsx
The PR brings images for items in Orders. 
locally
https://github.com/user-attachments/assets/be0dbdf4-7f6d-42fa-a7aa-c7c6cdb46004
=> feat(core): add images for order items

core/app/[locale]/(default)/page.tsx
The cta button on the featured image of the homepage was linking back to the home page. Now, it links to `/shop-all`. 
Go to home page, scroll down to the featured image and click the `Shop Now` button.
=> Chore: Update FeateredImage CTA href

core/vibes/soul/sections/products-list-section/sorting.tsx
Add `useOptions({shallow: false})` to trigger server rerender.
Locally sorting works.
=> fix: trigger server render on sort

core/vibes/soul/primitives/cursor-pagination/index.tsx
For cursor navigation we either want an `after` or `before`, not both.
Before:
https://github.com/user-attachments/assets/e7189cd1-ebbf-47df-8197-211073c94ed5
After:
https://github.com/user-attachments/assets/1a76128f-846a-418e-913d-368e724c8254
Locally.
=> fix: cursor navigation by removing unused param

core/components/header/index.tsx
For some reason, the redirect from `/account` to `/login` is very slow. The opposite is not true, so this replaces the link for now.
Locally, way faster to redirect from `/login` to `/account` if authenticated.
=> fix: replace /account with /login in Header

core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/account-settings-section/change-password-form.tsx, core/vibes/soul/sections/account-settings-section/update-account-form.tsx, core/vibes/soul/sections/address-list-section/index.tsx, core/vibes/soul/sections/cart/index.tsx, core/vibes/soul/sections/forgot-password-section/forgot-password-form.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx, core/vibes/soul/sections/sign-in-section/sign-in-form.tsx, core/vibes/soul/sections/sign-up-section/sign-up-form.tsx
VIBES uses `useActionState` for forms which is only supported in React 19 RC. In Catalyst we were using `useFormState` as a drop-in replacement for `useActionState`. Unfortunately, the third tuple item returned by `useActionState`, `isPending`, isn't returned by `useFormState`. This PR addresses that by using `useFormStatus` for the pending state.
https://github.com/user-attachments/assets/7039aa59-ece6-4c0f-8361-d842735aebfa
https://github.com/user-attachments/assets/f9a4cf64-de91-4c27-859a-952cecd224bb
=> fix: invalid use of `useFormState`

core/lib/makeswift/components.ts, core/makeswift/components/button-link/button-link.makeswift.tsx
We don't want the following builtins to appear in the Makeswift builder:
- Carousel
- Countdown
- Form
- Navigation
Also, we want the Button component to appear in the Makeswift toolbar instead of the menu
https://github.com/user-attachments/assets/1f3124d5-a213-4d6b-9e36-a3028b85f610
=> Hide some Makeswift builtins

core/lib/makeswift/components.ts, core/makeswift/components/section-layout/section-layout.makeswift.ts, core/vibes/soul/sections/section-layout/index.tsx, core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
=> feat: add section layout

core/makeswift/components/featured-products-carousel/featured-products-carousel.makeswift.tsx, core/makeswift/components/featured-products-list/featured-products-list.makeswift.tsx, core/makeswift/components/product-card/product-card.makeswift.tsx, core/makeswift/components/products-carousel/products-carousel.makeswift.tsx, core/makeswift/components/products-list/products-list.makeswift.tsx
Resolves `Attempted import error: 'swr' does not contain a default export (imported as 'useSWR')` runtime error,`useSWR` cannot be used on the server: https://github.com/vercel/swr/issues/2694
=> fix: mark bindings that use `swr` to fetch data with `use client`

core/app/globals.css, core/lib/makeswift/components.ts, core/makeswift/components/image/image.makeswift.tsx, core/makeswift/components/products-carousel/products-carousel.makeswift.tsx, core/makeswift/components/products-list/products-list.makeswift.tsx, core/makeswift/components/sticky-sidebar-layout/sticky-sidebar-layout.makeswift.tsx, core/vibes/soul/primitives/price-label/index.tsx, core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
- Replaced built-in Makeswift image with `BcImage`.
- Added `overflow-x: hidden` to body.
- Replaced `gap` with `padding` in the `StickyLayout` component. Gap seems to affect the `max-width` calculation of child elements. Further investigation is required, but using padding fixes the overflow issues.
- Put all Makeswift components that fetch from the product catalog under the `Catalog` label group.
=> Replace built-in image, hide body overflow-x, update labels, fix sticky layout

core/lib/makeswift/components.ts
Removing the FeaturedImageSection registration because we want all of those sections to be built visually in Makeswift.
=> fix: remove makeswift featured image section

.changeset/cuddly-boats-teach.md, core/.gitignore, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/account/(tabs)/layout.tsx, core/app/[locale]/(default)/account/(tabs)/settings/change-password/page.tsx, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/(default)/page.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/(default)/product/[slug]/static/page.tsx, core/app/[locale]/maintenance/page.tsx, core/app/[locale]/store-selector/_components/locale-link.tsx, core/app/[locale]/store-selector/page.tsx, core/build-config/reader.ts, core/build-config/schema.ts, core/build-config/writer.ts, core/channels.config.ts, core/client/index.ts, core/components/ui/header/locale-switcher.tsx, core/i18n/request.ts, core/i18n/routing.ts, core/next.config.ts
- Adds build time config, which writes a `.json` file that can be read at runtime
- Fetch available locales at build time and stores them in build config
=> feat(core): fetch locales at build time

core/app/[locale]/(default)/account/(tabs)/orders/page-data.ts
This PR extends `CustomerOrders` query with ability to filter out results.
locally
**Filtering by Status**:
=> refactor(core): add filters to orders query

core/vibes/soul/sections/slideshow/index.tsx
In the Slideshow component, if a slide description is removed, there was no spacing between the title and button. Margin classes were changed to ensure the title, description, and button had the proper spacing between them at all times.
View the Slideshow component and hide any slide description.
=> fix: move margins to button in slideshow

core/middlewares/with-routes.ts
This error was introduced when we tried to fix a stale issue when publishing changes. Instead of just removing the `postfix`, we commented out the whole block that handles PDP.
Run locally, go to PDP.
=> fix: PDP 404

core/next.config.ts
Re-add required Makeswift plugin into the next.config.ts configuration, to avoid errors with disallowed image hosts for Makeswift-provided images.
=> Add Makeswift plugin into Next.js config

core/package.json, pnpm-lock.yaml
Bump Makeswift `runtime` to the latest "RC" version that includes https://github.com/makeswift/makeswift/pull/872
=> fix: update runtime, fixes various crashes on attempts to use page templates

.changeset/forty-actors-notice.md, core/next.config.ts, core/package.json, pnpm-lock.yaml
Remove webpack config added in https://github.com/bigcommerce/catalyst/pull/1209 as it has outlived its usefulness. Need to remove from docs also.
=> Remove webpack chunk plugin

docs/environment-variables.md
Follow up to https://github.com/bigcommerce/catalyst/pull/1661 to remove docs for the removed variable
N/A
=> Remove WEBPACK_MAX_CHUNKS docs

core/app/[locale]/(default)/account/(tabs)/addresses/_actions/delete-address.ts, core/app/[locale]/(default)/account/(tabs)/addresses/add/_actions/add-address.ts, core/app/[locale]/(default)/account/(tabs)/addresses/edit/[slug]/_actions/update-address.ts, core/app/[locale]/(default)/account/(tabs)/settings/_actions/update-customer.ts, core/app/[locale]/(default)/cart/_actions/remove-item.ts, core/app/[locale]/(default)/cart/_components/coupon-code/apply-coupon-code.ts, core/app/[locale]/(default)/cart/_components/coupon-code/remove-coupon-code.ts, core/app/[locale]/(default)/cart/_components/item-quantity/update-item-quantity.ts, core/app/[locale]/(default)/cart/_components/shipping-info/submit-shipping-info.ts, core/app/[locale]/(default)/cart/_components/shipping-options/submit-shipping-costs.ts, core/app/[locale]/(default)/compare/_actions/add-to-cart.ts, core/app/[locale]/(default)/layout.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-form/_actions/add-to-cart.ts, core/components/product-card/add-to-cart/form/_actions/add-to-cart.ts, core/next.config.ts, core/package.json, pnpm-lock.yaml
+ Bumps next to canary
+ Enables PPR
+ Use new `expirePath`/`expireTag` functions.
We will need PPR in Header to properly render cart count.
Locally PPR is enabled in static sites.
=> chore(core): use next canary and enable ppr

.changeset/quick-owls-relate.md, core/app/[locale]/(default)/compare/_actions/add-to-cart.ts, core/app/[locale]/(default)/compare/_components/add-to-cart/index.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-form/_actions/add-to-cart.ts, core/app/[locale]/(default)/product/[slug]/_components/product-form/index.tsx, core/app/notifications.tsx, core/client/mutations/add-cart-line-item.ts, core/client/mutations/create-cart.ts, core/components/product-card/add-to-cart/form/_actions/add-to-cart.ts, core/components/product-card/add-to-cart/form/index.tsx, core/messages/en.json
Updates the add to cart actions to show an error based on the API response.
=> feat(core): update add to cart visual errors

packages/create-catalyst/src/commands/create.ts
Closes #1463
Fix the `create` CLI command to improve cross-platform compatibility when checking for required tools (git and pnpm). Currently it does not work on Windows.
- Introduced a utility function `getPlatformCheckCommand`
- Using `where.exe` (instead of `where`) for Windows to avoid conflicts with PowerShell's `Where-Object.`
- Fall back to existing `which` for Unix systems.
- Simulated missing tools to confirm that error messages display as expected.
- Windows: Tested in Command Prompt and PowerShell, with and without git/pnpm available.
No specific regression testing done over Linux/MacOS behaviour.
=> Fix command check for Windows in create

.changeset/sixty-pots-lay.md, core/client/index.ts
Passes the shopper locale into the client request which responds back with localized catalog data. It should also return other localized data, which is done by passing the `Accept-Language` header in the client request.
https://catalyst-latest-git-feat-shopper-locale-bigcommerce-platform.vercel.app/smith-journal-13/
https://catalyst-latest-git-feat-shopper-locale-bigcommerce-platform.vercel.app/es/smith-journal-13/
=> feat(core): add localized data-fetching

.changeset/selfish-buses-clap.md, .changeset/thirty-rockets-smell.md, core/.eslintrc.cjs, core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/app/[locale]/(default)/cart/_components/cart-item.tsx, core/app/[locale]/(default)/compare/page.tsx, core/components/bc-image/index.tsx, core/components/image/index.tsx, core/components/store-logo/index.tsx, core/components/ui/blog-post-card/blog-post-card.tsx, core/components/ui/compare-drawer/compare-drawer.tsx, core/components/ui/footer/footer.tsx, core/components/ui/form/pick-list/pick-list.tsx, core/components/ui/gallery/gallery.tsx, core/components/ui/header/header.tsx, core/components/ui/header/mobile-nav.tsx, core/components/ui/header/search.tsx, core/components/ui/product-card/product-card.tsx, core/components/ui/slideshow/slideshow.tsx, core/lib/cdn-image-loader.ts, core/lib/store-assets.ts
I attempted to try and use the `images.loaderFile` from `next.config.ts` but there are some internals that Next.js does with the build to replace all references to the default loader import. This causes infinite loops trying to import the defined `loaderFile`.
The PR makes the default image component `CatalystImage` which uses the default loader as a fallback. `BcImage` was renamed to `CatalystImage`.
=> feat(core): default to local image component

core/package.json
`@conform-to/react` was listed twice as a dependency
=> chore: remove duplicate dep

core/tests/fixtures/utils/order/index.ts, core/tests/ui/e2e/order-details.spec.ts, core/tests/ui/e2e/order.spec.ts
This Pr adds test for Order page to validate that  necessary sections are presented on the page.
locally
=> test(core): add order details test

.changeset/smart-feet-jump.md, core/app/[locale]/(default)/account/(tabs)/addresses/_actions/delete-address.ts, core/app/[locale]/(default)/account/(tabs)/addresses/_components/address-book.tsx, core/app/[locale]/(default)/account/(tabs)/addresses/page-data.ts, core/app/[locale]/(default)/account/(tabs)/addresses/page.tsx
…
This PR fixes the display of the existing address list after removing all visible addresses on the page.
Also this PR updates the entire list of addresses after deleting an address.
locally
**before:**
https://github.com/user-attachments/assets/bdc81450-2b76-47a5-9ea9-ff202c2d4e43
**after:**
https://github.com/user-attachments/assets/dd9f46b3-d90d-4954-a8aa-fd3010d48ebb
=> fix(core): refresh the entire list of addresses after deleting an address

.changeset/weak-poets-trade.md, core/package.json
The `--turbo` flag is causing a few issue as it's still experimental. Opting to remove it for now.
=> fix(core): remove --turbo dev flag

.changeset/quiet-sloths-beg.md, core/app/[locale]/(default)/account/addresses/_actions/delete-address.ts, core/app/[locale]/(default)/account/addresses/_components/address-book.tsx, core/app/[locale]/(default)/account/addresses/edit/[slug]/_components/edit-address-form.tsx, core/app/[locale]/(default)/account/addresses/page-data.ts, core/app/[locale]/(default)/account/addresses/page.tsx, core/client/tags.ts, core/tests/ui/e2e/account.spec.ts, core/tests/ui/e2e/addresses.spec.ts
Converts feedback message when deleting an address to use toasts instead of the page messages.
https://github.com/user-attachments/assets/1633607f-dca3-4f39-9418-017a846131fb
=> feat(core): use toasts for address deletions

.changeset/modern-garlics-sparkle.md, core/app/[locale]/(default)/account/addresses/_actions/delete-address.ts, core/app/[locale]/(default)/account/addresses/add/_actions/add-address.ts, core/app/[locale]/(default)/account/addresses/add/_components/add-address-form.tsx, core/app/[locale]/(default)/account/addresses/add/page.tsx, core/app/[locale]/(default)/account/addresses/edit/[slug]/_actions/update-address.ts, core/app/[locale]/(default)/account/addresses/edit/[slug]/_components/edit-address-form.tsx, core/app/[locale]/(default)/account/addresses/edit/[slug]/page.tsx, core/app/[locale]/(default)/account/settings/_actions/update-customer.ts, core/app/[locale]/(default)/account/settings/_components/update-settings-form.tsx, core/app/[locale]/(default)/account/settings/page-data.tsx, core/messages/en.json
Removes the ReCaptcha validation from actions related to your account. ReCaptcha was needed for BigCommerce headless stores using client-side tokens, however we are using server side auth so it's no longer needed for pages that a customer is logged in for.
=> feat(core): remove recaptcha fields in the account area

.changeset/silent-snails-sparkle.md, core/components/add-to-cart-button/index.tsx
The product options didn't have any inventory but other variants had stock. This fixes the logic to check for everything correctly.
=> fix(core): update inventory logic for out-of-stock

packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/checkout-ref.ts, packages/create-catalyst/src/utils/clone-catalyst.ts, packages/create-catalyst/src/utils/reset-branch-to-ref.ts
When moving from OCC to development, users should have the ability to check out a ref that is then set to the `main` branch so they can continue smoothly in their development journey. This will put them in a state where they have the exact code they originally deployed in OCC but will be set to the `main` branch.
- create `reset-main` boolean option for CLI
- create new resetBranchToRef to be called if `ghRef` and `resetMain` are present
- update checkoutRef to return a boolean status to determine whether or not it was run successfully
- test existing OCC generated command in isolation - should work as expected
- test existing OCC generated command  with `--reset-main` flag with the end result of being in the `main` branch with code matching the `gh-ref` provided
=> FEAT: added reset branch to ref command

.changeset/honest-ways-tell.md, core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts
The previous implementation would treat an empty string as a valid value, resulting in `['']` as the parsed array, which when mapped and coerced with `Number` to get an entity ID would result in `[0]`.
This gave some weird results, e.g., when visiting `/shop-all?brand=`.
The entity ID `0` was being passed to the `searchProducts` mutation resulting in products that _didn't_ have a brand in the results, instead of all products since a brand wasn't specified.
The current change now treats this as an empty array, which I believe is the appropriate behavior.
Notably, this behavior was not occurring in production deployments.
https://github.com/user-attachments/assets/fc22f48d-33aa-46ee-94b7-e5a212ac5e45
=> fix: properly handle empty array URL search params

core/components/add-to-cart-button/fragment.ts, core/components/add-to-cart-button/index.tsx
Fixes it again... The PLP page was showing out of stock options even though they were in stock.
=> fix(core): update inventory logic for out-of-stock again

.changeset/yellow-cougars-allow.md, core/app/[locale]/(default)/(auth)/layout.tsx, core/tests/ui/e2e/login.spec.ts
Redirects the user back to the account page if they are already logged in and trying to navigate to `/login`, `/login/forgot-password`, `/register`, or `/change-password` pages. All of this is under the `(auth)` route group.
https://github.com/user-attachments/assets/55240621-8f5b-4e84-81a8-3fe852616650
=> feat(core): redirect to account from auth pages if logged in

core/app/[locale]/(default)/page.tsx, core/components/footer/footer.tsx, core/components/header/index.tsx, core/messages/en.json, core/vibes/soul/primitives/carousel/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/primitives/products-carousel/index.tsx, core/vibes/soul/sections/featured-products-carousel/index.tsx, core/vibes/soul/sections/footer/index.tsx
This should clear all accessibility warnings in the homepage except the contrasting colors.
=> fix: bump VIBES components and pass in accessibility props in Home

core/app/globals.css, core/vibes/soul/primitives/alert/index.tsx, core/vibes/soul/primitives/button-link/index.tsx, core/vibes/soul/primitives/button/index.tsx, core/vibes/soul/primitives/inline-email-form/index.tsx, core/vibes/soul/primitives/navigation/index.tsx
To improve the theming experience we are introducing component based CSS variables for colors, font family etc. 
This PR adds a `shape` prop to the `Button` and `ButtonLink` and updates the idea of an `icon` size to a combination of a `size` and `shape` rather than being a special type of `size`.
I also add CSS variables to control the colors of all variations of the button at a global level. This will be hooked into via the `Theme` component to allow visual editing in Makeswift.
Verified all live usages of the `Button` and `Button` link have no visual regression.
https://github.com/user-attachments/assets/5397b468-948f-4a6a-bf8f-c8facefd090e
=> feat: update button props and css variables

core/vibes/soul/primitives/product-card/index.tsx
- Adds `imagePriority` prop to `ProductCard` for image pre-loading option
Locally
=> feat: add imagePriority prop to ProductCard

core/app/[locale]/layout.tsx, core/app/globals.css, core/vibes/soul/sections/slideshow/index.tsx
Added props to `Slideshow`:
- `playOnInit`
- `showDescription`
- `showCta`
- `variant`, `size`, and `shape` to `cta`
Added css variables to `Slideshow` for future theming.
Verified on homepage.
=> feat: add props and css variables to `Slideshow`

core/app/globals.css, core/vibes/soul/primitives/carousel/index.tsx
In preparation for the Makeswift integration and theming features, I've added:
- `colorScheme` to arrows and scrollbar elements of `Carousel`.
- CSS variables for all colors in `Carousel`
Visually verified on homepage.
=> feat: add props and css variables to `Carousel`

.changeset/proud-taxis-smoke.md, core/auth.ts
Use the new enhancement to the `login()` mutation to assign the guest cart to the customer at the moment of login, which avoids an extra GQL request for this and simplifies the code.
A similar enhancement is coming soon to logout but will be a separate PR.
https://github.com/user-attachments/assets/b3b9fa00-0eac-448e-807f-8616e3c5624f
=> Assign cart to customer as part of login mutation

core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/vibes/soul/sections/blog-post-content/blog-post-content.tsx, core/vibes/soul/sections/blog-post-content/index.ts
- Add `blog-post-content` vibes component into catalyst
- Use `BlogPostContent` component on the blog post page (`/blog/[blogId]`)
1. Ensure blog post content displays as expected
2. Ensure author can be blang
3. Ensure breadcrumbs link to the correct URL
4. Ensure blog tags link to the correct URL
https://github.com/user-attachments/assets/d7e5bf30-4100-4baa-9c6e-ff774b631c1d
=> feat: add BlogPostContent to blog/[id] page

core/app/[locale]/(default)/blog/page-data.ts, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx, core/vibes/soul/primitives/blog-post-card/index.tsx, core/vibes/soul/sections/blog-post-content/blog-post-content.tsx, core/vibes/soul/sections/blog-post-list/index.tsx, core/vibes/soul/sections/featured-blog-post-list/index.tsx
- Use `FeaturedBlogPostList` component on `/blog` page
- Update code to use streamable props for blog posts
- Optimized page-data to separate blog info from blog posts. This is more efficient, since we don't need to fetch the blog name/description on every request.
Blog functionality works as expected when using the `FeaturedBlogPostList` component
https://github.com/user-attachments/assets/8a7fbe48-874c-4e0f-8cde-7705f079e673
**Updated:**
`object-cover` ensures image is not stretched:
=> feat: add FeaturedBlogPostList to /blog

core/app/[locale]/(default)/[...rest]/page.tsx, core/lib/makeswift/client.ts, core/lib/makeswift/index.ts, core/lib/makeswift/page.tsx, core/package.json, pnpm-lock.yaml
Implements "userland" RSC `Page` component and related API abstractions as discussed [here](https://makeswifthq.slack.com/archives/C014SCS4G75/p1734553802046819?thread_ts=1734538843.665429&cid=C014SCS4G75) and [here](https://makeswifthq.slack.com/archives/C080BNSNEG7/p1734401070722499?thread_ts=1734384162.728269&cid=C080BNSNEG7).
https://github.com/user-attachments/assets/fcb2c2a1-ccee-46aa-95ce-31baeec92343
=> refactor(makeswift): userland RSC `Page` component etc.

core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
Fix max widths not being applied to sticky sidebar sections
=> fix: section max width

core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/blog/tag/[tagId]/page.tsx, core/data-transformers/page-info-transformer.ts, core/vibes/soul/primitives/breadcrumbs/index.tsx, core/vibes/soul/sections/featured-blog-post-list/index.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/products-list-section/filters-panel.tsx, core/vibes/soul/sections/products-list-section/index.tsx
- Added breadcrumbs to `/blog` and `/blog/tag/[tagId]` routes - when testing yesterday I realized that there was not an easy way to navigate after filtering for a blog tag
- Added `CursorPagination` to `FeaturedBlogPostList`
- Refactored `CursorPagination` component and its uses, as I noticed we were using `suspense`, even though the component already uses suspense internally. 
- Created utility function to transform GraphQL pagination info into the `CursorPaginationInfo` type
https://github.com/user-attachments/assets/2224741c-2d9e-4d0a-8771-ed82bcab5694
=> feat: add pagination and breadcrumbs to /blog and /blog/tag/[tagId]

core/data-transformers/page-info-transformer.ts
In my last PR, I realized there was a small oversight. We should return `null` for startCursor/endCursor if there is no previous or next page.
Confirmed cursor pagination is fixed
=> fix: ensure page info transformer returns null if no previous/next page

core/lib/makeswift/components/site-header/site-header.client.tsx, core/lib/makeswift/components/site-header/site-header.makeswift.tsx
Add `bannerId` to `site-header` to allow users to make a new banner. This is needed because we use the `bannerId` to determine whether users have dismissed the banner.
https://github.com/user-attachments/assets/d54c8985-8300-479f-99c7-6c17a311ac5b
=> feat: add banner id to site-header

core/app/[locale]/(default)/blog/page.tsx, core/messages/en.json, core/vibes/soul/sections/blog-post-list/index.tsx, core/vibes/soul/sections/featured-blog-post-list/index.tsx
- Sync BlogPostList with `vibes` changes for empty blog post state
- Implement it in the `/blog` route
=> feat: add empty state to BlogPostList

core/app/[locale]/layout.tsx, core/app/fonts.ts
We want to be able to import the fonts elsewhere, plus this arrangement matches Next.js examples as well: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#using-multiple-fonts
There are no semantic changes in this PR.
https://github.com/user-attachments/assets/bf2831ec-cb79-48c3-be69-ed52ac5bba80
=> refactor: move app fonts from root layout to their own file

core/vibes/soul/form/select/index.tsx, core/vibes/soul/sections/products-list-section/index.tsx, core/vibes/soul/sections/products-list-section/sorting.tsx
- Adds `aria-label` into Radix `SelectPrimitive.Trigger`
- Moves `placeholder` to `SelectPrimitive.Value`
- Add `placeholder` to prop to parent component
Reference: [Radix Select Docs](https://www.radix-ui.com/primitives/docs/components/select#with-a-placeholder)
Locally
=> fix: aria-label and placeholder in Select

core/vibes/soul/primitives/logo/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/footer/index.tsx
TLDR; Added a `height` prop to the `Logo` primitive and corresponding props to the `Navigation` and `Footer`. 
Previously, the logo height in the `Navigation` was being driven by a hardcoded height of `h-14` on the root element, and then `h-full` on the `Logo`. In the footer can't make this assumption which reveals we shouldn't be assuming there will always be an inferable height for the logo. Instead, I've decided to add a `height` prop to the logo and refactored the `Navigation` component to always include `8px` of padding to the y-axis so that users can better control the aspect ratio and size of their logo. I also added this to the `Footer` for the same reasons.
@fikrikarim we'll need to add these properties to the `Site Header` and `Site Footer` Makeswift components too.
=> feat: add height prop to Logo

core/app/[locale]/(default)/product/[slug]/page.tsx, core/vibes/soul/sections/product-detail/index.tsx
- Updated specifications to use CSS `grid`
- Replaced `ul` and `li` tags with `dl`, `dt` and `dd` tags. Grouped using `div` as per [spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element) allows.
- Reduced column spacing on smaller screens for PDP gallery / details per @andrewreifman request.
https://github.com/user-attachments/assets/e6822cf7-597f-49c1-9a26-1da612ce1860
=> fix: use grid for PDP specifications

.changeset/large-planes-reflect.md, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/commands/init.ts, packages/create-catalyst/src/utils/auth.ts, packages/create-catalyst/src/utils/cli-api.ts, packages/create-catalyst/src/utils/config.ts, packages/create-catalyst/src/utils/https.ts, packages/create-catalyst/src/utils/login.ts, packages/create-catalyst/src/utils/write-env.ts, pnpm-lock.yaml
- Update CLI to use OCC APIs
- Restructuring & simplifying code
- Use new OCC client ID
- Add sample data prompt
- Create `.catalyst` file with store hash/access token after login action to be used for other CLI commands without re-prompting for login
- Ensure CLI-created storefronts have the same end state in the control panel as storefronts created in the control panel
- Various UX improvements like automatically opening the device auth URL
Create wizard (the extraneous log statement is not there in this actual PR)
https://github.com/user-attachments/assets/4b173c35-000f-4724-8c86-92f4f685b091
Starting from app (I invalidated these credentials before posting this)
https://github.com/user-attachments/assets/368e8a4d-e578-4f25-b92d-2a6df7c38a63
Init command …
=> Improve CLI user experience & create continuity between control panel and CLI

core/lib/makeswift/components/site-footer/site-footer.client.tsx, core/lib/makeswift/components/site-footer/site-footer.makeswift.tsx, core/lib/makeswift/components/site-footer/site-footer.tsx, core/lib/makeswift/components/site-header/site-header.client.tsx, core/lib/makeswift/components/site-header/site-header.makeswift.tsx
- Cherry-picked Alan's commit that updates the components. I'll drop this commit once we rebase the `soul/integrations/makeswift` branch.
- Add height prop to `site-footer` and `site-header`. This fixes the issue of the logo not showing on the footer.
- Make the prop of a Shape control required. Makeswift supports this by default.
- Add default values to `height` and `weight` that match the VIBES default values.
- Move the banner `id` prop to be after `allowClose`.
- Rename and move some variables.
https://github.com/user-attachments/assets/8a2d3c24-21a3-4439-9f35-3b1d770e2857
=> Add height prop to site-footer and site-header and fix some issues

core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx, core/data-transformers/facets-transformer.ts, core/messages/en.json, core/vibes/soul/form/checkbox/index.tsx, core/vibes/soul/form/range-input/index.tsx, core/vibes/soul/primitives/accordions/index.tsx, core/vibes/soul/primitives/products-list/index.tsx, core/vibes/soul/sections/products-list-section/filters-panel.tsx, core/vibes/soul/sections/products-list-section/index.tsx
This PR brings in the latest changes for PLPs from the Soul VIBE:
- Adds new translated labels for product card compare, filters panel title, range filter apply button, and reset filters button
- Fixes min value for price filter
- Refactors range input to fix interaction edge cases that would result in a crash due to NaN values as well as the apply button not being disabled when it had to be and values not being clamped correctly
- a11y improvements to compare checkbox, range input, accordion, and product list section filters
- Fix accordion default open state
https://github.com/user-attachments/assets/d77e0e92-808f-4566-a0e9-474ab652b95e
=> Bring in latest PLP changes from Soul VIBE

core/package.json, pnpm-lock.yaml
Update to the latest version of Makeswift runtime to bring in a fix for duplicated elements after fast refresh. Note that, as evident in the video below, there are other issues with fast refresh that still need to be fixed.
https://github.com/user-attachments/assets/ab1c6994-771b-44a2-92f2-54903e215faa
=> fix: fast refresh doesn't duplicate elements in Makeswift

core/lib/makeswift/components/site-header/site-header.client.tsx, core/lib/makeswift/components/site-header/site-header.makeswift.tsx
Making site header props more organized/manageable.
Companion PR for the footer: https://github.com/bigcommerce/catalyst/pull/1834
https://github.com/user-attachments/assets/2d233521-562e-4ee6-a118-14a88f7165c9
=> fix(site header): move banner & logo props into popovers, add group titles etc.

core/lib/makeswift/components/site-footer/site-footer.makeswift.tsx
Making footer header props more organized/adjusting props terminology to better match code/semantics.
Companion PR for the header: https://github.com/bigcommerce/catalyst/pull/1833
https://github.com/user-attachments/assets/fbdeaba4-9c72-4cfb-8857-e4a5cd8eb4cf
=> fix(site footer): move the logo into a popover, add/edit labels etc.

core/lib/makeswift/components/button-link/button-link.makeswift.tsx, core/lib/makeswift/components/carousel/carousel.makeswift.tsx, core/lib/makeswift/components/products-carousel/products-carousel.makeswift.tsx, core/lib/makeswift/components/section/section.makeswift.ts, core/vibes/soul/sections/slideshow/index.tsx
=> Makeswift integration QA fixes

core/app/[locale]/(default)/product/[slug]/page.tsx, core/data-transformers/product-options-transformer.ts, core/messages/en.json
Fixes an accessibility issue of missing labels.
Lighthouse no longer mentions this issue.
=> fix: add missing labels to number input

.changeset/fresh-pens-accept.md, .changeset/little-seals-carry.md, .changeset/wise-hats-drive.md, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/utils/clone-catalyst.ts, packages/create-catalyst/src/utils/login.ts
Set default ghref to use the latest tag, so that CLI users will not be exposed to canary code by default.
Ran `create` with no args:
Ran `create` with `--reset-main`:
Ran `create` with a `--gh-ref` and `--reset-main`:
=> Set default ghref for CLI to @bigcommerce/catalyst-core@latest

.changeset/tidy-stingrays-search.md
Add a changeset to the branch to eventually merge into canary.
=> chore: add changeset

.github/CODEOWNERS
Remove group from codeowners for the canary merge.
=> chore: remove @bigcommerce/makeswift group from codeowners

core/app/[locale]/(default)/[...rest]/page.tsx
In the current Next.js canary version we're using, when PPR is enabled, returning empty parameters from `generateStaticParams` results in an error:
```
[Error: A required root parameter (locale) was not provided in generateStaticParams for /[locale]/[...rest], please provide at least one value.]
```
Locally ran `next build` while returning `[{ rest: [''], locale: defaultLocale }]` from `generateStaticParams`.
Also tested by deploying OCC with only the Makeswift homepage, which results in the parameters being empty. @bookernath tested this with me.
=> fix: handle empty root params Makeswift catch-all

core/package.json, pnpm-lock.yaml
This release contains fixes for the 404 revalidation issue with `revalidateTag`. https://github.com/vercel/next.js/pull/74577
One quirk about the issue is that this issue only appears when Next.js returns 404 as the HTTP status. Sometimes PPR will return 200 HTTP status even though we throw `notFound` inside a page. [Related docs](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming#status-codes).
To be able to reproduce this issue locally, I need to revert the [temporary cookies() error commit](https://github.com/bigcommerce/catalyst/pull/1856). Otherwise, the not found page will have 200 as the HTTP status, and won't have this issue in the first place.
Before
https://github.com/user-attachments/assets/9833cef8-60f3-4a80-8726-1cdcfdb578eb
After …
=> chore: upgrade next to 15.2.0-canary.1

core/lib/makeswift/components/carousel/carousel.makeswift.tsx
This was causing HTML hydration error when we put a button inside the carousel: 
```
In HTML, <a> cannot be a descendant of <a>.
```
We also don't want the carousel item to be inside a link.
Before
https://github.com/user-attachments/assets/57e310ca-7761-4b54-a2c1-95cc9c6f86cf
After
https://github.com/user-attachments/assets/0b087a43-4857-49a8-bd32-b9563a7ed9af
=> fix: remove link prop from carousel

core/app/[locale]/(default)/product/[slug]/page.tsx, core/lib/makeswift/component.tsx, core/lib/makeswift/components.ts, core/lib/makeswift/components/product-detail/client.tsx, core/lib/makeswift/components/product-detail/index.tsx, core/lib/makeswift/components/product-detail/register.ts, core/vibes/soul/lib/streamable.tsx, core/vibes/soul/primitives/products-list/index.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/products-list-section/index.tsx
Make product detail page visually editable.
https://github.com/user-attachments/assets/c210f664-8145-403c-b792-e104d2e10612
=> feat: visually editable PDP

core/components/header/index.tsx, core/package.json, pnpm-lock.yaml
This fixes 500 error:
```
needs to bail out of prerendering at this point because it used cookies()
```
Without the lazy promise, the `getCartCount()` is immediately executed, and calls `cookies()` on the Header.
With lazy promise, the `getCartCount()` execution is deferred, until `await`/`then` is used.
This bug was only reproducible if we reverted the [temporary fix commit](https://github.com/bigcommerce/catalyst/pull/1856) on the `soul/makeswift/integration` branch. See this [deployment](https://vercel.com/bigcommerce-platform/catalyst-soul/BmZk2nfaemBus1EQzeJP5JrCGcH2).
Makeswift pages are PPRed correctly instead of being server-rendered
```
@bigcommerce/catalyst-core:build: ├ ◐ /[locale]                                  1.8 kB          441 kB
@bigcommerce/catalyst-core:build: ├   ├ …
```
=> fix: use lazy promise on getCartCount to defer cookies() execution

core/package.json, pnpm-lock.yaml
Upgrade to the latest Makeswift runtime with [this fix](https://github.com/makeswift/makeswift/pull/905). Note that this doesn't make the site search functional (the search dropdown disappears before user can see any search results/take an action), but it does resolve the 500 error.
https://github.com/user-attachments/assets/1d7f3967-538e-49b8-97ee-9a104f859524
=> fix: do not crash on attempt to search while in the builder

core/lib/makeswift/page.tsx
- After we correctly use PPR, the non-published pages are not editable in the builder.
- We're still investigating the root cause of the issue. [Discussion link](https://makeswifthq.slack.com/archives/C07DAL1D8JK/p1736505188282539).
- We have this temporary solution so we can cut a stable release for the `integrations/makeswift` branch.
https://github.com/user-attachments/assets/611c3ece-c1a3-4e84-8a6c-c0b5bd60a8fa
=> Temporary fix on Page to allow editing of non-published pages

core/app/[locale]/(default)/webpages/_components/web-page.tsx, core/app/[locale]/(default)/webpages/normal/[id]/page.tsx
Add Web Page component from vibes. This is only the first iteration.
- Add support for nested web pages with children, and a way to navigate between them. This will bring full feature parity with BigCommerce.
=> Add Web Pages from vibes

core/vibes/soul/primitives/carousel/index.tsx, core/vibes/soul/primitives/products-carousel/index.tsx, core/vibes/soul/sections/featured-blog-post-list/index.tsx, core/vibes/soul/sections/featured-products-carousel/index.tsx, core/vibes/soul/sections/section-layout/index.tsx, core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
Added a `hideOverflow` prop to the carousel and section components.
By default, the `Carousel` will hide it's own overflow. In order to create the effect that is present in the designs for Soul, where the carousels appear to "overflow" off the screen, we need to move the overflow clipping up to the section so we can retain the left padding. To do this, we've added a way to toggle overflow visibility on sections independently from the `Carousel`. The sections will default to overflow visible.
I've decided to make this a boolean prop called `hideOverflow` instead of `overflow: 'visible' | 'hidden'` due to the semantic intent of the prop. Given there are many options for the CSS `overflow` property I don't want to confuse users with additional values that don't have an intended use case.
In …
=> fix: add hideOverflow to sections and carousels

core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
When using an Image inside of a `StickySidebarLayout` a min width was being set preventing it from shrinking in a flex layout. This PR fixes this by setting a min width of 0 on the columns in the `StickySidebarLayout` component.
=> fix: sticky sidebar layout overflow

core/vibes/soul/primitives/navigation/index.tsx
Improved the styles of the navigation menu by removing dividers, shrinking text of group links, adding a max width, and increasing columns to 5.
=> fix: remove dividers in nav

core/app/api/makeswift/[...makeswift]/route.ts
Makeswift API route needs a components import, otherwise it won't know about any of the custom components and won't be able to introspect them/replace the resources. See [this thread](https://makeswifthq.slack.com/archives/C014SCS4G75/p1736555455966869) for more context.
The typography resource inside of a `section-layout` component is not replaced:
The typography resource is correctly replaced:
=> fix: element tree introspection on Makeswift API routes

.changeset/popular-ducks-bake.md, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/account/layout.tsx, core/app/[locale]/(default)/webpages/contact/[id]/page.tsx, core/app/[locale]/layout.tsx, core/app/[locale]/maintenance/page.tsx
While working on adding locale dropdown, I noticed we are inconsistent with the use of `setRequestLocale`.
- No needed in metadata.
- Removed from pages that are no longer static (we need to fix this in different PR)
- Added to pages that are static or PPR.
=> chore: use setRequestLocale only where needed

.changeset/plenty-jokes-learn.md, core/components/link/index.tsx, core/package.json, pnpm-lock.yaml
- Remove explicit locale override in Link component that was prepending default locale to links even with the 'as-needed' mode.
- Bump `next-intl`.
Links in default locale no longer get prepended `/en` prefix, while non default locale links do have their corresponding locale prefix.
Default locale:
ES locale:
=> fix(core): remove explicit locale override in Links

core/components/header/_actions/switch-locale.ts, core/components/header/index.tsx, core/messages/en.json
Add locale switcher to the Header, using server action and `redirect`. In this use case we need to revalidate the `/` to make sure the cookies get updated with the new locale. We also had to workaround an issue by redirecting to the `/en` when the default locale is used.
Locale switcher works as expected.
https://github.com/user-attachments/assets/b78fcca2-1fc5-4608-b2e9-517797fcafab
=> feat(core): add locale switcher to Header

.changeset/gold-ducks-tie.md, core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts, core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts, core/app/[locale]/(default)/cart/_actions/remove-item.ts, core/app/[locale]/(default)/cart/_actions/update-quantity.ts, core/app/[locale]/(default)/cart/page-data.ts, core/app/[locale]/(default)/cart/page.tsx, core/app/[locale]/(default)/compare/_actions/add-to-cart.ts, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/page.tsx, core/app/[locale]/(default)/product/[slug]/_actions/add-to-cart.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-schema/fragment.ts, core/app/[locale]/(default)/product/[slug]/page-data.ts, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/not-found.tsx, core/auth/index.ts, core/client/fragments/pricing.ts, core/components/header/_actions/switch-currency.ts, core/components/header/fragment.ts, core/components/header/index.tsx, core/components/header/schema.ts, core/lib/cart.ts, core/lib/currency.ts, core/messages/en.json, core/vibes/soul/primitives/navigation/index.tsx
- Adds currency selector following the same pattern used for locale selector
- Establishes new `currencyCode` httpOnly cookie
- New lib functions to customize/extend currency selection
- Moved cart to a lib as well while I was at it
- Decorates all queries that touch pricing to include currency code
- ... except Cart and Orders, as currency lives on those models directly
Only transactional currencies are supported for now, because we don't have a way to render prices for the cart for a display currency from the API. Theoretically we could use the exchange rate we have access to in the API to calculate the prices within next.js, but my preference would be for all monetary values, even estimates, to come from the API. So for now, I have filtered the list of currencies to only the …
=> feat(core): Add currency selector to header

.changeset/ninety-files-begin.md, .changeset/warm-drinks-think.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx, core/app/[locale]/(default)/blog/[blogId]/page-data.ts, core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/app/[locale]/(default)/blog/page-data.ts, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/cart/page-data.ts, core/app/[locale]/(default)/cart/page.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/(default)/webpages/[id]/contact/page-data.ts, core/app/[locale]/(default)/webpages/[id]/normal/page-data.ts, core/components/header/_actions/search.ts
- Dedupe requests in various pages by properly caching/memoizing the function per page render.
- Fix an issue with quick search result.
Tested and see less function calls that call `fetch`.
=> fix(core): dedupe requests in various pages

.changeset/fuzzy-beds-lick.md, core/app/[locale]/(default)/(auth)/change-password/_actions/change-password.ts, core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts, core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts, core/app/[locale]/(default)/account/settings/_actions/update-customer.ts, core/app/[locale]/(default)/cart/page-data.ts, core/app/[locale]/(default)/webpages/[id]/layout.tsx, core/app/favicon.ico/route.ts, core/app/robots.txt/route.ts, core/auth/index.ts, core/components/header/_actions/switch-currency.ts, core/middlewares/with-routes.ts
Noticed some queries/mutations were not using the standardized naming. I feel it may seem redundant in many cases, but we either we have all named the same or we remove the trailing `Query`/`Mutation`.
Nothing changes.
=> chore(core): rename query/mutations to standard names

core/middlewares/with-makeswift.ts
The URL search param is only set on the very first request. For the proxy to work as intended, the `x-makeswift-draft-mode` header must be used to determine whether to proxy Draft Mode or not.
https://github.com/user-attachments/assets/475ac733-4d7c-47d9-8e84-6db712d1ed58
=> fix: use x-makeswift-draft-mode header for proxy

.changeset/tidy-lobsters-compete.md, core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts
This is a mistake. Thanks @bookernath for pointing it out. Not sure how it happened.
=> fix: remove unecessary fetchOptions in object

.changeset/silver-numbers-divide.md, core/client/mutations/create-cart.ts
Set the currency from the preferred currency cookie as part of the cart creation call.
https://github.com/user-attachments/assets/fea8f89f-2abd-441f-b2ef-ce66590746e7
=> Set currency on cart at creation time

core/package.json
It's confusing to customers (and our telemetry) that the version number in package.json is still <1.0.
Manually updating it for now; once we are out of RC this will be set automatically by changesets or CI/CD.
N/A
=> Manually update version number in package.json to indicate 1.0.0-rc

.changeset/flat-kiwis-design.md, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/messages/en.json
Properly look for the type of error we get from next-auth and show the correct message when credentials are invalid.
=> fix(core): handle invalid credentials error message in Login

.changeset/seven-flies-wonder.md, core/lib/makeswift/components/accordions/accordions.makeswift.tsx, core/lib/makeswift/components/card-carousel/card-carousel.makeswift.tsx, core/lib/makeswift/components/carousel/carousel.makeswift.tsx, core/lib/makeswift/components/product-card/product-card.makeswift.tsx, core/lib/makeswift/components/product-detail/register.ts, core/lib/makeswift/components/products-carousel/products-carousel.makeswift.tsx, core/lib/makeswift/components/products-list/products-list.makeswift.tsx, core/lib/makeswift/components/site-footer/site-footer.makeswift.tsx, core/lib/makeswift/components/site-header/site-header.makeswift.tsx, core/lib/makeswift/components/site-theme/components/accordion.ts, core/lib/makeswift/components/site-theme/components/button.ts, core/lib/makeswift/components/site-theme/components/card.ts, core/lib/makeswift/components/site-theme/components/carousel.ts, core/lib/makeswift/components/site-theme/components/footer.ts, core/lib/makeswift/components/site-theme/components/header/banner.ts, core/lib/makeswift/components/site-theme/components/header/index.ts, core/lib/makeswift/components/site-theme/components/header/nav.ts, core/lib/makeswift/components/site-theme/components/logo.ts, core/lib/makeswift/components/site-theme/components/price-label.ts, core/lib/makeswift/components/site-theme/components/product-card.ts, core/lib/makeswift/components/site-theme/components/section.ts, core/lib/makeswift/components/site-theme/components/slide-show.ts, core/lib/makeswift/components/site-theme/register.ts, core/lib/makeswift/components/slideshow/slideshow.makeswift.tsx, core/package.json, pnpm-lock.yaml
Upgrade `@makeswift/runtime` to the [latest official release](https://github.com/makeswift/makeswift/releases).
https://github.com/user-attachments/assets/3b3e004f-2213-43e4-bb4e-b183091225b4
=> chore: upgrade `@makeswift/runtime` to 0.23.3

core/package.json, pnpm-lock.yaml
Bump to latest canary
CI/CD and preview
=> Bump canary to .33

.github/ISSUE_TEMPLATE/🐞📝-bug-report-makeswift.md
This adds a bug report template that is more specific to Makeswift. Right now, it is pretty similar to the existing bug report, but this gives us the ability to evolve this one separately as needed and also track issues with Makeswift more easily.
=> Makeswift bug template

.changeset/tame-trains-dance.md, core/lib/makeswift/components/site-theme/components/index.ts, core/lib/makeswift/components/site-theme/components/price-label.ts, core/lib/makeswift/components/site-theme/to-css.ts
Price label color changes had no effect because of the CSS variables mismatch.
=> fix: rename price label's prop to match its CSS variables' prefix

.changeset/spotty-seahorses-type.md, core/i18n/routing.ts
Override `next-intl`'s default cookie options to ensure that the `NEXT_LOCALE` cookie is set when a Catalyst site is loaded in the Makeswift Builder. See [this document](https://www.notion.so/makeswift/iframe-cookies-1886f737ce30809595a8dd7bffbf79a6) for additional context.
=> fix: configure `NEXT_LOCALE` cookie to work in the builder

core/components/image/index.tsx, core/lib/store-assets.ts, core/next.config.ts
This BIGCOMMERCE_CDN_HOSTNAME variable is supposed to indicate the allowlisted hostname for the bigcommerce CDN, in the case of using Catalyst against a non-production environment. However, it was not exposed to the image client component because it was not prefixed with NEXT_PUBLIC_, so this PR renames the env var in order to allow it to work in a client component.
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser
Tested locally against a non-production CDN URL
=> Update BIGCOMMERCE_CDN_HOSTNAME to NEXT_PUBLIC_BIGCOMMERCE_CDN_HOSTNAME

.changeset/dry-dragons-burn.md, core/auth/index.ts
Configure NextAuth cookies to ensure they are set when a Catalyst site is loaded in the Makeswift Builder. See [this document](https://www.notion.so/makeswift/iframe-cookies-1886f737ce30809595a8dd7bffbf79a6) for additional context.
Related: https://github.com/bigcommerce/catalyst/pull/1959
=> fix: configure NextAuth cookies to work inside the builder

core/app/[locale]/(default)/product/[slug]/_components/reviews.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/data-transformers/page-info-transformer.ts, core/vibes/soul/sections/reviews/index.tsx
Handles pagination parameters in PDP `Reviews` component.
https://github.com/user-attachments/assets/10ab8d36-1cd0-478d-80b7-4e496aed7796
=> fix: pagination for PDP reviews

.changeset/new-books-drop.md, core/middlewares/with-routes.ts
Fix `withRoutes` middleware to properly rewrite localized home page routes (`/fr`, `/es-MX`, etc.)
https://github.com/user-attachments/assets/e52ab236-5ff1-4ce4-add2-42bc8bc926b0
https://github.com/user-attachments/assets/88b973e1-ec24-41bb-bb19-2e3c6e169936
=> fix: localized home page routes are rewritten to the "catch all" page

.changeset/hip-countries-tap.md, core/app/[locale]/(default)/cart/page.tsx
Add cart discounts to summary in Cart.
I don't have discounts set up but this follows the previous pattern in prelude.
=> feat(core): add discounts summary item to Cart

.changeset/wet-rings-unite.md, core/middlewares/with-makeswift.ts
Support switching of the page's locale through the Makeswift Builder.
https://github.com/user-attachments/assets/0d03eedb-387a-4e4d-a847-74eeea9b5e7c
https://github.com/user-attachments/assets/8350e8d1-c445-4882-86ce-299318d47ff6
=> fix: `NEXT_LOCALE` cookie interferes with the builder's locale switcher

README.md
Moving the demo links into the README as we changed the entrypoint link in Github.
Documentation changes.
=> chore: add demo section to readme

.changeset/short-lies-draw.md, packages/create-catalyst/package.json, packages/create-catalyst/src/commands/create.ts, packages/create-catalyst/src/prompts/multi-select/helpers.ts, packages/create-catalyst/src/prompts/multi-select/index.ts, packages/create-catalyst/src/prompts/multi-select/multi-select.ts, packages/create-catalyst/src/prompts/multi-select/types.ts, packages/create-catalyst/src/utils/cli-api.ts, packages/create-catalyst/src/utils/localization.ts, packages/create-catalyst/tsconfig.json, pnpm-lock.yaml
Manage locales via CLI when creating a channel.
To rich a goal I created multi-select solution to select additional locales.
To enable the selection of multiple locales, a custom multi-select component is required with the following features:
- **Multiple Selection**: Users must be able to select more than one locale.
- **Search Functionality**: Due to the extensive list of available locales, a search feature is essential for efficient navigation and selection.
- **Selection Limit**: A maximum of five locales per channel is permitted. The component should enforce this limit and provide clear feedback to the user when they attempt to exceed it.
- **Informative Tooltips**: Helpful tooltips should be displayed to guide users and provide additional context about each locale.
No one of …
=> feat: manage locales when creating storefronts from the CLI

core/app/[locale]/(default)/(auth)/login/forgot-password/_actions/reset-password.ts, core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts
We were incorrectly looking for registration errors in the wrong object of the response. With this change, we actually show a correct error response and short-circuit the login flow.
Error messages display from response correctly.
=> fix(core): handle registration errors in form

.changeset/gentle-seals-sing.md, packages/create-catalyst/src/utils/localization.ts
Add es-419 to list of allowed locale for selecting in CLI
=> feat: add es-419 to list of allowed locale for selecting in CLI

.gitignore, packages/cli/.eslintrc.cjs, packages/cli/README.md, packages/cli/package.json, packages/cli/prettier.config.cjs, packages/cli/src/commands/version.ts, packages/cli/src/index.ts, packages/cli/src/program.ts, packages/cli/tests/commands/version.spec.ts, packages/cli/tests/index.spec.ts, packages/cli/tsconfig.json, packages/cli/tsup.config.ts, packages/cli/vitest.config.ts, pnpm-lock.yaml
Scaffolds a new CLI package
Vitest setup
=> feat(cli): scaffold package

.changeset/shiny-insects-swim.md, core/app/[locale]/(default)/cart/page-data.ts, core/app/[locale]/(default)/cart/page.tsx
The `cart.discounts` array can return N number of discounts (one for each item, for example). This is not very useful and it is better to show the total sum, however this total sum does not account for coupon discounts. Use `cart.discountedAmount` and sum `checkout.coupons` to show as a separate summary item. Hide these summary items if they are 0.
Discounts show accordingly on the right summary item.
=> fix(core): show coupon discounts as a separate summary item

.changeset/cold-poets-refuse.md, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts, core/app/login/token/[token]/route.ts, core/auth/customer-login-api.ts, core/auth/index.ts, core/next.config.ts, core/tests/fixtures/utils/account/delete.ts, core/tests/fixtures/utils/order/delete.ts, core/tests/ui/components/radio-group.spec.ts, core/tests/ui/components/swatch.spec.ts, core/tests/ui/e2e/order-details.spec.ts, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/account-settings-section/change-password-form.tsx, core/vibes/soul/sections/header-section/index.tsx, core/vibes/soul/sections/product-detail/schema.ts
Updates the sign in behavior to use different providers instead of relying on a single provider. This is prework to in order to properly handle session syncing.
Also added some folders to be linted by `next lint` and fixed them: https://github.com/bigcommerce/catalyst/pull/2103/commits/77634f9c8c734337ff731417a839cbc8c83a4c2a
=> refactor: update signin behavior to use different providers

core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx, core/app/[locale]/(default)/blog/[blogId]/page.tsx, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/webpages/[id]/_components/web-page.tsx, core/app/[locale]/(default)/webpages/[id]/contact/page.tsx, core/app/[locale]/(default)/webpages/[id]/normal/page.tsx, core/data-transformers/breadcrumbs-transformer.ts, core/vibes/soul/sections/blog-post-content/index.tsx, core/vibes/soul/sections/breadcrumbs/index.tsx, core/vibes/soul/sections/featured-blog-post-list/index.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/products-list-section/index.tsx
Sync `Breadcrumbs` component with VIBES. Breadcrumbs shouldn't have an `id` property on them, and have since been removed.
Locally, build passes
=> feat: Sync Breadcrumbs

.changeset/weak-candles-buy.md, core/lib/makeswift/utils/use-bc-product-to-vibes-product/use-bc-product-to-vibes-product.ts, core/lib/makeswift/utils/use-products.ts, core/vibes/soul/lib/streamable.tsx
Fix incidental rendering of `<ProductList />` elements, most visible when the page is edited in the builder.
https://github.com/user-attachments/assets/d4087405-12c9-4c37-9bd1-fefb807df35c
https://github.com/user-attachments/assets/dc687f9b-0b94-4de0-81d4-e748928f9098
=> fix: flicker on rerendering `<ProductList />`

core/auth/index.ts
- Adds some documation around CSRF checks and explicitly sets it to undefined. We want to ensure users handle CSRF checks if they need to roll their own sensitive actions as the next-auth/auth.js lib won't handle it for them if doing something custom.
- `trustHost` value is determined by an env var to ensure we can set it up when running `next build` & `next start` locally. Setting it to always be true is detrimental to cookie security when deploying the application to production, but is needed to be set to true when running on `localhost`.
N/A
=> chore(security): add documentation around CSRF checks

core/app/[locale]/(default)/compare/page.tsx, core/vibes/soul/primitives/compare-drawer/index.tsx
Reverts to the previous behavior by overriding the link generated in the compare drawer component.
Locally, ids use the `ids` search param in compare page.
=> fix(core): revert to ids search param in compare page

.changeset/itchy-ways-do.md, packages/client/src/client.ts
Add an `errorPolicy` option for GQL requests. Accepts `none`, `ignore`, `all`. Defaults to `none` which throws an error if there are GQL errors, `ignore` returns the data without error object, and `all` returns both data and errors.
=> feat(client): add errorPolicy option to GQL requests

.changeset/ten-pots-vanish.md, core/app/[locale]/(default)/(auth)/layout.tsx, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts, core/app/[locale]/(default)/account/layout.tsx, core/app/login/token/[token]/route.ts, core/auth/index.ts, core/lib/cart.ts, core/middlewares/with-auth.ts, core/vibes/soul/primitives/compare-card/add-to-cart-form.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx
This PR solves a two-fold:
1. Creates an anonymous session whenever a user navigates to a Catalyst page. This will allow us to store a bunch of information we need for shoppers and creates a consistent place to read customer-specific data from.
2. Moves reading/writing the cart id into the session. Regardless of if the session is an anonymous session or a logged-in shopper, the cart id will be tied to the session and can move freely between the two.
This is a better pattern to practice for security reasons. It makes it so attackers can't access the shoppers cart id without being validated by the Catalyst server.
https://github.com/user-attachments/assets/0e53a570-6d6f-4449-be0b-c1b153219d8a
https://github.com/user-attachments/assets/f6e94ed4-51df-4fdf-a6b4-98600975362d …
=> feat: add anonymous session with cart tracking

core/package.json, pnpm-lock.yaml
Bump next to 15.2.3 to address CVE
https://nextjs.org/blog/cve-2025-29927
Will be an out-of-band release to 0.x to allow customers using older versions of Catalyst to benefit
CI/CD and preview
=> Bump next to address CVE

.changeset/happy-moles-thank.md, core/app/[locale]/(default)/account/layout.tsx, core/app/[locale]/(default)/account/wishlists/[id]/page-data.ts, core/app/[locale]/(default)/account/wishlists/[id]/page.tsx, core/app/[locale]/(default)/account/wishlists/page-data.ts, core/app/[locale]/(default)/account/wishlists/page.tsx, core/app/[locale]/(default)/wishlist/[token]/page-data.ts, core/app/[locale]/(default)/wishlist/[token]/page.tsx
Add wishlist pages:
- `/account/wishlists`
- `/account/wishlists/[id]`
- `/wishlist/[token]`
Tested locally
https://github.com/user-attachments/assets/1a75a99d-566c-459b-86ce-96b2e5b63563
=> feat: Add wishlist pages

.changeset/rotten-pans-sneeze.md, core/app/[locale]/(default)/account/orders/[id]/page-data.tsx, core/app/[locale]/(default)/account/orders/page-data.ts, core/data-transformers/order-details-transformer.ts, core/data-transformers/orders-transformer.ts, core/vibes/soul/sections/order-details-section/index.tsx, core/vibes/soul/sections/order-list-section/order-list-line-item.tsx
- Set `errorPolicy` to ignore errors for order queries to fix thrown error when an order has deleted products with no valid paths and an error is returned.
- Make `href` optional for order products.
- If no `href` is passed, render a product without using a Link.
Locally, my product with no path renders without being a link and no error is thrown.
=> fix(core): ignore errors in orders and render products without links

.changeset/witty-suns-explode.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx, core/app/[locale]/(default)/account/wishlists/[id]/page.tsx, core/app/[locale]/(default)/account/wishlists/page.tsx, core/app/[locale]/(default)/blog/page.tsx, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/page.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/(default)/webpages/[id]/contact/page.tsx, core/app/[locale]/(default)/webpages/[id]/normal/page.tsx, core/app/[locale]/(default)/wishlist/[token]/page.tsx, core/components/header/index.tsx, core/vibes/soul/lib/streamable.tsx
Our `Streamable` pattern relies on passing promises as props to RSCs and client components. For RSCs, it "pushes down" data fetching so that Next.js will mark particular components as dynamic when using PPR. For client components, it streams the data to the client while triggering a Suspense boundary.
For the former case, we were getting the following error:
```
Unhandled Rejection: Error: Route /[locale]/category/[slug] needs to bail out of prerendering at this point because it used `await searchParams`, `searchParams.then`, or similar. React throws this special object to indicate where. It should not be caught by your own try/catch. Learn more: https://nextjs.org/docs/messages/ppr-caught-error
at P (.next/server/chunks/5884.js:1:42808)
at Object.get (.next/server/chunks/4019.js:4:32956) …
```
=> fix: add `Streamable.from` to avoid eager promises

.changeset/slow-dodos-ring.md, core/app/[locale]/layout.tsx
Adds the store hash to a meta tag for easily debugging merchants sites.
=> feat(core): add store hash meta tag

core/lib/makeswift/components/card/card.makeswift.tsx
- changes the default value for `textPostion` to `outside` for the `Card` component to avoid breaking changes for users that might have already created `Card` components
https://github.com/user-attachments/assets/2d4a35ae-7515-4c40-833f-596b6a5ba6b6
=> fix: textPosition defualt value set to outside

.changeset/violet-avocados-fail.md, core/package.json, pnpm-lock.yaml
Bumps the `@makeswift/runtime` to get the latest improvements and fixes
All changes were tested on a Catalyst host locally and through a Vercel deployment.
=> chore: upgrade makeswift runtime

.changeset/khaki-rice-design.md, core/app/[locale]/(default)/product/[slug]/page.tsx
Since we render the default image first, and append all of the images, this causes duplicate images in product. This fix dedupes the default image from the product gallery. 
Duplicate image is no longer present.
| Before | After |
| ------ | ------ |
| ![Screenshot 2025-03-27 at 2 37 19 PM](https://github.com/user-attachments/assets/861cb0f5-3e8c-4acc-9441-3a4ce4893110) | ![Screenshot 2025-03-27 at 2 40 10 PM](https://github.com/user-attachments/assets/d2bfaac7-325b-4869-aa97-740a26fc3b05) |
=> fix: dedupe default image in PDP

.changeset/loud-breads-jog.md, core/.eslintrc.cjs, core/build-config/schema.ts, core/build-config/writer.ts, core/components/image/index.tsx, core/lib/store-assets.ts, core/next.config.ts, core/package.json, pnpm-lock.yaml
Fetches the store urls on build and consumes it for CDN urls. This is some pre-work to validate urls coming from session-sync endpoints.
Also, fixes some eslint issues since `pnpm@10` resolved dependencies a little differently.
=> feat(core): add store urls to build-config.json

.changeset/bumpy-waves-behave.md, core/app/[locale]/(default)/cart/_actions/redirect-to-checkout.ts, core/app/[locale]/(default)/checkout/route.ts, core/messages/en.json
Moves triggering the redirect to checkout as a separate route handler. This will enable us to use the Sites/Routes API to set a checkout route to redirect to. This will be useful when we need to trigger session syncing by redirecting to the login page with a `/checkout` `redirectTo` query param.
=> refactor(core): move checkout redirect as a route

core/app/[locale]/(default)/product/[slug]/page.tsx, core/messages/en.json, core/messages/fr.json, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx
Add ability to localize default `Select` placeholder labels on the PDP page.
https://github.com/user-attachments/assets/c6c33493-8ae7-4096-801b-dcd675b52778
=> feat: localize empty select placeholders on the PDP page

.changeset/late-ends-nail.md, core/app/[locale]/(default)/(auth)/login/_actions/login.ts, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/checkout/route.ts
Add the ability to redirect from the login page. Developers can now append a relative path to the `?redirectTo=` query param on the `/login` page. When a shopper successfully logs in, it'll redirect them to the given relative path. Defaults to `/account/orders` to prevent a breaking change.
This functionality will be critical for redirecting a user back to checkout to ensure the session is synced between headless and checkout (stencil).
https://github.com/user-attachments/assets/06586442-0d67-465c-9398-27574546851e
=> feat(core): add the ability to redirect from login

core/components/wishlist/fragment.ts, core/data-transformers/wishlists-transformer.ts
Recent GraphQL schema changes made `product` field optional on the wishlist item type. This fixes the data transformer for this update.
Tested locally, build passes
=> Update wishlist transformer to account for updated schema

.changeset/slick-turtles-cry.md, core/app/[locale]/(default)/(auth)/logout/route.ts, core/auth/index.ts
Enables developers to redirect to a specific pathname after a user logs out. This enables us to session sync back to checkout when a user logs out.
https://github.com/user-attachments/assets/5662a0b2-bc32-48ef-bf8c-aff54f813ffa
=> feat(core): add the ability to redirect after logout

core/app/[locale]/(default)/product/[slug]/page-data.ts
Bump the number of product options and product option values loaded on the PDP to the largest number the API supports without pagination; this ensures product pages will load completely without missing options (up to these new limits).
Above these, pagination will be required, or changes to the API to increase limits further.
Before:
After:
=> Bump options and option values to 50/50

core/app/[locale]/(default)/(auth)/logout/route.ts
A miss from https://github.com/bigcommerce/catalyst/pull/2186/files#r2031310242 – adds the `.pathname` to only accept relative paths as the `redirectTo` value.
=> fix(core): add missing .pathname to only use relative paths

core/lib/makeswift/components.ts
Admin API key was removed from Catalyst for security purposes. A higher level API key is required to query Customer Groups for the Customer Group Slot. We need to unregister this component while we find a solution to this.
=> fix: temp unregister of Customer Group Slot

.changeset/eighty-nails-juggle.md, core/app/[locale]/(default)/product/[slug]/page-data.ts
Remove unused `variants` collection from the query used to build PDPs.
=> Remove unused variant fetch from query

core/vibes/soul/form/swatch-radio-group/index.tsx, core/vibes/soul/form/textarea/index.tsx, core/vibes/soul/form/toggle-group/index.tsx
- renames CSS vars that incorrectly start with `--border-contrast` to `--border`
- renames CSS vars that incorrectly use `--contrast-gray` to `--contrast`
=> fix: incorrect css vars for border and contrast-gray

.changeset/forty-pants-pump.md, core/globals.css
The following styles were applying on top of other styles, while they were specifically meant to only overwrite the `.prose` styles. This fixes them by scoping of the styles under the `.prose` and `@layer utilities` with the same generated styles the `tailwind-typography` plugin would generate. This creates a specificity that is higher than the generated classes, but easily overridable if needed.
>[!TIP]
>Hide whitespace https://github.com/bigcommerce/catalyst/pull/2209/files?diff=split&w=1
The styles at the top are our overrides.
=> fix(core): issues with styles not overriding prose

.changeset/tired-places-build.md, core/middlewares/with-makeswift.ts, core/package.json, pnpm-lock.yaml
This is a rework of https://github.com/bigcommerce/catalyst/pull/1984 that fixes the unintended page reload introduced by that PR. See [ENG-7924](https://linear.app/makeswift/issue/ENG-7924/unconditional-deletion-of-next-locale-cookie-triggers-page-rerender) for more details.
https://github.com/user-attachments/assets/8caf3611-4b6d-40db-9e61-b880e1ade156
=> fix: deletion of `NEXT_LOCALE` cookie triggers page rerender

.changeset/wise-humans-serve.md, core/middlewares/with-intl.ts, core/middlewares/with-makeswift.ts
Makeswift Builder's locale switcher expects the host to derive locale strictly from the URL. Disable cookie- and language-based locale detection when in draft mode to meet this expectation. Rework of https://github.com/bigcommerce/catalyst/pull/2213 and https://github.com/bigcommerce/catalyst/pull/1984.
https://github.com/user-attachments/assets/a3e1aac0-5cd6-475d-90f3-b5c19ac750f3
=> fix: disable locale detection in the builder

.changeset/swift-tips-wave.md, packages/client/src/client.ts
Adds the name of the GraphQL operation as a query parameter on the GraphQL URL, such as:
`/graphql?operation=HomePageQuery&type=query`
This improves observability in server logs, making it easier to tell queries apart without parsing the body.
In the future we may add `locale` as well.
Tested on preview deployment by observing logs.
=> Add operation name and type to graphQL URL for easier logging

core/app/[locale]/(default)/checkout/route.ts
Adding cart id as an optional search param in the checkout route - this will help with B2B payments of quotes and invoices since the buyer portal creates carts and checks out in the same submit event, this leads to issues with passing a cart id to the session in between. 
Tested in B2B while paying a quote and redirecting to catalyst checkout route.
No migration changes
=> feat(core): B2B-2562 cart id as optional search param in checkout route

.changeset/puny-radios-show.md, core/app/[locale]/not-found.tsx, core/vibes/soul/sections/not-found/index.tsx
We'd like to move in the direction of a static 404 page with just a search box instead of a featured products panel, in order to make 404 pages inexpensive to serve. This is particularly important because of [this issue.](https://github.com/vercel/next.js/issues/67532#issuecomment-2688292808)
This is the first step of that change which removes the featured products panel, the search box can be added in a separate PR.
=> fix: remove featured products from 404 page, allowing the page to be static

.changeset/nine-bikes-hunt.md, core/tailwind.config.js
Add `core/lib/makeswift/components` folder to tailwind config content property so that tailwind classes can be used in components there. If you happen to write a tailwind class in a component in this folder that hasn't been used elsewhere in the codebase, the tailwind class won't work. Tailwind needs to watch this folder in order to include classes used in the compiled css.
There are other components in this folder already using tailwind classes; for example: [the Basic / Accordions component](https://github.com/bigcommerce/catalyst/blob/9d07a7160270d77c1e52ddfadef2325816d928fc/core/lib/makeswift/components/accordions/accordions.makeswift.tsx#L27). The only reason those classes worked is because they're already used in the folders tailwind is watching.
Try using `p-10`(or another tailwind …
=> fix: add /lib/makeswift/components folder to tailwind.config.js

core/app/[locale]/layout.tsx, core/app/[locale]/not-found.tsx, core/vibes/soul/sections/not-found/index.tsx, core/vibes/soul/sections/section-layout/index.tsx
- updates NotFound Soul component
- adds `min-h-screen`, `flex`, & `flex-col` to the body to allow full-screen content when not enough content fills the page
- updates `SectionLayout` component
https://github.com/user-attachments/assets/e0ad1a71-70a0-4412-8b07-71cd957857ff
=> feat: update NotFound and SectionLayout

.changeset/fine-files-enjoy.md, core/app/[locale]/(default)/compare/page.tsx
Disables PPR in the Compare page to fix an issue of products disappearing when a product is added to cart. This happens due to a bug in Next.js when PPR is enabled that removes search params when a page is revalidated. More info: https://github.com/vercel/next.js/issues/59407
In production, products no longer disappear when added to cart.
Add `export const experimental_ppr = false;` to compare page.
=>  fix(core): disable ppr for compare page

.changeset/shiny-worlds-type.md, core/app/[locale]/layout.tsx, core/middlewares/with-makeswift.ts, core/next.config.ts, core/package.json, pnpm-lock.yaml
Upgrades `@makeswift/runtime`, which resolves an issue with editing SSGd Catalyst pages in Makeswift.
Manually tested locally and via Vercel deployments
=> feat: bump makeswift runtime to 0.24.0, simplify implementation

core/package.json, pnpm-lock.yaml
Bump next to 15.4.0-canary.0
We still require canary builds of Next until PPR is marked stable. Bumping to canary.0 allows our customers to get the full benefit of 15.3.1 while minimizing canary risk as there are only a few minor changes beyond 15.3.1:
https://github.com/vercel/next.js/releases/tag/v15.4.0-canary.0
=> Bump next to 15.4.0-canary.0

.changeset/salty-laws-hunt.md, core/app/[locale]/(default)/(faceted)/category/[slug]/page-data.ts, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/fetch-compare-products.ts, core/app/[locale]/(default)/(faceted)/fetch-faceted-search.ts, core/app/[locale]/(default)/product/[slug]/loading.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/messages/en.json
This refactor optimizes category PLP for caching and the eventual use of dynamicIO. With these changes we leverage data caching to hit mostly cache data for guest shoppers in different locales and with different currencies.
- We don't stream in Category page data, instead it's a blocking call that will redirect to `notFound` when category is not found. Same for metadata.
- Our query functions now take in all params required for fetching, instead of accessing dynamic variables internally. This is important to serialize arguments if we want to eventually `use cache`.
- Use `Streamable.from` to generate our streaming props that are passed to our UI components.
- Remove use of nuqs' `createSearchParamsCache` in favor of nuqs' `createLoader`.
- Update `/(facted)/category/[slug]/page.tsx`
- For …
=> refactor(core): category for dynamicIO 

.changeset/bitter-comics-cry.md, core/app/[locale]/(default)/(faceted)/fetch-compare-products.ts, core/app/[locale]/(default)/(faceted)/search/page.tsx
This refactor optimizes search PLP for caching and the eventual use of dynamicIO. With these changes we leverage data caching to hit mostly cache data for guest shoppers in different locales and with different currencies.
- We don't stream in Search page data, instead it's a blocking call to get page data.
- Our query functions now take in all params required for fetching, instead of accessing dynamic variables internally. This is important to serialize arguments if we want to eventually `use cache`.
- Use `Streamable.from` to generate our streaming props that are passed to our UI components.
- Remove use of nuqs' `createSearchParamsCache` in favor of nuqs' `createLoader`.
- Update `/(facted)/search/page.tsx`
- For this page we are now doing a blocking request for brand page data. Instead …
=> refactor(core): search for dynamicIO

.changeset/whole-signs-shine.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/page-data.ts, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/fetch-compare-products.ts, core/messages/en.json
This refactor optimizes brand PLP for caching and the eventual use of dynamicIO. With these changes we leverage data caching to hit mostly cache data for guest shoppers in different locales and with different currencies.
- We don't stream in Brand page data, instead it's a blocking call that will redirect to `notFound` when brand is not found. Same for metadata.
- Our query functions now take in all params required for fetching, instead of accessing dynamic variables internally. This is important to serialize arguments if we want to eventually `use cache`.
- Use `Streamable.from` to generate our streaming props that are passed to our UI components.
- Remove use of nuqs' `createSearchParamsCache` in favor of nuqs' `createLoader`.
- Update `/(facted)/brand/[slug]/page.tsx`
- For this page …
=> refactor(core): brand for dynamicIO

core/vibes/soul/form/switch/index.tsx
I noticed that after we updated TailwindCSS, the `Switch` component labels got broken. This is a quick PR to fix it.
Confirmed the fix works:
https://github.com/user-attachments/assets/5c58cebb-b972-4968-9076-fe09355d2014
1. Copy CSS classes over to Switch component
=> Fix Switch component labels

.changeset/seven-banks-bow.md, core/lib/makeswift/component.tsx, core/lib/makeswift/makeswift-component-shim.tsx, core/lib/makeswift/makeswift-page-shim.tsx, core/lib/makeswift/page.tsx
React / Next.js bug remounts a memoised client component rendered directly by an RSC. This caused the `ProductDetail` to remount before it can show the toast and update the cart.
https://github.com/vercel/next.js/issues/44901
https://github.com/vercel/next.js/issues/73507
Introduce a non-memo shims around `MakeswiftComponent` and `MakeswiftPage` that prevent the unwanted remount.
https://github.com/user-attachments/assets/23831b75-2d5e-45ab-83be-2dbe67434d9f
Test on the preview branch vs the `integrations/makeswift` branch:
https://catalyst-canary-git-fikri-eng-8075-3c0f42-bigcommerce-platform.vercel.app/smith-journal-13/
https://integrations-makeswift.catalyst-canary.store/spray-bottle/
=> fix: toast & cart updates on "add to cart"

core/lib/makeswift/provider.tsx, core/package.json, pnpm-lock.yaml
[Tailwind v4 use @layer](https://tailwindcss.com/blog/tailwindcss-v4#designed-for-the-modern-web). This caused the CSS reset to override the Tailwind styles.
[source](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
Disable the Makeswift CSS reset that overrides Tailwind v4 styles. Runtime PR: https://github.com/makeswift/makeswift/pull/1008
Preview deployment:
https://catalyst-canary-git-fikri-disable-m-51301b-bigcommerce-platform.vercel.app/
https://github.com/user-attachments/assets/73bb766e-600f-4c14-b124-76fefd686081
=> fix: disable Makeswift CSS reset that overrides Tailwind v4 styles

.changeset/plenty-buttons-know.md, core/app/[locale]/(default)/(auth)/login/_actions/login.ts
Check for `error.type` instead of `error.name` auth error in Login, since `error.name` gets minified in production and the check never returns `true`. Additionally, add a check for the `cause.err` to be of type `BigcommerceGQLError`.
In production:
Change `error.name === 'CallbackRouteError'` to `error.type === 'CallbackRouteError'` check in the error handling of the login action and include `error.cause.err instanceof BigCommerceGQLError`.
=> fix(core): check for error.type for login auth error

.changeset/legal-ends-judge.md, core/app/providers.tsx, core/context/search-context.tsx, core/messages/en.json, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/not-found/index.tsx
In order to maintain parity with Stencil's 404 page, we wanted to allow the user to search from the 404 page. Since the search included with the header component is fully featured, we included a CTA to open the same search that you get when clicking the search icon in the header.
* Pull down branch locally, navigate to `localhost:3000/foo`
* Check preview deployment: https://catalyst-canary-git-add-search-cta-to-404-bigcommerce-platform.vercel.app/foo/
Most changes are additive, so they should hopefully be easy to resolve if flagged for merge conflicts. Change #3 below replaces the Search state with the new search context, be sure to pay attention to the new 
1. This change adds a new directory under `core/` called `context/` containing a `search-context.tsx` file. Since this is a new …
=> feat: add search button cta to 404 page

.changeset/little-hornets-stand.md, core/app/[locale]/(default)/account/layout.tsx, core/app/[locale]/(default)/account/orders/[id]/page-data.tsx, core/app/[locale]/(default)/account/orders/page-data.ts, core/app/[locale]/(default)/account/wishlists/_actions/change-wishlist-visibility.ts, core/app/[locale]/(default)/account/wishlists/_actions/delete-wishlist.ts, core/app/[locale]/(default)/account/wishlists/_actions/new-wishlist.ts, core/app/[locale]/(default)/account/wishlists/_actions/remove-wishlist-item.ts, core/app/[locale]/(default)/account/wishlists/_actions/rename-wishlist.ts, core/app/[locale]/(default)/checkout/route.ts, core/client/index.ts, core/middlewares/with-auth.ts, packages/client/src/client.ts, packages/client/src/gql-auth-error.ts, packages/client/src/gql-error.ts, packages/client/src/index.ts, packages/client/src/invalid-cat-error.ts, packages/client/src/lib/error.ts, packages/client/src/missing-cat-error.ts
- Update `withAuth` middleware to redirect protected routes to `/login` page when user is unauthorized
- Add customer access token validation on protected routes
- Minor updates to end-user error messages on unauthorized GQL requests to stop returning raw GQL error and use our translated error message instead.
- Add `onError` event to GraphQL client
- Use the `onError` callback to invalidate user session when GQL returns an invalid or missing token error
https://github.com/user-attachments/assets/d3c519dd-1655-4a15-8801-cd0ef368711d
1. Copy all changes from the `/core/client` directory and the `/packages/client` directory
2. Copy logic from withAuth middleware to handle the `?invalidate-session` query param
3. Copy translation values
4. Copy all changes from the …
=> Update GQL client and auth middleware to handle invalid tokens and invalidate session

.changeset/whole-papers-scream.md, core/vibes/soul/sections/product-detail/product-detail-form.tsx
Add `date` field to product details form.
Locally, tested with default values or no default values.
Add missing date field switch case to product details form.
=> feat(core): add date field to product details form

.changeset/fruity-dingos-sip.md, core/components/header/index.tsx
* As part of the low cache hit rate investigation, we found that `GetCartCountQuery` is sent twice per render when navigating not using client cache (e.g., pressing browser reload button, clicking a link to a page)
* This PR wraps it in React `cache()` to prevent the behavior
* ✅ The `cache()` function does not do anything to cache the fetch request in data cache or otherwise, the cache options are still set to `'no-store'`. 
https://github.com/user-attachments/assets/c359de4d-a6ba-4952-811c-32ec25119eac
https://github.com/user-attachments/assets/38a3a0e1-7944-44a2-ba8b-195bed7d5776
Simply wrap `getCartCount` in `core/components/header/index.tsx` with React `cache()`
=> fix: memoize GetCartCountQuery with react cache

.changeset/pretty-coats-accept.md, packages/create-catalyst/bin/index.cjs
* The Catalyst CLI is currently powered by the package `packages/create-catalyst`
* Before running the CLI, we check what version of Node.js you are running the CLI with
* **⚠️ This check is done only to ensure that the version of Node.js you using to run the CLI supports all of the native Node.js features that the CLI depends on**. It does not need to be concerned with what version of Node.js is required to run Catalyst, those are two separate things.
* The minimum required Node version for the CLI to function is 18, because that's when [global Fetch was enabled by default](https://nodejs.org/en/blog/announcements/v18-release-announce), and global Fetch is the most recently released feature that the CLI depends on.
* Therefore, as long as the user is running Node 18+, they should have no …
=> chore: expand node.js version required to run CLI

.changeset/red-otters-wave.md, core/app/[locale]/(default)/(faceted)/category/[slug]/_components/category-viewed.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/account/wishlists/[id]/_components/wishlist-analytics-provider.tsx, core/app/[locale]/(default)/account/wishlists/[id]/page.tsx, core/app/[locale]/(default)/cart/_actions/update-line-item.ts, core/app/[locale]/(default)/cart/_components/cart-analytics-provider.tsx, core/app/[locale]/(default)/cart/_components/cart-viewed.tsx, core/app/[locale]/(default)/cart/page.tsx, core/app/[locale]/(default)/compare/_components/compare-analytics-provider.tsx, core/app/[locale]/(default)/compare/page.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-analytics-provider/index.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-viewed/index.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/app/[locale]/layout.tsx, core/components/analytics/events.tsx, core/components/analytics/fragment.ts, core/components/analytics/provider.tsx, core/components/wishlist/fragment.ts, core/vibes/soul/primitives/compare-card/add-to-cart-form.tsx, core/vibes/soul/primitives/wishlist-item-card/wishlist-item-add-to-cart.tsx, core/vibes/soul/sections/cart/client.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx, pnpm-workspace.yaml
Implements the new analytics provide and replaces consumption of the old one. The new provider now fetches your GA4 ID from the Bigcommerce Control Panel settings, removing the need of setting the environment variable. It also comes with new  events bindings to work more easily with VIBES components.
Most changes are additive so merge conflicts should be easy to resolve. In order to use the new provider from the previous provider, if it's already not setup in the BigCommerce control panel for checkout analytics, you'll need to add the GA4 property ID. This will automatically be used by the new `GoogleAnalytics` provider.
=> refactor(core): hook up new analytics provider

README.md
- We have plans to improve the OCC app to support the Vercel deploy button flow.
- Currently, the deploy button flow is supported by the Next.js Commerce integration which behaves a lot differently than OCC. In order to cause less confusion, we deep link to the OCC app instead of recommending the Deploy button flow. 
Tested the Deploy button flow, it:
- Installed the Next.js Commerce app in Control Panel, instead of OCC app
- The channel manu/details experience is not as good as OCC
- Next.js Commerce still uses Customer Impersonation Token, when Catalyst requires Storefront Token
N/A
Closes #1442
=> chore: CATALYST-1117 update readme recommendation for deployment

.changeset/cuddly-seals-exist.md, core/app/[locale]/(default)/webpages/[id]/contact/page.tsx, core/messages/en.json
Adds missing translation.
Translated label shows up.
Add missing translation.
=> fix(core): translate home breadcrumb in contact us page

README.md
> [!WARNING]
> This PR builds on #2305. Review by last commit on this branch
- Removes the outdated guidance under `## Resources`. This guidance used to be relevant back when the CLI would install just the application inside of `core/`, however now the CLI installs the entire monorepo.
N/A
N/A
=> chore: CATALYST-1117 remove outdated cli/monorepo guidance

README.md
We've seen a lot of value in DeepWiki for asking questions about Catalyst and getting some nice AI-generated documentation:
https://deepwiki.com/bigcommerce/catalyst
In support of this project, and also to get the benefit of the wiki refreshing weekly as we push new code, adding a badge to the README.
=> Add deepwiki badge to README

CONTRIBUTING.md
- Existing `CONTRIBUTING.md` file felt boilerplate-y, wanted to update it with relevant information on things like repository structure, development/integration branches, and how to pull in updates from `canary` into `integrations/makeswift`
N/A
N/A
=> chore: CATALYST-1117 update contributing.md with merge strategy we use for integrations/makeswift

README.md
Two changes:
1. Sync the readme with `canary` for `integrations/makeswift`; somehow it had the readme from `main`.
2. Add a specific notice to this readme as to which version of Catalyst it's from
N/A
=> Update readme for integrations/makeswift branch

core/vibes/soul/primitives/button/index.tsx
- removes previous styles where loading and disabled states had the same styles
- moves disabled styles into the default classes with the correct `disabled:` Tailwind syntax
https://github.com/user-attachments/assets/d8022d46-f9dc-4ee2-a2b4-78212cef5ff0
=> fix: button disabled and loading styles

.changeset/swift-geese-bake.md, core/app/[locale]/(default)/(faceted)/brand/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx, core/app/[locale]/(default)/(faceted)/search/page.tsx
Now that `totalCount` accepts strings, format the number to account for i18n.
Number is formatted.
Use `getFormatter` to `format.number` the values passed to the section component.
=> feat(core): format totalCount value for i18n

.changeset/silver-spiders-sing.md, core/app/[locale]/(default)/account/addresses/page.tsx
Pass `minimumAddressCount={0}` to the AddressListSection component.
We should allow customers to delete addresses even if it is their last one.
Tested locally
Update `/core/app/[locale]/(default)/account/addresses/page.tsx` and pass the `minimumAddressCount={0}` prop to the AddressListSection component.
Example:
```tsx
return (
<AddressListSection
addressAction={addressAction}
addresses={addresses}
cancelLabel={t('cancel')}
createLabel={t('create')}
deleteLabel={t('delete')}
editLabel={t('edit')}
fields={[...fields, { name: 'id', type: 'hidden', label: 'ID' }]}
minimumAddressCount={0}
setDefaultLabel={t('setDefault')}
showAddFormLabel={t('cta')}
title={t('title')}
updateLabel={t('update')}
/>
);
```
=> Set minimum address count to 0

.changeset/shiny-cooks-travel.md, core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/account/orders/page.tsx, core/app/[locale]/(default)/account/settings/_actions/update-customer.ts, core/app/[locale]/(default)/account/wishlists/[id]/_components/wishlist-actions.tsx, core/app/[locale]/(default)/account/wishlists/[id]/page-data.ts, core/app/[locale]/(default)/account/wishlists/[id]/page.tsx, core/app/[locale]/(default)/account/wishlists/_components/wishlist-actions-menu.tsx, core/app/[locale]/(default)/account/wishlists/modals.tsx, core/app/[locale]/(default)/account/wishlists/page-data.ts, core/app/[locale]/(default)/account/wishlists/page.tsx, core/app/[locale]/(default)/wishlist/[token]/page.tsx, core/app/admin/route.ts, core/app/favicon.ico/route.ts, core/app/robots.txt/route.ts, core/app/sitemap.xml/route.ts, core/app/xmlsitemap.php/route.ts, core/components/wishlist/share-button.tsx, core/i18n/locales.ts, core/i18n/request.ts, core/i18n/routing.ts, core/messages/en.json, core/vibes/soul/sections/wishlist-list-item/index.tsx
To prepare for the subsequent e2e testing PRs I'm going to make, I had to make some changes to some core components first:
1. Fix incorrect/missing translation messages, as this is needed for locale-based testing. I did not capture all of the missing ones, just the easy ones. We will follow up on this.
2. Separate `defaultLocale` into it's own file. This needs to be done because `i18n/routing.ts` imports server-only NextJS components which prevents importing `defaultLocale` in tests. Splitting `defaultLocale` into a separate file allows us to use it in the test environment.
3. I noticed caching issues on account pages in my e2e tests, and we decided that it's best not to cache the data on these pages.
4. Update `WishlistListItem` for better accessibility
Tested locally, local build, and …
=> Fix incorrect/missing translation messages, separate defaultLocale in to a separate file, remove caching in /account pages

.changeset/fluffy-oranges-act.md, core/components/analytics/events.tsx
Softly fails the `useEvents` hook if not rendered within a context.
https://github.com/user-attachments/assets/e021ce06-66d1-4bc8-81d7-f5994fe47292
Pull in changes with a merge/rebase.
=> fix: soft fail analytics events

.changeset/sour-ducks-hug.md, core/app/[locale]/not-found.tsx, core/messages/en.json, core/vibes/soul/sections/not-found/index.tsx
When writing e2e tests, I noticed that the "Search" button on the 404 page is not translated.
Tested locally via production build.
1. Add `"search"` translation key in the `"NotFound"` translations
2. In `core/vibes/soul/sections/not-found/index.tsx`, add a `ctaLabel` property and ensure it is used in place of the "Search" text
3. In `core/app/[locale]/not-found.tsx`, pass the `ctaLabel` prop as the new translation key `ctaLabel={t('search')}`
=> Translate search button on NotFound page

.changeset/wide-olives-deny.md, core/components/header/index.tsx, core/messages/en.json, core/vibes/soul/primitives/navigation/index.tsx
When writing e2e tests, I found more missing translations with the Search component. This PR removes some unused props and adds the missing translations.
Tested locally
Ensure the following props are passed to the `HeaderSection` navigation prop:
```tsx
searchInputPlaceholder: t('Search.inputPlaceholder'),
searchSubmitLabel: t('Search.submitLabel'),
```
Add the following keys to the `Components.Header.Search` translations:
```json
"somethingWentWrong": "Something went wrong. Please try again.",
"inputPlaceholder": "Search products, categories, brands...",
"submitLabel": "Search"
```
Copy all changes from this file:
1. Create `searchSubmitLabel?: string;` property, ensure it is passed into `SearchForm`
2. On the `SearchForm`, remove the `searchCtaLabel = 'View more',` property, as it is …
=> Remove unused search props, add missing search translations

.changeset/proud-masks-read.md, core/vibes/soul/sections/product-detail/actions/revalidate-cart.ts, core/vibes/soul/sections/product-detail/product-detail-form.tsx
We want state to be persitent on the `ProductDetailForm`, even after submit. This change will allow the API error messages to properly show when the form is submitted. Additionally, other form fields will retain state (like item quantity).
State is retained when form is submitted.
- Update `ProductDetailForm` to prevent reset on submit, by removing `requestFormReset` in the `onSubmit`.
- Remove `router.refresh()` call and instead call new `revalidateCart` action.
- `revalidateCart` is an action that `revalidateTag(TAGS.cart)`
- This prevents the form from fully refreshing on success.
=> fix(core): product form retains state when submitted

.changeset/rich-brooms-read.md, core/vibes/soul/primitives/navigation/index.tsx
Noticed that when we switch locales, we lose the search params selection. In some cases (like compare and PDP), we want search params to be retained.
Locally tested that the search params remain.
Modify `useSwitchLocale` hook to include `Object.fromEntries(searchParams.entries())`.
=> fix(core): pass searchParams when swapping locales

.changeset/some-cars-sink.md, core/package.json, pnpm-lock.yaml
Upgrade from 0.24.1 to 0.24.6 to incorporate the latest Makeswift runtime fixes, including component error boundaries. See https://github.com/makeswift/makeswift/releases for the full list of changes.
https://github.com/user-attachments/assets/4dd7d13a-e281-4fa8-bec8-6d8ecce4a73c
=> Upgrade `@makeswift/runtime` to 0.24.6

.changeset/silent-times-nail.md, core/vibes/soul/form/select-field/index.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx
Updates `SelectField` to have a hidden input to pass the value of the select to the form. This is a workaround for a [Radix Select issue](https://github.com/radix-ui/primitives/issues/3198) that auto selects the first option in the select when submitting a form (even when no selection has been made).
Additionally, fixes an issue of incorrectly adding an empty query param for product options when an option is empty.
Locally, input error when it is required and no selection has been made.
Migration is straighforward and requires adding the hidden input to the component and renaming the `name` prop for the `Select` component to something temporary.
=> fix(core): select component properly errors when required and empty

.changeset/bright-rabbits-joke.md, core/data-transformers/product-options-transformer.ts, core/vibes/soul/form/card-radio-group/index.tsx, core/vibes/soul/sections/product-detail/schema.ts
Fixes the error warning of having a `ProductPickList` with no images, by making the `image` prop optional for when it is not needed.
Locally, no issue on console.
- Update `schema.ts` to allow optional `image` prop for `CardRadioField`
- Update `productOptionsTransformer` switch to have two cases for `ProductPickList`
- `ProductPickList` with no image object
- `ProductPickListWithImages` with image object
- Update ui component to make the `image` prop optional and conditionally render the image.
=> fix(core): makes image optional for PickList with no images

core/vibes/soul/form/switch/index.tsx
The tailwind 3 downgrade broke switch labels since `group-has-data` is no longer a valid selector. It must be replaced with `group-data-[]`
https://github.com/user-attachments/assets/3b01f111-428b-4ecb-b345-e9f245bc79a9
Copy over changes from the `core/vibes/soul/form/switch/index.tsx` file
=> Fix switch component labels for tailwind 3

.changeset/crazy-wings-smell.md, core/vibes/soul/form/input/index.tsx, core/vibes/soul/form/number-input/index.tsx
Add missing border style for `Input`, `NumberInput` and `DatePicker`.
Following convention, add these conditional classes to the fields using `clsx`:
```
{
light:
errors && errors.length > 0
? 'border-[var(--input-light-border-error,hsl(var(--error)))]'
: 'border-[var(--input-light-border,hsl(var(--contrast-100)))]',
dark:
errors && errors.length > 0
? 'border-[var(--input-dark-border-error,hsl(var(--error)))]'
: 'border-[var(--input-dark-border,hsl(var(--contrast-500)))]',
}[colorScheme],
```
=> fix(core): add missing error styles for inputs with errors

.changeset/silver-items-tie.md, core/auth/anonymous-session.ts
This adds the `__Secure-` cookie prefix to the anonymous session cookie to add extra security measures. This logic follows the same behavior as Auth.js does for prefixing it's cookies with the `__Secure-` prefix.
If you haven't merge the anonymous session code, pulling it in should just work ™️.
=> fix(core): prefix anonymous cookie with __Secure for https://

.changeset/icy-cars-camp.md, core/package.json, core/postcss.config.js, core/tailwind.config.js, core/vibes/soul/form/card-radio-group/index.tsx, core/vibes/soul/primitives/blog-post-card/index.tsx, core/vibes/soul/primitives/compare-drawer/index.tsx, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/sections/blog-post-content/index.tsx, core/vibes/soul/sections/cart/client.tsx, core/vibes/soul/sections/cart/index.tsx, core/vibes/soul/sections/order-details-section/index.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/product-detail/product-gallery.tsx, pnpm-lock.yaml
Utilizes the tailwind plugin to support aspect ratios in older browsers like Safari 14. 
All the old arbitrary classes will need to define the height and width classes:
```
// before
.aspect-[4/5]
//after
.aspect-w-4 .aspect-h-5
```
=> fix(core): use tailwind aspect-ratio plugin

.changeset/soft-emus-drive.md, core/app/[locale]/(default)/product/[slug]/_components/wishlist-button/index.tsx, core/components/header/index.tsx, core/messages/en.json, core/vibes/soul/primitives/favorite/heart.tsx, core/vibes/soul/primitives/favorite/index.tsx, core/vibes/soul/primitives/navigation/index.tsx
Add title to currency selector and PDP wishlist buttons. This is good for accessibility but also allows e2e tests to find the elements.
Build passes locally
1. Copy all changes from the `/messages/en.json` file to get updated translation keys
2. Add the `title` prop to the `Heart` component in `/core/vibes/soul/primitives/favorite/heart.tsx`
3. Add the `title` prop to the `Favorite` component in `/core/vibes/soul/primitives/favorite/index.tsx` and pass it to the `Heart` component
4. Copy all changes in the `/core/vibes/soul/navigation/index.tsx` file to add the `switchCurrencyLabel` property
5. Update `/core/components/header/index.tsx` file to pass the `switchCurrencyLabel` to the `HeaderSection` component
6. Update `/core/app/[locale]/(default)/product/[slug]/_components/wishlist-button/ …
=> Add aria labels to currency selector and PDP wishlist favorite button

core/tests/fixtures/catalog/index.ts, core/tests/fixtures/currency/index.ts, core/tests/fixtures/customer/session.ts, core/tests/fixtures/index.ts, core/tests/fixtures/utils/api/catalog/http.ts, core/tests/fixtures/utils/api/catalog/index.ts, core/tests/fixtures/utils/api/currencies/http.ts, core/tests/fixtures/utils/api/currencies/index.ts, core/tests/fixtures/utils/api/index.ts, core/tests/ui/e2e/account/wishlist-details.spec.ts, core/tests/ui/e2e/product.spec.ts
- Add e2e tests for the product page
- Add currency fixture for tests that need alternate currency formatting and utilities
1. Copy all changes from the `/core/tests` directory
=> Add PDP e2e tests, add currency fixture

.changeset/fancy-clowns-shout.md, core/app/[locale]/(default)/(auth)/register/_actions/prefixes.ts, core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts, core/app/[locale]/(default)/(auth)/register/page-data.ts, core/app/[locale]/(default)/(auth)/register/page.tsx, core/app/[locale]/(default)/account/addresses/page.tsx, core/data-transformers/form-field-transformer/index.ts, core/data-transformers/form-field-transformer/utils.ts, core/tests/ui/e2e/auth/register.spec.ts
As part of the update with VIBES, we decided to slim down the account creation from. Part of this we added a custom hardcoded list of form fields we rendered within the form based on the form fields provided from the API. We'd then filter out the form fields provided by the API with this hardcoded list. Where this broke down is when you set a field on the address fields, e.g. `Phone number`, as required and tried to submit the form, you'd get API errors because the form field was not present on the form submission. A developer would need to go in and manually add the form field as part of the hard coded list.
As a solution to this problem, we are now taking all the form fields from the API and dynamically rendering them (still) with the `DynamicForm` component. This also aligns the logic …
=> feat(core): render address fields for customer registration

.changeset/busy-snakes-agree.md, core/vibes/soul/sections/breadcrumbs/index.tsx
Alter `Breadcrumb` component to use `index` instead of `href` for the key. When using large breadcrumbs for nested pages or categories, we truncate the breadcrumbs to put a `...` (e.g. `Home > Page 1 > ... > Page 5`), Where the `...` and `Page 5` will both use `#` for the href property.
This means that if you have a deeply nested page, you will get a duplicate key error.
This was previously fixed, but had a regression when we sync'd the Breadcrumbs component from VIBES.
Tested locally
Update `core/vibes/soul/sections/breadcrumbs/index.tsx` to use `index` as the `key` property instead of `href`
=> Fix breadcrumb keys

core/tests/fixtures/index.ts, core/tests/fixtures/utils/api/index.ts, core/tests/fixtures/utils/api/webpages/http.ts, core/tests/fixtures/utils/api/webpages/index.ts, core/tests/fixtures/webpage/index.ts, core/tests/ui/e2e/webpages.spec.ts
Add e2e tests for core functionality on Web Pages
Copy all changes from `/core/tests`
=> Add webpage e2e tests

.changeset/rare-news-jump.md, core/vibes/soul/primitives/blog-post-card/index.tsx
Fix the blog date formatting to use the `date` property directly passed in. Currently, we're calling `new Date(date).toLocaleDateString('en-US', ...)` on the blog post card, which fails on alternate locales.
Update the component to use `<time dateTime={date}>{date}</time>` for the date, instead of calling `new Date(date).toLocaleDateString(...)`.
=> Fix blog date formatting

core/tests/fixtures/utils/api/client.ts
I noticed that after refactoring the httpClient for test fixtures, we forgot to account for the fact that the BC API returns an empty body for certain routes.
For example, with `GET /v2/orders`, if no orders are returned, instead of responding with an empty array `[]`, the endpoint will simply respond with `204 No Content` with an empty body. This causes an error when attempting to parse the response as a zod schema.
For usability, we should only parse as JSON when the body is not empty, otherwise attempt to use zod to parse an `undefined` value. This allows the API clients to define the intent when calling the API:
```
const resp = await httpClient
.get(`/v2/orders?${params}`)
.parse(z.array(OrderSchema).optional());
```
Copy changes from `/core/tests`
=> Fix test httpClient from breaking when BC returns empty body for a JSON response

.changeset/open-hotels-fetch.md, core/lib/makeswift/components.ts, core/lib/makeswift/components/accordion/accordion.makeswift.tsx
Rename `Accordions` to `Accordion` to avoid confusion and align with [standard UX terminology](https://chatgpt.com/share/676758f0-d0b0-8012-968f-4b0949cc6826). Note that the underlying Soul component is already correctly named, this change only affects the Makeswift component and builder naming.
Aside from the terminology update, this change is fully backward compatible and does not affect user-visible component behavior.
https://github.com/user-attachments/assets/65a1d834-50b9-43f3-a755-78ed5a19d0d0
=> fix: usability/terminology fix, Accordions -> Accordion

core/tests/fixtures/index.ts, core/tests/fixtures/promotion/index.ts, core/tests/fixtures/utils/api/index.ts, core/tests/fixtures/utils/api/promotions/http.ts, core/tests/fixtures/utils/api/promotions/index.ts, core/tests/ui/e2e/coupon.spec.ts
Add e2e tests for coupon code functionality on the cart.
Copy changes from `/core/tests`
=> Add e2e tests for coupon codes

.changeset/some-aliens-punch.md, core/app/[locale]/(default)/account/addresses/page.tsx, core/app/[locale]/(default)/account/orders/page.tsx, core/app/[locale]/(default)/account/wishlists/page.tsx, core/messages/en.json, core/tests/ui/e2e/account/orders.spec.ts, core/tests/ui/e2e/account/wishlists.spec.ts, core/vibes/soul/sections/account-settings/index.tsx, core/vibes/soul/sections/address-list-section/index.tsx, core/vibes/soul/sections/order-list/index.tsx, core/vibes/soul/sections/wishlist-list/index.tsx, core/vibes/soul/sections/wishlists-section/index.tsx
Add empty state for AddressListSection.
- Add `AddressListEmptyState` and conditionally render it if the `addresses` array is empty.
- Add `emptyStateTitle` prop.
- Update header classes for all account pages
- Hide header in small viewport
=> feat(core): update empty states for account pages

.changeset/every-pets-sneeze.md, core/vibes/soul/primitives/navigation/index.tsx
Set a min-height for the Navigation fallback skeleton to prevent layout shift.
Reason why it's `41px` is because this is the value of the menu links.
Tested locally and no longer see a layout shift when swapping locales.
Add `min-h-[41px]` & `items-center` to fallback.
=> fix(core): set min-height for navigation fallback

core/tests/ui/e2e/compare.spec.ts
Use translations labels for compare e2e tests.
Tests pass locally
Update tests to include translation labels.
=> fix(tests): use translation labels for compare e2e tests

core/vibes/soul/sections/footer/index.tsx
- adds same CSS classes to footer logo as header logo to ensure support for different logo widths
- fixes oversized logo in footer
https://github.com/user-attachments/assets/46f028fa-52f9-40d0-a337-ae0134678d4a
=> fix: oversized logo in footer

CONTRIBUTING.md
Jira: [CATALYST-1333](https://bigcommercecloud.atlassian.net/browse/CATALYST-1333)
Update and introduce new guidance for: 
* How to keep `integrations/makeswift` up to date with `canary`
* How to release new versions of `@bigcommerce/catalyst-core`, `@bigcommerce/catalyst-makeswift`, `@bigcommerce/catalyst-client`, `@bigcommerce/create-catalyst`, `@bigcommerce/eslint-config-catalyst`
These steps were tested and validated as part of the process of merging #2334 and #2335 
N/A
[CATALYST-1333]: https://bigcommercecloud.atlassian.net/browse/CATALYST-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add guidance for how to release new versions of catalyst-makeswift with Changesets

.github/scripts/prevent-invalid-changesets.js, .github/workflows/prevent-invalid-changesets.yml, CONTRIBUTING.md
#2336 introduced updated documentation on how to keep `integrations/makeswift` up to date with `canary`. That documentation left room for potential human error. This PR introduces a GitHub Action to help prevent those errors. 
This action causes PR's to `integrations/makeswift` that contain `.changeset/*.md` files targeting packages that do not exist in that branch  (e.g., `"@bigcommerce/catalyst-core"`), or packages that we do not want to publish from this branch (e.g., `"@bigcommerce/catalyst-client"`, `"@bigcommerce/create-catalyst"`, or `"@bigcommerce/eslint-config-catalyst"`) to fail and prevent the PR from being merged. 
> [!NOTE]
> This work needs to be synced over to the `integrations/makeswift` branch to take effect. Will open a PR to do that after this. 
Locally via …
=> feat: prevent invalid changesets from being merged into integrations/makeswift

.changeset/ninety-flowers-retire.md, core/auth/anonymous-session.ts
Fixes an issue where when we were deleting the anonymous session, additional cookie options were not being passed to the `Set-Cookie` header, thus not clearing the anonymous session. You can see the issue in the following screenshot.
Pull in the change like normal.
=> fix(core): add addition cookie options to anonymous cookie deletion

package.json, pnpm-lock.yaml
When changesets tries to generate a changelog, it utilizes prettier, and resolves the prettier config closest to the `CHANGELOG.md` file that is being generated. In the case of `core/` the `prettier.config.js` included the `prettier-plugin-tailwindcss` plugin, but since changesets is being ran at the root cwd, pnpm can't resolve that ESM module. This errored out  when trying to generate the changelog and stopped the changelog from being built:
```bash
Error: Cannot find module 'prettier-plugin-tailwindcss'
Require stack:
- /home/runner/work/catalyst/catalyst/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js
- /home/runner/work/catalyst/catalyst/node_modules/.pnpm/@changesets+write@0.4.0/node_modules/@changesets/write/dist/changesets-write.cjs.js
- …
```
=> chore: fix changesets dependency resolution

.changeset/metal-aliens-attend.md, core/package.json, pnpm-lock.yaml
Bump next to latest canary
This resolves an issue with docker builds of catalyst 500ing on PDPs
Preview build
N/A
=> Bump next to latest canary

.changeset/thick-readers-deny.md, core/app/[locale]/(default)/(faceted)/category/[slug]/page.tsx
Add slots for user-provided content (e.g., banners, footers) to category pages, in the same way they are supported on the cart page.
https://github.com/user-attachments/assets/04f05948-2f15-468b-ba26-8eb4c763c779
=> feat: slots for user-provided content on category pages

.changeset/moody-coats-see.md, core/app/[locale]/(default)/product/[slug]/page-data.ts, core/app/[locale]/(default)/product/[slug]/page.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx, core/vibes/soul/sections/product-detail/schema.ts
Respect the min and max purchase quantity of the product, as returned by GraphQL.
Before:
After:
N/A
=> Use min and max purchase quantity to set bounds of quantity number input

packages/cli/commander.d.ts, packages/cli/package.json, pnpm-lock.yaml
> [!WARNING]
> Merge after #2461
Maintainers of `@commander-js/extra-typings` recently provided updated documentation on how to configure the package as a `devDependency` to get the extra typings from the ambient module without needing extra typings at runtime: https://github.com/commander-js/extra-typings/pull/92
In my opinion, this is worth doing because by default, IDE’s like VSCode automatically import from "commander" instead of "@commander-js/extra-typings" which easily slips through PR reviews (hence why all of the imports in `@bigcommerce/catalyst` are importing from `"commander"` instead of `"@commander-js/extra-typings"`
Add an option to a command, see that it is typed.
N/A
=> chore: use @commander-js/extra-typings as devDep

.changeset/wise-ads-drive.md, core/app/[locale]/layout.tsx, core/client/graphql.ts, core/components/scripts/README.md, core/components/scripts/fragment.ts, core/components/scripts/index.tsx, core/components/scripts/scripts.tsx
Checks for scripts in Script Manager tied to the Catalyst storefront's channel and renders them in the root layout using [next/script](https://nextjs.org/docs/app/api-reference/components/script).
Related docs PR: https://github.com/bigcommerce/docs/pull/1014
⚠️ This makes a best-effort attempt to map [Scripts API](https://developer.bigcommerce.com/docs/integrations/scripts) properties to the optimal settings in a [next/script](https://nextjs.org/docs/app/api-reference/components/script) context, but it does prefer performance over parity for purposes of rendering scripts on Catalyst ⚠️ 
⚠️ Scripts that worked on Stencil are NOT guaranteed to work on Catalyst, and may need to be re-written, especially if they depend on the DOM or need to fire on every navigation ⚠️ 
⚠️ Overall this is not …
=> Render scripts from Script Manager

core/.eslintrc.cjs, packages/cli/.eslintrc.cjs, packages/client/.eslintrc.cjs, packages/create-catalyst/.eslintrc.cjs, pnpm-workspace.yaml
[`pnpm@10` introduced a breaking change where modules are no longer hoisted to the root modules directory by default](https://github.com/pnpm/pnpm/releases/tag/v10.0.0). While this does not break `eslint` when it's run as a script, it does cause errors for the ESLint LSP. See screenshots below
Before:
After:
Delete `node_modules` and run `pnpm install` again
=> chore: explicitly hoist eslint for pnpm 10

.github/workflows/basic.yml, packages/cli/package.json, packages/cli/src/commands/build.ts, packages/cli/src/program.ts, packages/cli/tests/commands/build.spec.ts, pnpm-lock.yaml
* Adds [`consola`](https://github.com/unjs/consola) for logging
* Runs CLI tests in all popular OS's to match the different environments where our customers run the CLI 
* Recursively copy a Catalyst project to a temporary directory, OS-agnostic API's from Node.js are being used
* Includes tests
Includes unit tests
N/A
=> feat: recursively copy cwd into temp folder

core/package.json, packages/cli/src/commands/build.ts, pnpm-lock.yaml
Updates `opennextjs-cloudflare` version to [`1.5.2`](https://github.com/opennextjs/opennextjs-cloudflare/releases/tag/%40opennextjs%2Fcloudflare%401.5.2) to fix instrumentation for Next.js 15.4
Tested build with `1.5.2`:
N/A
Closes #2482
=> chore: bump opennextjs-cloudflare version

packages/cli/.eslintrc.cjs, packages/cli/package.json, packages/cli/src/commands/build.ts, packages/cli/src/lib/get-module-cli-path.ts, packages/cli/templates/open-next.config.ts, packages/cli/templates/wrangler.jsonc, packages/cli/tsconfig.json
There are at least two templates that do not exist in the `core/` folder that need to exist in order for `opennextjs-cloudflare build` to succeed. 
The `opennextjs-cloudflare` CLI does create these files for you [if they do not exist](https://github.com/opennextjs/opennextjs-cloudflare/blob/54e65c5092d21aee3731c105f915ff17bef8fae0/packages/cloudflare/src/cli/index.ts#L32), however you must answer an interactive prompt. Rather than trying to answer the prompt in our CLI, we can just manually copy the templates from the CLI module in NPM. This also gives us more control over the contents of the templates in case we want to tweak any settings. 
Pull down this branch, install deps (`pnpm i`), build the CLI (`pnpm -F "./packages/cli" build`), and run the build command in Catalyst root (`node …
=> feat: copy templates from cli to catalyst build tmpdir

packages/cli/src/commands/version.ts, packages/cli/src/program.ts, packages/cli/tests/commands/version.spec.ts, packages/cli/tests/index.spec.ts
+ Updates `version` to use `consola`
+ Updates tests for `version` and `program`
Tests pass
N/A
=> refactor(cli): use consola for version logs and update tests

packages/cli/templates/wrangler.jsonc
Recent load testing generated over 6 million logs on a single Catalyst deployment; this is quite a large number considering that the base paid plan only gets 20M logs for free, then requires that you pay for each million logs after that. In this PR we are primarily disabling [invocation logs](https://developers.cloudflare.com/workers/observability/logs/workers-logs/#invocation-logs) and lowering the sampling rate from the default (1) to 0.05 to decrease the number of logs emitted by a Catalyst deployment. 
Will be tested during the next load test
N/A
=> refactor: modify cf observability config to decrease logs generated

packages/cli/package.json, packages/cli/src/commands/version.ts, packages/cli/src/program.ts, packages/cli/tests/commands/version.spec.ts, pnpm-lock.yaml
In the spirit of #2505, I don't think we need `chalk` anymore. Since we are using `consola` we can instead use `consola.colorize('cyan', '<str>')` ([docs](https://github.com/unjs/consola?tab=readme-ov-file#console-utils)) whenever we want to colorize logs. 
Additionally, since we have the `version` command, we don't need to log the CLI version each time the CLI runs. I am open to reverting this change if it's too drastic, I'm not sure if there are good reasons to keep the log (IMO, the log prints every time tests run which adds to the test log output which is slightly annoying). 
Run `pnpm test` and see that all tests still pass
N/A
=> refactor: remove chalk in favor of consola.colorize

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/link.ts, packages/cli/src/lib/project-config.ts, packages/cli/src/lib/telemetry.ts, packages/cli/tests/commands/link.spec.ts, packages/cli/tests/lib/project-config.spec.ts
As discussed in https://github.com/bigcommerce/catalyst/pull/2514#discussion_r2257806601, this PR refactors the `ProjectConfig` class so that it does not wrap `get` and `set` methods. For example, the [`get`](https://github.com/sindresorhus/conf?tab=readme-ov-file#getkey-defaultvalue) method from Conf accepts a second parameter for a `defaultValue`, but we don't allow that. 
The original idea behind creating the `ProjectConfig` class was to reduce the boilerplate required to instantiate `Conf` with `cwd`,  `projectSuffix`, `configName`, etc. options; this refactor still accomplishes that goal, while making the `get` and `set` calls more flexible.
Test suite passes
N/A
=> refactor: unwrap get and set instance methods of conf

.changeset/smooth-rats-rule.md, core/app/[locale]/(default)/cart/_components/checkout-preconnect.tsx, core/app/[locale]/(default)/cart/page-data.ts, core/app/[locale]/(default)/cart/page.tsx
On the cart page, add a preconnect tag for the checkout URL, to make sure DNS and TLS connection is already done by the time the user needs to redirect to checkout, thus improving checkout load performance for the redirected checkout.
https://nextjs.org/docs/app/api-reference/functions/generate-metadata#resource-hints
=> Preconnect to checkout origin on cart page

packages/cli/package.json, packages/cli/src/commands/build.ts, packages/cli/tests/commands/build.spec.ts, pnpm-lock.yaml
> [!WARNING]
> Depends on #2531
Previously, `build` was running inside of a temporary directory in an effort to abstract away Cloudflare-related configuration files (`wrangler.jsonc`, `open-next.config.ts`) and dependencies (`@opennextjs/cloudflare`). The only artifact that we copied from this temporary directory back into the original Catalyst project was a single `worker.js` file.
Unfortunately, we discovered that the `opennextjs-cloudflare preview` command needs access to some of the intermediary files that were being deleted when the temporary folder was deleted at the end of `build`.
This PR removes the temporary directory step and runs `opennextjs-cloudflare build` to programmatically build the application in `core`.
If you'd like to test this PR locally, follow these steps:
1. Pull …
=> refactor(cli): run build directly on core

packages/cli/src/commands/build.ts
> [!WARNING]
> Depends on #2527
Organizes the `open-next.config.ts` file and `wrangler.jsonc` file injected by `build`. Instead of putting `wrangler.jsonc` in `core`, it places it in `.bigcommerce`. The `open-next.config.ts` file is now cleaned up after `build` since it's no longer needed (the compiled version of the file exists in `.open-next`
1. Pull down this branch
2. Run `pnpm build`
3. `cd` into `core`
4. Run `pnpm add @opennextjs/cloudflare`
5. Run `node ../packages/cli/dist/index.js build`
N/A
=> refactor: organize configuration files for better build output

packages/cli/templates/open-next.config.ts
When we place `scripts.build` in `core/package.json` with `catalyst build` instead of `next build`, `opennextjs-cloudflare build` [will just recursively call](https://github.com/opennextjs/opennextjs-aws/blob/551dc85ec6f6e7ccb209ecc957c2c19b4ce1e6f6/packages/open-next/src/build/buildNextApp.ts#L13-L24) `pnpm run build` — this PR overrides the build command allowing us to break out of the recursion.
N/A
N/A
=> feat: override buildcommand when building with opennextjs-cloudflare

packages/cli/src/commands/build.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/start.ts, packages/cli/src/lib/wrangler-config.ts, packages/cli/tests/commands/start.spec.ts
Builds on top of #2517 
Runs either `nextjs start` or `opennextjs-cloudflare preview` when running `catalyst start`, depending on the selected framework.
Locally it runs both versions + unit tests.
```
❯ pnpm run start
> @bigcommerce/catalyst-core@1.1.0 start /Users/jorge.moya/dev/catalyst/core
> catalyst start
◢ @bigcommerce/catalyst v0.1.0                                                                    3:24:47 PM
┌───────────────────────────────┐
│ OpenNext — Cloudflare preview │
└───────────────────────────────┘
Monorepo detected at /Users/jorge.moya/dev/catalyst
Populating KV incremental cache...
▲ [WARNING]                             You have defined bindings to the following internal Durable Objects:
- {"name":"NEXT_CACHE_DO_QUEUE","class_name":"DOQueueHandler"}
- …
```
=> feat(cli): run opennext-cloudflare preview for catalyst framework

packages/cli/src/commands/deploy.ts, packages/cli/tests/commands/deploy.spec.ts
Add `--dry-run` option for the cases where we only.
Remove `--root-dir` since we're moving away from that option.
Unit tests and locally
```
◢ @bigcommerce/catalyst v0.1.0                                                                                                                                    2:49:37 PM
ℹ Generating bundle...                                                                                                                                           2:49:37 PM
✔ Bundle created at: /Users/jorge.moya/dev/catalyst/core/.bigcommerce/dist/bundle.zip                                                                            2:49:39 PM
ℹ Dry run enabled — skipping upload and deployment steps. …
```
=> feat(cli): add --dry-run option to deploy

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/link.ts, packages/cli/tests/commands/link.spec.ts, packages/cli/tests/mocks/handlers.ts
Adds a new option in the prompt to create a new project.
Locally and unit tests.
```
◢ @bigcommerce/catalyst v0.1.0                                                         1:15:22 PM
◐ Fetching projects...                                                                 1:15:22 PM
✔ Projects fetched.                                                                   1:15:23 PM
✔ Select a project (Press <enter> to select).
Create a new project
✔ Enter a name for the new project:
Team Gucci 3
✔ Project "Team Gucci 3" created successfully.                                        1:15:37 PM
◐ Writing project UUID to .bigcommerce/project.json...                                 1:15:37 PM
✔ Project UUID written to .bigcommerce/project.json.   
```
N/A
=> feat(cli): allow creation of project in link command

.changeset/great-queens-joke.md, core/app/[locale]/layout.tsx, core/lib/makeswift/provider.tsx, core/package.json, pnpm-lock.yaml
Bump the runtime for compatibility with Next.js 15.5; will be necessary for next release.
Did a smoke test of Makeswift builder on this branch.
=> chore: update @makeswift/runtime to version 0.25.0 in package.json

packages/cli/src/commands/build.ts
`--project-uuid` should also read from `BIGCOMMERCE_PROJECT_UUID` for CI environments
N/A
N/A
=> fix: build command --project-uuid should also read from env

packages/cli/src/commands/deploy.ts, packages/cli/tests/commands/deploy.spec.ts
Parses `env.options` to send to create deployment.
Will also read from env variables if the corresponding key was not passed in `env.options`.
Variables we're looking for:
`BIGCOMMERCE_STORE_HASH`
`BIGCOMMERCE_STOREFRONT_TOKEN`
`BIGCOMMERCE_CHANNEL_ID`
Locally and unit tests.
N/A
=> feat(cli): add env option to deploy command

core/vibes/soul/primitives/button-link/index.tsx, core/vibes/soul/primitives/button/index.tsx
- renames variables ending in `-text` in the `Button` and `ButtonLink` components to use `-foreground` to fix issues with Site Theme
https://github.com/user-attachments/assets/9a46ffa7-bcc7-4ebc-98d4-debec5cc3cb7
=> fix: text variable for button and button-link components

.changeset/cruel-pens-dance.md, packages/client/src/client.ts
Fixes the following error when `cacheComponents` is set to `true`
> Cannot access `Date.now()`, `Date()`, or `new Date()` before other uncached data or Request data in a Server Component
Docs: https://nextjs.org/docs/messages/next-prerender-current-time 
Before:
After:
Replace usage of Date.now with performance.now in @bigcommerce/catalyst-client
=> chore: prefer performance.now over Date.now in server component

.changeset/tender-women-smash.md, packages/client/src/client.ts
Fixes `duration` in the client logger to 2 decimal places
Before:
After:
Add `.toFixed(2)` to the duration calculation in the client logger
=> chore: fix performance.now to 2 decimal places

.changeset/cold-buckets-watch.md, core/app/[locale]/(default)/account/addresses/_actions/update-address.ts, core/app/[locale]/(default)/account/wishlists/[id]/_components/wishlist-analytics-provider.tsx, core/app/[locale]/(default)/cart/_components/cart-analytics-provider.tsx, core/app/[locale]/(default)/compare/_components/compare-analytics-provider.tsx, core/app/[locale]/(default)/product/[slug]/_components/product-analytics-provider.tsx, core/components/header/_actions/switch-currency.ts, core/data-transformers/form-field-transformer/utils.ts, core/i18n/routing.ts, core/lib/cart/add-cart-line-item.ts, core/lib/cart/create-cart.ts, core/lib/user-agent.ts
Removes unused exports from core.
N/A
Remove `export` declarations from functions that are not being imported anywhere else.
=> chore(core): removes unused exports

.changeset/floppy-pans-return.md, core/data-transformers/facets-transformer.ts
Had a support request that the product counts and the collapse by default weren't working. I assume this was a miss from the VIBES transition.
Update the `facets-transformer.ts` code to include the product count in the label and `defaultCollapsed` prop.
=> fix(plp): add back product counts and collapse by default

.changeset/config.json, .changeset/itchy-lions-work.md, .changeset/pre.json, packages/catalyst/CHANGELOG.md, packages/catalyst/package.json
> [!WARNING]
> Merging this into a separate `alpha` branch instead of `canary`. changesets recommends tracking it in a separate branch to keep `canary` releasable.
Using an `alpha` branch to publish `alpha` versions of the new `@bigcommerce/catalyst` package. This package will be used for experimenting with new features we want to bring to Catalyst. For now, we want to publish the CLI as an alpha so we can make sure it works as expected.
In order to publish, this need to be published manually, via `pnpm changeset publish`.
N/A
N/A
=> chore: create the alpha version of the CLI

.github/CODEOWNERS
Members of the Makeswift team that don't own this code are getting pinged for PRs that update this branch.
https://makeswifthq.slack.com/archives/C014SCS4G75/p1757962467576659
=> chore: remove makeswift team from codeowners file for integrations/makeswift

core/b2b/use-b2b-auth.ts
We recently added a feature to redirect to storefront for registration in checkout, we need to be able to take users back to checkout.
Sibling: 
- https://github.com/bigcommerce/b2b-buyer-portal/pull/542
- https://github.com/b3bc-external/b2b-checkout-app/pull/387
https://github.com/user-attachments/assets/e3831f86-48ef-4a22-9a28-c9d05cf7662b
You'll need to add the option to redirect to your checkout page in the useB2BAuth hook.
=> feat: add checkout as a valid landing location after registration

.changeset/twenty-ants-sip.md, core/vibes/soul/primitives/navigation/_actions/localized-pathname.ts, core/vibes/soul/primitives/navigation/index.tsx
Fix locale switcher on localized Makeswift pages with different paths.
https://github.com/user-attachments/assets/4658ebc5-088a-463c-804d-b0f80ae27c6f
N/A
=> fix: locale switcher correctly works w/ localized Makeswift paths
